### PR TITLE
Fix usage of contain finder options for hasMany relations

### LINKED ISSUE #10223: Contain usage of custom finder not working
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.0
* Platform and Target: Apache 2, PHP 7.1.1, MySQL 5.7

### What you did

```
        $jobs = $this->Jobs->find('active')
            ->contain(['JobLogs' => [
                'strategy' => 'select',
                'finder' => ['orphan' => ['node_id' => $nc->node_id()]]
            ]]);
```

Jobs is returned with all JobLogs records.

### What happened

Confirmed that finder is not called.

```
    public function findOrphan(Query $query, array $options = [])
    {
        dd('findOrphan');
    }
```

### What you expected to happen

Finder for contain should be used instead of find "All".

### PR DESCRIPTION
**Pull request by cleptric**
This fixes #10223 as the option didn't work anymore for `hasMany` relations.
I didn't created a new trait for `_extractFinder` and instead copied `Association::_extractFinder()`.

@lorenzo Thank you for your help 😄

### CODE REVIEW

File: tests/TestCase/ORM/QueryTest.php [hunk 1]
```diff
@@ -2817,6 +2817,108 @@ public function testContainFinderCanSpecifyOptions()
...
+                    'finder' => [
+                        'published' => [
+                            'title' => 'Foo'
+                        ]
+                    ]
+                ]
+            ]);
+
+        $this->assertSame(2, count($resultWithArticles->first()->articles));
+        $this->assertSame(2, count($resultWithArticlesArray->first()->articles));
```
Comment (markstory) [inline tests/TestCase/ORM/QueryTest.php]: You can use`assertCount()` to save some typing and get better failure messages.

File: src/ORM/Association/Loader/SelectLoader.php [hunk 2]
```diff
@@ -163,7 +163,14 @@ protected function _buildQuery($options)
             $options['fields'] = [];
         }
 
-        $fetchQuery = $finder()
+        if (isset($options['finder'])) {
+            list($finderName, $opts) = $this->_extractFinder($options['finder']);
+            $query = $finder()->find($finderName, $opts);
+        } else {
+            $query = $finder();
+        }
```
Comment (lorenzo) [inline src/ORM/Association/Loader/SelectLoader.php]: Another way to write this without the `else`

```
$query = $finder();
if (...) {
 ...
 $query = $query->find(..)
} // no else
```

File: src/ORM/Association/Loader/SelectLoader.php [hunk 3]
```diff
@@ -194,6 +201,33 @@ protected function _buildQuery($options)
...
+     * The following will call the finder 'translations' with the value of the finder as its options:
+     * $query->contain(['Comments' => ['finder' => ['translations']]]);
+     * $query->contain(['Comments' => ['finder' => ['translations' => []]]]);
+     * $query->contain(['Comments' => ['finder' => ['translations' => ['locales' => ['en_US']]]]]);
+     *
+     * @param string|array $finderData The finder name or an array having the name as key
+     * and options as value.
+     * @return array
+     */
+    protected function _extractFinder($finderData)
```
Comment (robertpustulka) [inline src/ORM/Association/Loader/SelectLoader.php]: Is it possible to support multiple finders, eg `['finder' => ['translations' => [], 'foo', 'bar']`?

Is is supported anywhere else?

Comment (lorenzo) [inline src/ORM/Association/Loader/SelectLoader.php]: it is not possible and not supported anywhere else.

**Comment by ADmad** [comment]
I made updates as per the feeback.
