### PR TITLE
4.x - Fix `cakephp/database` depending on `cakephp/log`.

### LINKED ISSUE #16824: [Database] `Error: Class 'Cake\Log\Engine\BaseLog' not found`
### Description

Hey,

I'm using the CakePHP Database library as standalone and I sometimes get the `Error: Class 'Cake\Log\Engine\BaseLog' not found` error.

Shouldn't the library work without the log library?

```
Error: Class 'Cake\Log\Engine\BaseLog' not found (Most recent call first)
File /var/www/_composer/vendor/cakephp/database/Log/QueryLogger.php:28
File /var/www/_composer/vendor/composer/ClassLoader.php:444 in include
File /var/www/_composer/vendor/composer/ClassLoader.php:322 in Composer\Autoload\includeFile
Show 2 non-project frames
File /var/www/_composer/vendor/cakephp/database/Connection.php:900 in class_exists
File /var/www/_composer/vendor/cakephp/database/Connection.php:920 in Cake\Database\Connection::getLogger
File /var/www/_composer/vendor/cakephp/database/Retry/ReconnectStrategy.php:113 in Cake\Database\Connection::log
File /var/www/_composer/vendor/cakephp/database/Retry/ReconnectStrategy.php:86 in Cake\Database\Retry\ReconnectStrategy::reconnect
File /var/www/_composer/vendor/cakephp/core/Retry/CommandRetry.php:74 in Cake\Database\Retry\ReconnectStrategy::shouldRetry
File /var/www/_composer/vendor/cakephp/database/Connection.php:287 in Cake\Core\Retry\CommandRetry::run
File /var/www/_composer/vendor/cakephp/database/Connection.php:335 in Cake\Database\Connection::prepare
File /var/www/_composer/vendor/cakephp/core/Retry/CommandRetry.php:70 in Cake\Database\Connection::Cake\Database\{closure}
File /var/www/_composer/vendor/cakephp/database/Connection.php:340 in Cake\Core\Retry\CommandRetry::run
File /var/www/_composer/vendor/cakephp/database/Query.php:250 in Cake\Database\Connection::run
```

### CakePHP Version

4.3.0

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by ndm2**
fixes #16824

### CODE REVIEW

File: src/Database/Connection.php [hunk 1]
```diff
@@ -919,7 +920,7 @@ public function getLogger(): LoggerInterface
             return $this->_logger;
         }
 
-        if (!class_exists(QueryLogger::class)) {
+        if (!class_exists(BaseLog::class)) {
```
Comment (othercorey) [inline src/Database/Connection.php:923]: This hidden dependency isn't very maintainable. I wonder if we can attach it to something.

File: src/Database/Retry/ReconnectStrategy.php [hunk 2]
```diff
@@ -110,7 +110,9 @@ protected function reconnect(): bool
 
         try {
             $this->connection->connect();
-            $this->connection->log('[RECONNECT]');
+            if ($this->connection->isQueryLoggingEnabled()) {
+                $this->connection->log('[RECONNECT]');
```
Comment (othercorey) [inline src/Database/Retry/ReconnectStrategy.php:114]: We should probably add a wrapper to log if a logger is attached.

**Comment by othercorey** [comment]
Nice find!

File: src/Database/Retry/ReconnectStrategy.php (hunk 2 above)
Comment (ndm2) [reply src/Database/Retry/ReconnectStrategy.php:114]: "_to_" as in _inside_ of `log()`, or as in _around_` (ie an additional method)?

Comment (othercorey) [reply src/Database/Retry/ReconnectStrategy.php:114]: As in inside of log.

Comment (ndm2) [reply src/Database/Retry/ReconnectStrategy.php:114]: Don't we want it to scream at people if no logger is available when something tries to log something?

File: src/Database/Connection.php (hunk 1 above)
Comment (ndm2) [reply src/Database/Connection.php:923]: Yeah, it's not overly nice, but at the moment I don't have any overly good ideas. There's more of those checks btw, for caching and for `CSPBuilder`.

File: src/Database/Retry/ReconnectStrategy.php (hunk 2 above)
Comment (othercorey) [reply src/Database/Retry/ReconnectStrategy.php:114]: I would say no. If you want logging, attach a logger.

Comment (othercorey) [reply src/Database/Retry/ReconnectStrategy.php:114]: All I'm saying is put the is logging enabled check inside the logging function. We should still error if creating the logger failed.

File: src/Database/Connection.php (hunk 1 above)
Comment (othercorey) [reply src/Database/Connection.php:923]: Yea, but this checks for a class that isn't being directly instantiated. That's all I'm saying. We probably should merge and fix this as-is though.

File: src/Database/Retry/ReconnectStrategy.php (hunk 2 above)
Comment (ndm2) [reply src/Database/Retry/ReconnectStrategy.php:114]: I see, I thought you meant to prevent the latter. I guess it could make sense to have the method obey the configuration, but since it's a public method, we probably can't change its behavior right now?

Comment (othercorey) [reply src/Database/Retry/ReconnectStrategy.php:114]: It's not blocking this PR, no.

Comment (othercorey) [reply src/Database/Retry/ReconnectStrategy.php:114]: Yea, "attached" can mean "was the logger successfully created". I meant it as "was logging enabled" which implies a logger should be attached.
