### PR TITLE
Fix incorrectly handled null action.

### LINKED ISSUE #14990: Controller/Component/AuthComponent.php declare(strict_types=1);
* [x] bug
* 4.x (master)

### What you did
// Instance reflection class of a controller (with AuthComponent)

$rcController = new \ReflectionClass($controllerClassName);
$obController = $rcController->newInstance();
$obController->startupProcess();

### What happened
Controller/Component/AuthComponent.php lines 271 and 330 TypeError.

Argument 1 passed to Cake\Controller\Controller::isAction() must be of the type string, null given, called in C:\wamp64\www\cakephp4\plugins\vendor\cakephp\cakephp\src\Controller\Component\AuthComponent.php on line 271

### Solution
Replace line 270
$action = $controller->getRequest()->getParam('action');
with 
$action = $controller->getRequest()->getParam('action', '');

Replace line 330
$action = strtolower($controller->getRequest()->getParam('action'));
with
$action = strtolower($controller->getRequest()->getParam('action', ''));

### PR DESCRIPTION
**Pull request by markstory**
Fixes #14990

### CODE REVIEW

File: tests/TestCase/Controller/Component/AuthComponentTest.php [hunk 1]
```diff
@@ -1652,6 +1652,36 @@ public function testStatelessAuthRedirectToLogin(): void
...
+            'url' => '/',
+            'session' => $this->Auth->session,
+        ]);
+        $this->Controller->setRequest($request);
+
+        $this->Auth->getController()->getRequest()->getSession()->clear();
+        $this->Auth->setConfig([
+            'authenticate' => ['Form'],
+            'authorize' => false,
+            'loginAction' => ['controller' => 'auth_test', 'action' => 'login']
```
Comment (othercorey) [inline tests/TestCase/Controller/Component/AuthComponentTest.php:1677]:
```suggestion
            'loginAction' => ['controller' => 'auth_test', 'action' => 'login'],
```
