### PR TITLE
5.x relax types in SelectBoxWidget

### LINKED ISSUE #17217: Cake5 float on form data
### Description

I have an existing test fail on Cake5 latest branch commit

> TypeError: Cake\View\Widget\SelectBoxWidget::_renderOptions(): Argument # 3 ($selected) must be of type array|string|int|false|null, float given, called in /.../vendor/cakephp/cakephp/src/View/Widget/SelectBoxWidget.php on line 176

I wonder if this should either also allow float or renderOptions() get a casted value if float is passed.

    (float) 0

seems to be the value that got passed.
All values seem to be int, but they come from this source:

    range(1, $options['stars']), range(1, $options['stars']))

which seems to return those ints as float.

### CakePHP Version

5.x

### PHP Version

8.2

### PR DESCRIPTION
**Pull request by markstory**
Fixes #17217

### CODE REVIEW

File: src/View/Widget/SelectBoxWidget.php [hunk 1]
```diff
@@ -209,7 +209,7 @@ protected function _renderOptgroup(
         string $label,
         ArrayAccess|array $optgroup,
         ?array $disabled,
-        array|string|int|false|null $selected,
+        mixed $selected,
```
Comment (othercorey) [inline src/View/Widget/SelectBoxWidget.php:212]: Need to update parameter type hint
