### PR TITLE
Fix rendering of dev error pages in 8.3

### LINKED ISSUE #17491: dev_error_stacktrace shows <?php even when it's not php code
### Description

image

Can't tell where but in `templates/element/dev_error_stacktrace.php` or `templates/element/exception_stack_trace.php` it adds a "<?php" to the beginning of each line. This isn't entirely correct because line 8 and 9 in my screenshot are HTML. 

### CakePHP Version

5.0.3

### PHP Version

8.3.1

### PR DESCRIPTION
**Pull request by markstory**
- Add PHP8.3 HTML formatting to the list of replacements.
- Update styling to make output visually consistent in 8.3

Fixes #17491

### CODE REVIEW

File: src/Error/Debugger.php [hunk 1]
```diff
@@ -617,9 +617,6 @@ public static function excerpt(string $file, int $line, int $context = 2): array
      */
     protected static function _highlight(string $str): string
     {
-        if (function_exists('hphp_log') || function_exists('hphp_gettid')) {
-            return htmlentities($str);
-        }
```
Comment (markstory) [inline src/Error/Debugger.php:622]: We don't support hhvm anymore.

File: src/Error/Debugger.php [hunk 2]
```diff
@@ -628,7 +625,7 @@ protected static function _highlight(string $str): string
         $highlight = highlight_string($str, true);
         if ($added) {
             $highlight = str_replace(
-                ['&lt;?php&nbsp;<br/>', '&lt;?php&nbsp;<br />'],
+                ['&lt;?php&nbsp;<br/>', '&lt;?php&nbsp;<br />', '&lt;?php'],
```
Comment (LordSimal) [inline src/Error/Debugger.php]: Do we want to replace the empty space  after `<?php` as well?

It feels weird to me if I see an extra white space in that output.

image

Especially if someone wants to copy paste stuff out of that code output.

**Review by LordSimal — APPROVED** [review]
