### PR TITLE
Expand types in TypeFactory and add fallback

### LINKED ISSUE #19054: TypeFactory - Missing $_types records for PostgreSQL types "inet", "cidr", "macaddr"
### TypeFactory - Missing $_types records for PostgreSQL types "inet", "cidr", "macaddr"

This causes a crash when attempting to insert a record via Form into the DB (Marshaller), but also, for example, during Fixture tests.

```
2025-11-14 20:03:26 error: [InvalidArgumentException] Unknown type `inet` in /app/watcher-nms/vendor/cakephp/cakephp/src/Database/TypeFactory.php on line 83
Stack Trace:
- CORE/src/ORM/Marshaller.php:79
- CORE/src/ORM/Marshaller.php:614
- CORE/src/ORM/Table.php:3073
- APP/Controller/RouterosDevicesController.php:184
- CORE/src/Controller/Controller.php:501
- CORE/src/Controller/ControllerFactory.php:166
- CORE/src/Controller/ControllerFactory.php:141
- CORE/src/Http/BaseApplication.php:362
- CORE/src/Http/Runner.php:86
- ROOT/vendor/cakephp/authorization/src/Middleware/RequestAuthorizationMiddleware.php:110
- CORE/src/Http/Runner.php:82
- ROOT/vendor/cakephp/authorization/src/Middleware/AuthorizationMiddleware.php:136
- CORE/src/Http/Runner.php:82
- ROOT/vendor/cakephp/authentication/src/Middleware/AuthenticationMiddleware.php:106
- CORE/src/Http/Runner.php:82
- ROOT/vendor/cakedc/users/src/Middleware/SocialEmailMiddleware.php:34
- CORE/src/Http/Runner.php:82
- ROOT/vendor/cakedc/users/src/Middleware/SocialAuthMiddleware.php:121
- CORE/src/Http/Runner.php:82
- CORE/src/Http/Middleware/CsrfProtectionMiddleware.php:169
- CORE/src/Http/Runner.php:82
- CORE/src/Http/Middleware/SecurityHeadersMiddleware.php:274
- CORE/src/Http/Runner.php:82
- CORE/src/Http/Middleware/BodyParserMiddleware.php:162
- CORE/src/Http/Runner.php:82
- CORE/src/Routing/Middleware/RoutingMiddleware.php:118
- CORE/src/Http/Runner.php:82
- CORE/src/Routing/Middleware/AssetMiddleware.php:71
- CORE/src/Http/Runner.php:82
- CORE/src/Error/Middleware/ErrorHandlerMiddleware.php:115
- CORE/src/Http/Runner.php:82
- CORE/src/Http/Runner.php:60
- CORE/src/Http/Server.php:98
- ROOT/webroot/index.php:37
- [main]:

Request URL: /routeros-devices/add
```

```
98) App\Test\TestCase\Model\Table\IpAddressRangesTableTest::testBuildRules
InvalidArgumentException: Unknown type `cidr`

/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/TypeFactory.php:83
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Type/ExpressionTypeCasterTrait.php:72
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Expression/ValuesExpression.php:311
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Expression/ValuesExpression.php:272
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Query.php:1705
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Query.php:1679
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Driver.php:564
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Driver.php:921
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Query.php:300
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Driver.php:396
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Driver.php:311
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Connection.php:300
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:71
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Connection.php:300
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Query.php:238
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:207
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:161
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:141
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/ConnectionHelper.php:159
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Connection.php:725
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php:71
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Connection.php:721
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/ConnectionHelper.php:159
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/Database/Connection.php:669
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/ConnectionHelper.php:158
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:139
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:120
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:133
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/Fixture/TruncateStrategy.php:52
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:294
/home/runner/work/Watcher-NMS/Watcher-NMS/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:244
/home/runner/work/Watcher-NMS/Watcher-NMS/tests/TestCase/Model/Table/IpAddressRangesTableTest.php:42
```

### CakePHP Version

5.3.0-RC1

### PHP Version

8.4

### PR DESCRIPTION
**Pull request by markstory**
- Add new abstract types to TypeFactory.
- Replace an exception on unknown type name with a fallback to String. Having string as a fallback makes extending the database typesystem easier as you aren't required to also define a type map unless you want custom behavior.

Fixes #19054

### CODE REVIEW

File: src/Database/TypeFactory.php [hunk 1]
```diff
@@ -32,32 +32,37 @@ class TypeFactory
...
         'timestampfractional' => Type\DateTimeFractionalType::class,
         'timestamptimezone' => Type\DateTimeTimezoneType::class,
+        'tinyinteger' => Type\IntegerType::class,
         'uuid' => Type\UuidType::class,
-        'nativeuuid' => Type\UuidType::class,
-        'linestring' => Type\StringType::class,
-        'geometry' => Type\StringType::class,
-        'point' => Type\StringType::class,
-        'polygon' => Type\StringType::class,
+        'year' => Type\StringType::class,
```
Comment (othercorey) [inline src/Database/TypeFactory.php]: Is year supposed to be a string?

Comment (markstory) [reply src/Database/TypeFactory.php]: It could be an integer. I'll update that.

**Review by othercorey — APPROVED** [review]
