### PR TITLE
4.next - Add required option support

### LINKED ISSUE #12498: Allow marking shell options as required
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.6
* Platform and Target: N/A

### What you did
It is useful sometimes to specify cli options as required, but at the moment we cant. 

This is most relevant If a cli has multiple required inputs - in this case it is currently only possible to enforce via the command parser by using (positional) arguments. 

Example, consider a shell with this options parser:

```
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();

        foreach(range(1,3) as $i) {
            $parser->addArgument("thing$i", [
                'help' => "Required thing $i",
                'required' => true
            ]);
        }

        return $parser;
    }
```

```
-> bin/cake my-cli --help
Usage:
cake my_cli [-h] [-q] [-v] <thing1> <thing2> <thing3>

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.

Arguments:

thing1  Required thing 1
thing2  Required thing 2
thing3  Required thing 3

-> bin/cake my-cli
Error: Missing required arguments. thing1 is required.
```
Although helpful, having to specify args in order is sometimes pretty awkward.

It's be much easier with this example to create a parser like so:

```
    public function getOptionParser()
    {
        $parser = parent::getOptionParser();

        foreach(range(1,10) as $i) {
            $parser->addOption("thing$i", [ <---- changed
                'help' => "Required thing $i",
                'required' => true <---- ignored 
            ]);
        }

        return $parser;
    }
```

But that only achieves the syntax I'm looking for:

```
-> cake/bin/cake my-cli --help
Usage:
cake my_cli [-h] [-q] [-v] [--thing1] [--thing2] [--thing3]

Options:

--help, -h     Display this help.
--quiet, -q    Enable quiet output.
--verbose, -v  Enable verbose output.
--thing1       Required thing 1
--thing2       Required thing 2
--thing3       Required thing 3
```
It does not enforce `required` as options are, according to the Shell class, always optional:

```
-> cake/bin/cake my-cli
Hello now going to try and do something in the main method and fail because required things are missing...
```

So, the ask here is simply to allow marking options required.

### PR DESCRIPTION
**Pull request by markstory**
Allow CLI flags to be marked as required flags/options.

Fixes #12498

### CODE REVIEW

File: src/Console/ConsoleInputOption.php [hunk 1]
```diff
@@ -192,6 +210,16 @@ public function defaultValue()
...
     }
 
+    /**
+     * Check if this option is required
+     *
+     * @return bool
+     */
+    public function isRequired(): bool
+    {
+        return (bool)$this->required;
```
Comment (ADmad) [inline src/Console/ConsoleInputOption.php:220]: The casting shouldn't be necessary.

File: src/Console/ConsoleOptionParser.php [hunk 2]
```diff
@@ -434,7 +435,8 @@ public function addOption($name, array $options = [])
                 $options['boolean'],
                 $options['default'],
                 $options['choices'],
-                $options['multiple']
+                $options['multiple'],
+                $options['required'],
```
Comment (othercorey) [inline src/Console/ConsoleOptionParser.php:439]:
```suggestion
                $options['required']
```

File: tests/TestCase/Console/ConsoleOptionParserTest.php [hunk 3]
```diff
@@ -330,6 +332,38 @@ public function testAddMultipleOptionsWithMultiple()
...
+            $result[0]
+        );
+
+        $result = $parser->parse(['--no-default', 'value']);
+        $this->assertSame(
+            ['no-default' => 'value', 'help' => false, 'test' => 'default value'],
+            $result[0]
+        );
+
+        $this->expectException(ConsoleException::class);
```
Comment (othercorey) [inline tests/TestCase/Console/ConsoleOptionParserTest.php:363]: If the first parse throws an exception, does phpunit mark the remaining asserts as fails?

Comment (markstory) [reply tests/TestCase/Console/ConsoleOptionParserTest.php:363]: Anything that happens before expectException should still get counted as passed. Nothing will happen after the exception is raised though.

Comment (othercorey) [reply tests/TestCase/Console/ConsoleOptionParserTest.php:363]: I prefer to have exception tests in a separate function to avoid capturing it for other tests so nothing is skipped.

Comment (markstory) [reply tests/TestCase/Console/ConsoleOptionParserTest.php:363]: Ok. I can split them up.
