### PR TITLE
Fix passedParams with object values

### LINKED ISSUE #16307: bypass coerceStringToType when source type is equal param type
### Description

In case of using custom routing classes, for passing and manipulating pass params. In this case the custom routing class return the parameters in the correct target type. This generates a type error in  the controllerFactory.
When the source paramtype equal target param type in this case cann we bypass the the coerceStringToType conversion

In (vendor\cakephp\cakephp\src\Controller\ControllerFactory.php) ControllerFactory[204] after 
```
// Use any passed params as positional arguments
            if ($passedParams) {
                $argument = array_shift($passedParams);
```

```
if ($type->getName() === \get_debug_type($argument)) {
                    $resolved[] = $argument;
                    continue;
                }
```

### CakePHP Version

4.3.4

### PHP Version

8.0

### PR DESCRIPTION
**Pull request by markstory**
We never really defined the types for `passedParams` so userland code relies on that now. I think it provides some clever solutions like adding automatic ORM entity resolution via middleware that I'd like to make it formally work.

Fixes #16307

### CODE REVIEW

File: src/Controller/ControllerFactory.php [hunk 1]
```diff
@@ -174,8 +174,16 @@ protected function getActionArgs(Closure $action, array $passedParams): array
...
-                    $resolved[] = $this->container->get($type->getName());
+                $typeName = $type->getName();
+                if ($this->container->has($typeName)) {
+                    $resolved[] = $this->container->get($typeName);
+                    continue;
+                }
+
+                // Use passedParams as a source of typed dependencies.
+                // The accepted types for passedParams was never defined and userland code relies on that.
+                if ($passedParams && is_object($passedParams[0]) && $passedParams[0] instanceof $typeName) {
```
Comment (ADmad) [inline src/Controller/ControllerFactory.php:185]: Why check for objects only? Scalar types could also be pre converted in passed args.

Comment (markstory) [reply src/Controller/ControllerFactory.php:185]: Because the guard condition above is for non-builtin types. The scalar values are all builtin.

Comment (ADmad) [reply src/Controller/ControllerFactory.php:185]: Ah sorry, I missed the `!$type->isBuiltin()` check above.
