### PR TITLE
Make Table::aliasField() idempotent.

### LINKED ISSUE #9244: 3.3 running Table::aliasField($field) multiple times should be idempotent
This is a (multiple allowed):
* [x] enhancement
* [x] feature-discussion (RFC)

* CakePHP Version: 3.3 BETA 3

### What you did
Implicitly ran `Table::aliasField()` multiple times
Ref: https://github.com/FriendsOfCake/search/issues/111

### Expected Behavior
To only alias the field once - or at least have an option to do that.

### Actual Behavior
The fields where alias multiple times resulting in incorrect query-snipplets such as `Countries.Countries.code IN (:c0)`

### PR DESCRIPTION
**Pull request by ADmad**
Closes #9244

We don't support table column names with dot right? :)

### CODE REVIEW

File: src/ORM/Table.php [hunk 1]
```diff
@@ -371,11 +371,17 @@ public function alias($alias = null)
...
      * Alias a field with the table's current alias.
      *
+     * If field is already aliased it will result in no-op.
+     *
      * @param string $field The field to alias.
      * @return string The field prefixed with the table alias.
      */
     public function aliasField($field)
     {
+        if (strpos($field, '.') !== false) {
```
Comment (htstudios) [inline src/ORM/Table.php]: // In case you want to make sure things don't break (untested):
list($alias, $tmpField) = pluginSplit($field);
$tmpField = $this->alias() . '.' . $tmpField;
if ($tmpField === $field) {
    return $field;
}
return $tmpField;

Comment (ADmad) [inline src/ORM/Table.php]: I don't think `foo.bar.baz` would ever be a valid name so there are no BC concerns imo.

Comment (htstudios) [inline src/ORM/Table.php]: I tend to agree. However some advanced RDBMS allow database schema cluster whatever as dotnotations.
I am fine with the PR like it is! <3

**Comment by markstory** [comment]
> We don't support table column names with dot right? :)

No but we do support database prefixed column/table references like `db.Table.column`.

File: src/ORM/Table.php (hunk 1 above)
Comment (markstory) [inline src/ORM/Table.php]: This won't work well with schema prefixed column names. You could do `strpos($field, $alias) !== false`

**Comment by ADmad** [comment]
> No but we do support database prefixed column/table references like db.Table.column.

Okay but that can't achieve using `aliasField()` anyway.

**Comment by markstory** [comment]
@ADmad Good point, it didn't work before, and it won't work now either.
