### PR TITLE
Fix custom type overrides not be using in fixtures

### LINKED ISSUE #16067: TestFixture::_schemaFromReflection getting "wrong" column type (Sqlite, Json)
### Description

When using the new Fixture System and relying on `TestFixture::_schemaFromReflection` instead of specifying fields in the Fixture file CakePHP is not taking `_initializeSchema` of the table into consideration.

Having 2 json columns in a sqlite database result in errors inserting the fixture data now.

Within the Migration:

```php
            ->addColumn('excluded_articles', 'json', [
                'default' => null,
                'length' => null,
                'null' => true,
            ])
```

within the table:

```php
    protected function _initializeSchema(TableSchemaInterface $schema): TableSchemaInterface
    {
        $schema->setColumnType('excluded_articles', 'json');

        return $schema;
    }
```

within the fixture:

```php
        $this->records = [
            [
                ...
                'excluded_articles' => [],
                ...
            ],
```

error message:
```log
InvalidArgumentException: Cannot convert value of type `array` to string
```

Note: it is currently working just fine for PostgreSQL because it has a json column type but it's not for sqlite.

### CakePHP Version

4.3.0

### PHP Version

8.0

### PR DESCRIPTION
**Pull request by markstory**
When fixtures are reflecting schema they should use the ORM table
classes to get the schema data, as tables can re-map types and fixtures
and tests are likely to rely on those custom types.

Fixes #16067

### CODE REVIEW

File: src/TestSuite/Fixture/TestFixture.php [hunk 1]
```diff
@@ -245,20 +245,17 @@ protected function _schemaFromImport(): void
...
-
-        if (!in_array($this->table, $tables, true)) {
-            throw new CakeException(
-                sprintf(
-                    'Cannot describe schema for table `%s` for fixture `%s`: the table does not exist.',
-                    $this->table,
-                    static::class
-                )
+        try {
+            $table = $this->fetchTable($this->table, ['connection' => $db]);
```
Comment (othercorey) [inline src/TestSuite/Fixture/TestFixture.php]: This doesn't match the alias name used in Table so this schema and the Table schema instances are different.

Comment (markstory) [reply src/TestSuite/Fixture/TestFixture.php]: Well we have no way of getting the alias name for a table. This has a better chance of success than before though.

Comment (ADmad) [reply src/TestSuite/Fixture/TestFixture.php]: `$this->table` is the actual db table name right? Should we then at least camelize it to increase the probability of matching table alias?

Comment (othercorey) [reply src/TestSuite/Fixture/TestFixture.php]: We have to allow two things for this to work:

* The name in the fixture can be either the db table name or the model Table name
* If the fixture name doesn't load a Table name then we canonicalize it and load that Table name

This requires changes for users with unconventional Table names + custom schema, but it will have the same behavior otherwise. If the 2nd Table isn't found, that default behavior (generated db table name and schema) will work like we had before.

Comment (markstory) [reply src/TestSuite/Fixture/TestFixture.php]: > $this->table is the actual db table name right?

Yes it is. ~~Using the fixture name like @othercorey mentioned is probably a safer bet.~~ 

Fixtures currently inflect their table name from the fixture name if the `$table` property isn't defined. If we're worried about oddly named tables, we'd need additional properties to cover that scenario as fixture names don't have to match up with the model name they are for. Inflecting the table is probably our best bet unless we want to add more attributes.

Comment (othercorey) [reply src/TestSuite/Fixture/TestFixture.php]: As long as there is a Table that matches the expected name, this should work. I don't know what situation users have where that isn't the case. Maybe some weird transition using an old table with a new model name.

Otherwise TestFixture::$table would have to support a Table name.
