### PR TITLE
Removing legacy output buffer handling in Response::file().

### LINKED ISSUE #7974: Exception in tests give risky test as result
Hi guys,

I created a controller-test that should get an exception. I asserted on this, and my test worked great, however, PHPUnit marks my test as risky. Using `verbose` gave me the following information:

> Test code or tested code did not (only) close its own output buffers

Googling on this brought me to this: https://github.com/Codeception/Codeception/issues/1262

(intersting comment: https://github.com/Codeception/Codeception/issues/1262#issuecomment-52419252)

I'm not an expert, but I guess Cakephp needs a small change to close the output buffer on an exception. Anybody knows how to make this work?

### PR DESCRIPTION
**Pull request by lorenzo**
This made it possible to correctly test file sending in IntegrationTestCase.

Fixes #7974

### CODE REVIEW

File: src/TestSuite/IntegrationTestCase.php [hunk 1]
```diff
@@ -878,11 +879,31 @@ public function assertCookie($expected, $name, $message = '')
...
+            $this->fail('No response set, cannot assert cookies.');
         }
         $result = $this->_response->cookie($name);
         $this->_cookieEncriptionKey = $key;
         $result['value'] = $this->_decrypt($result['value'], $encrypt);
         $this->assertEquals($expected, $result['value'], 'Cookie data differs. ' . $message);
     }
+
+    /**
+     * Asserts that a file with the fiven name was sent in the response
```
Comment (ADmad) [inline src/TestSuite/IntegrationTestCase.php]: Typo "fiven"

**Comment by markstory** [comment]
:clap:
