### PR TITLE
Shorten paths in error logs

### LINKED ISSUE #17671: shorten stack trace file paths
### Description

In the logs, often the trace is unnecessarily long:
```
Stack Trace:
- /home/clients/f6204f36e6ee43c547b7635b726cb6Xf/sites/test.xyz.com/src/Model/Table/EventsTable.php:414
- /home/clients/f6204f36e6ee43c547b7635b726cb6Xf/sites/test.xyz.com/src/Controller/Api/EventsController.php:58
- ....
```

Whereas the path to ROOT is clear and repeating all the time

Could we just provide it by replacing ROOT with empty string?

```
Stack Trace:
- vendor/...
- src/Model/Table/EventsTable.php:414
- src/Controller/Api/EventsController.php:58
- ....
```
etc?

Makes it also more readable if the length doesn't quite fit on the screen otherwise.

### CakePHP Version

5.x

### PR DESCRIPTION
**Pull request by markstory**
Switch to using application relative paths in log messages.  There are a few other places we generate stacktraces but those are currently using `Exception::getTraceAsString()`. If this doesn't address the problem with logging, I can revise those call sites as well.

Fixes #17671

### CODE REVIEW

File: tests/TestCase/Error/DebuggerTest.php [hunk 1]
```diff
@@ -601,6 +601,13 @@ public function testTraceExclude(): void
         $this->assertDoesNotMatchRegularExpression('/^Cake\\\Test\\\TestCase\\\Error\\\DebuggerTest..testTraceExclude/m', $result);
     }
 
+    public function testTraceShortPoints(): void
+    {
+        $result = Debugger::trace(['format' => 'shortPoints']);
+        $this->assertIsArray($result);
+        $this->assertEquals('CORE/vendor/phpunit/phpunit/src/Framework/TestCase.php', $result[0]['file']);
```
Comment (dereuromark) [inline tests/TestCase/Error/DebuggerTest.php]: What does CORE stand for?
I would expect that to be vendor/cakephp/cakephp

Wouldnt this be just `ROOT/...` or even `vendor/phpunit/phpunit/src/Framework/TestCase.php`

File: src/Error/Debugger.php [hunk 2]
```diff
@@ -400,7 +401,13 @@ public static function formatTrace(Throwable|array $backtrace, array $options =
             if (in_array($signature, $options['exclude'], true)) {
                 continue;
             }
-            if ($options['format'] === 'points') {
+            if ($options['format'] === 'shortPoints') {
```
Comment (LordSimal) [inline src/Error/Debugger.php:404]: ~I believe this should be `shortPath` 😅~ scrap that, I misunderstood

File: tests/TestCase/Error/DebuggerTest.php (hunk 1 above)
Comment (markstory) [reply tests/TestCase/Error/DebuggerTest.php]: CORE is a long standing 'short path' that goes to cakephp within `vendor`. We could remove that alias but it will impact debugkit and possibly userland usage.

Comment (dereuromark) [reply tests/TestCase/Error/DebuggerTest.php]: Thats my point: Why would it be `CORE/vendor/phpunit/phpunit/src/Framework/TestCase.php` then?
As that would resolve into `vendor/cakephp/cakephp/vendor/phpunit/phpunit/...`

Comment (ADmad) [reply tests/TestCase/Error/DebuggerTest.php]: I agree with @dereuromark. The path before the `vendor` folder would be ROOT, not CORE.

Comment (markstory) [reply tests/TestCase/Error/DebuggerTest.php]: Ah ok. I didn't pick up on CORE being a prefix to vendor directories. I think this is caused by how we have constants configured in the tests suite. Currently the `CORE` alias is used when paths are prefixed with `CAKE_CORE_INCLUDE_PATH` which we set to `ROOT` in `tests/bootstrap.php`.

Comment (dereuromark) [reply tests/TestCase/Error/DebuggerTest.php]: Then it sounds fine here I guess?

Comment (ADmad) [reply tests/TestCase/Error/DebuggerTest.php]: The slashes in `$result[0]['file']` need to be normalized to `/` or use `DS` in the expected string to fix the failure on Windows.
