### PR TITLE
Making I18n in Text Class optional

### LINKED ISSUE #18131: Broken module dependency
### Description

Module [Utility](https://github.com/cakephp/utility) depends on module [i18n](https://github.com/cakephp/i18n):
https://github.com/cakephp/cakephp/blob/ab02056c1e6d9fbd7ec68bb21dcdf72fd1d88e18/src/Utility/Text.php#L22C1-L22C28

The problem is that when using Utility module outside Cake projects it's broken, since it doesn't list the dependency in [compser.json](url)

### CakePHP Version

5

### PHP Version

8.1

### PR DESCRIPTION
**Pull request by hvallieri**
I fixed this to avoid the `I18n` dependency in the `Text` Class (by the way not declared in [composer.json](https://github.com/cakephp/utility/blob/5.x/composer.json) of `cakephp/utility`)

### CODE REVIEW

File: src/Utility/Text.php [hunk 1]
```diff
@@ -891,7 +891,9 @@ public static function excerpt(string $text, string $phrase, int $radius = 100,
      */
     public static function toList(array $list, ?string $and = null, string $separator = ', '): string
     {
-        $and ??= __d('cake', 'and');
+        $defaultAnd = function_exists('__d') ? __d('cake', 'and') : 'and';
```
Comment (dereuromark) [inline src/Utility/Text.php]: Not sure if we should put this into a conditions check to avoid it being created at runtime every time.

Comment (hvallieri) [reply src/Utility/Text.php]: Would you like to save the condition check in a property like in [`Validator`](https://github.com/cakephp/cakephp/blob/5.x/src/Validation/Validator.php#L168)?

Comment (ADmad) [inline src/Utility/Text.php]:
```suggestion
        static $defaultAnd ??= function_exists('__d') ? __d('cake', 'and') : 'and';
```

This should avoid the function_exits() call on each invocation of the toList() method.

Comment (hvallieri) [reply src/Utility/Text.php]: A static variable would solve the problem but prior PHP 8.3 you couldn't assign values from dynamic expressions to static variables (see [doc](https://www.php.net/manual/en/language.variables.scope.php)). 
The requirements for version 5.x are [>= 8.1](https://github.com/cakephp/cakephp/blob/5.x/composer.json#L25)

Comment (ADmad) [reply src/Utility/Text.php]: Guess we need to use a static property then.

File: src/Utility/Text.php [hunk 2]
```diff
@@ -50,6 +50,13 @@ class Text
         'script',
     ];
 
+    /**
+     * Whether to use I18n functions for translating default error messages
+     *
+     * @var bool
+     */
+    protected static bool $_useI18n;
```
Comment (ADmad) [inline src/Utility/Text.php]:
```suggestion
    protected static bool $useI18n;
```

We don't use underscore prefix for protected properties anymore.

File: src/Utility/Text.php [hunk 3]
```diff
@@ -891,7 +898,9 @@ public static function excerpt(string $text, string $phrase, int $radius = 100,
      */
     public static function toList(array $list, ?string $and = null, string $separator = ', '): string
     {
-        $and ??= __d('cake', 'and');
+        static::$_useI18n ??= function_exists('__d') === true;
+        $and ??= (static::$_useI18n === true ? __d('cake', 'and') : 'and');
```
Comment (ADmad) [inline src/Utility/Text.php]:
```suggestion
        static::$useI18n ??= function_exists('__d');
        $and ??= static::$useI18n ? __d('cake', 'and') : 'and');
```

Comparing booleans with a boolean is redundant, directly use the boolean value.

File: src/Utility/Text.php [hunk 4]
```diff
@@ -891,7 +898,9 @@ public static function excerpt(string $text, string $phrase, int $radius = 100,
      */
     public static function toList(array $list, ?string $and = null, string $separator = ', '): string
     {
-        $and ??= __d('cake', 'and');
+        static::$_useI18n ??= function_exists('__d') === true;
```
Comment (garas) [inline src/Utility/Text.php]:
```suggestion
        static::$_useI18n ??= function_exists('Cake\I18n\__d') === true;
```

File: src/Utility/Text.php (hunk 3 above)
Comment (hvallieri) [reply src/Utility/Text.php]: As you want, the comparison is safer and for more clarity in reading the code.

File: src/Utility/Text.php (hunk 2 above)
Comment (hvallieri) [reply src/Utility/Text.php]: Better without underscores: this Class needs a refactoring...

File: src/Utility/Text.php (hunk 4 above)
Comment (hvallieri) [reply src/Utility/Text.php]: The function is imported at the beginning of the file; including the namespace in this way is prone to bugs in future refactorings...

Comment (garas) [reply src/Utility/Text.php]: `function_exists` doesn't check `use` imports.

`function_exists('__d')` checks for global `__d()` which might be undefined when using `cakephp/*` subpackages separately.

Comment (hvallieri) [reply src/Utility/Text.php]: True, anyway be careful in case of refactoring

**Review by ADmad — APPROVED** [review]

File: src/Utility/Text.php (hunk 4 above)
Comment (ADmad) [reply src/Utility/Text.php]: @garas Thanks, I missed that.

**Comment by markstory** [comment]
Thank you 🎉
