### PR TITLE
Fix .json routes not rendering error pages properly

### LINKED ISSUE #12834: Exeption in json route no render json (cakephp 3.7)
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.7.1 : 1f6fd21ca27ffc88fa88506a400b94a809e29254
* Platform and Target: apache php 7.0.12

### What you did
In fresh cakephp 3.7.1 install, I create an API.

In my route.php
```php
Router::scope('/', function (RouteBuilder $routes) {
    $routes->setExtensions(['json']);
	//...
});
```

In AppController
```php
public function initialize()
    {
        parent::initialize();

        $this->loadComponent('RequestHandler', [
            'enableBeforeRedirect' => false,
        ]);
        $this->loadComponent('Flash');

        /*
         * Enable the following component for recommended CakePHP security settings.
         * see https://book.cakephp.org/3.0/en/controllers/components/security.html
         */
        //$this->loadComponent('Security');
    }
```

My TestController
```php
<?php
namespace App\Controller;

use Cake\Http\Exception\NotFoundException;

class TestController extends AppController
{
    public function success()
    {
        $this->set([
            'test' => true,
            '_serialize' => ['test']
        ]);
    }

    public function error()
    {
        throw new NotFoundException();
    }
}
```

A simple view for test
```
<script>
    fetch('/Test/error.json')
    fetch('/Test/success.json')
</script>
```

### What happened

* /Test/success.json
success

* /Test/error.json
error

### What you expected to happen

I would like, as with cakephp 3.6 for error.json

error2

### PR DESCRIPTION
**Pull request by markstory**
Due to changes in #11978 the original request state was preserved. This is a good thing as it makes control flow more explicit however, it has the side-effect of parsed extensions being 'lost' as the request error handler has access to is detached from the one Router mutated.

By using the Router state to apply routing if available we can fix #12834. I'm using the `controller` param as a hint for empty params as controller is a required router output key.

### CODE REVIEW

File: src/Error/ExceptionRenderer.php [hunk 1]
```diff
@@ -125,9 +125,18 @@ protected function _unwrap($exception)
...
+        // $_SERVER
         if ($request === null) {
-            $request = ServerRequestFactory::fromGlobals();
+            $request = $routerRequest ?: ServerRequestFactory::fromGlobals();
+        }
+
+        // If the current request doesn't have routing data, but we
+        // found a request in the router context copy the params over
+        if ($request->getParam('controller') === false && $routerRequest !== null) {
+            $request = $request->withAttribute('params', $routerRequest->getAttribute('params'));
```
Comment (saeideng) [inline src/Error/ExceptionRenderer.php]: why not whole request ?
```
if ($request->getParam('controller') === false && $routerRequest !== null) {
            $request =$routerRequest;
```

Comment (markstory) [reply src/Error/ExceptionRenderer.php]: I was concerned with overwriting headers or transformed data.
