### PR TITLE
Merging queryBuilders in contain. Fixes #6696

### LINKED ISSUE #6696: Composing multiple contain()s for the same relationship
Just getting this documented. As discussed at Cakefest, the ORM is not currently able to compose together multiple [`Query::contain()`](https://github.com/cakephp/cakephp/blob/3a8e70ef46c633ed09e34fb19bb3a75e066d04cd/src/ORM/Query.php#L266) clauses _for the same relationship_. This issue is more fully documented (with sample code and failing tests) in a sample repo here: https://github.com/beporter/cake3-tests#composing-contain-clauses

Loadsys intends to work on a PR to provide this functionality (if the core team doesn't beat us to it.)

The tl;dr version follows: 

The following code only filters the `Comments` association by `Comments.published_date`, but not **also** by `Comments.author`.

```php
$this->Posts->find()
    ->contain(['Comments' => function ($q) {
        return $q->andWhere([
            'Comments.author' => 'John Doe',
        ]);
    }])
    ->contain(['Comments' => function ($q) {
        return $q->andWhere([
            'Comments.published_date >=' => new Time('7 days ago'),
        ]);
    }]);
```

Now obviously this is a contrived example since both `andWhere()`s could be consolidated into the same closure, but what if we had two different custom finder methods that tried to do this separately?

```php
class PostsTable extends Table
{
    public function findCommenter(Query $query, array $options)
    {
        if (!count($options)) {
        	return $query;
        }
        $authorName = array_shift($options);

        $query->contain(['Comments' => function ($q) use ($authorName) {
            return $q->andWhere([
                'Comments.author' => $authorName,
            ]);
        }]);
        return $query;
    }

    public function findRecent(Query $query, array $options)
    {
        $query->contain(['Comments' => function ($q) {
            return $q->andWhere([
                'Comments.published_date >=' => new Time('7 days ago'),
            ]);
        }]);
        return $query;
    }
}
```

Now when you try to compose these together, you end up with only the _last_ `contain()` used:

`$this->Posts->find('commenter', ['John Doe'])->find('recent');`

In this example, we will end up with **only** the `recent` conditions being met.

### PR DESCRIPTION
**Pull request by lorenzo**
This makes it a lot easir to break queries into multiple custom finders
where the same assocaition is used multiple times in contain. It also
brings the orm closer to the behavior in 2.x where you could appen to a contain
clause anywhere.

### CODE REVIEW

**Comment by markstory** [comment]
Nice work! :+1: Should the docs be updated for this? Or is this making the code work the way people expect?

**Comment by lorenzo** [comment]
I can add it to the docs. I think it is worth mentioning, although it is how people would expect it to work

File: src/ORM/EagerLoader.php [hunk 1]
```diff
@@ -309,6 +309,15 @@ protected function _reformatContain($associations, $original)
             }
 
             $pointer += [$table => []];
+
+            if (isset($options['queryBuilder']) && isset($pointer[$table]['queryBuilder'])) {
+                $first = $pointer[$table]['queryBuilder'];
+                $second = $options['queryBuilder'];
+                $options['queryBuilder'] = function ($query) use ($first, $second) {
+                    return $second($first($query));
```
Comment (jippi) [inline src/ORM/EagerLoader.php]: :boom:

**Comment by beporter** [comment]
:tada:
