### PR TITLE
Make test suite compatible with PHPUnit 5.

### LINKED ISSUE #9973: 2.x PHPunit 3.7.38 doesn't play nicely with PHP 7
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 2.9.4
* Platform and Target: Centos 7 PHP 7.1.0

### What you did
```php
class MyModel extends Model {
    public function doSomething(array $data): array {
        // ....
    }
}
```

### What happened
Mocking the model with `$this->getMockForModel('MyModel');` results in the following error:

```
Declaration of Mock_MyModel_bea013db::doSomething(array $data = Array) must be compatible with MyModel::doSomething(array $data = Array): array	
```

Not just `getMockForModel` of course, all mocking methods do this.

### What you expected to happen
Model is successfully mocked.

Are there any plans to update PHPunit?

### PR DESCRIPTION
**Pull request by mtricht**
Sadly there are 1200 deprecation warnings for `getMock`, but at least we can use PHP7 features now!

Closes #9973

### CODE REVIEW

**Comment by markstory** [comment]
Do you know if PHPUnit runs the test method when there is a warning? I thought it bailed as soon as the warning condition was hit.

File: lib/Cake/TestSuite/CakeTestCase.php [hunk 1]
```diff
@@ -655,7 +655,7 @@ protected function expectError($expected = false, $message = '') {
  * @deprecated 3.0.0 This is a compatibility wrapper for 1.x. It will be removed in 3.0.
```
Comment (inoas) [inline lib/Cake/TestSuite/CakeTestCase.php]: OT: ... removed in 3.0?

**Comment by swordbeta** [comment]
@markstory It executes the test yes.

@inoas looks like it has been removed https://github.com/cakephp/cakephp/blob/3.next/src/TestSuite/TestCase.php

**Comment by josegonzalez** [comment]
This is probably fine for merging, right @markstory ?

**Comment by markstory** [comment]
Sure. I have no time to deal with PHPUnit deprecations in 2.x, perhaps someone else can take it on?
