### PR TITLE
Fix cookie expire set to 1 when app timezone is not UTC

### LINKED ISSUE #17048: Expire cookie when App defaultTimezone is not UTC
### Description

Cakephp 4.x
How to reproduce : 

Configuration
```php
# config/app.php
  'defaultTimezone' => 'Europe/Paris',
```

Tests controller
```php
<?php
declare(strict_types=1);

namespace App\Controller;

use Cake\Http\Cookie\Cookie;

class TestsController extends AppController
{
    public function setCookie()
    {
        $cookie = new Cookie('testing', 'my value');
        $this->setResponse($this->response->withCookie($cookie));

        return $this->redirect('/tests/readCookie');
    }

    public function readCookie()
    {
        if ($this->request->getCookieCollection()->has('testing')) {
            $cookie = $this->request->getCookieCollection()->get('testing');
            debug($cookie);
        } else {
            debug('No cookie. Yeah!');
        }
        exit;
    }

    public function expireCookie()
    {
        $cookie = $this->request->getCookieCollection()->get('testing');
        $this->setResponse($this->response->withExpiredCookie($cookie));

        return $this->redirect('/tests/readCookie');
    }
}
```

Url : `/tests/setCookie` redirect to `/tests/readCookie`. Cookie is displayed
Url : `/tests/expireCookie` redirect to `/tests/readCookie`. Cookie should not be displayed but it is.

Changing the `App.defaultTimezone` fix this.

### CakePHP Version

4.4.11

### PHP Version

_No response_

### PR DESCRIPTION
**Pull request by Erwane**
Try to fix #17048

### CODE REVIEW

File: src/Http/Cookie/Cookie.php [hunk 1]
```diff
@@ -621,7 +621,7 @@ public function withNeverExpire()
     public function withExpired()
     {
         $new = clone $this;
-        $new->expiresAt = new DateTimeImmutable('1970-01-01 00:00:01');
+        $new->expiresAt = new DateTimeImmutable('1970-01-01 00:00:01', new DateTimeZone('UTC'));
```
Comment (ADmad) [inline src/Http/Cookie/Cookie.php]: This seems quite redundant. Expiring/deleting a cookie just requires setting a time in the past and `1970-01-01 00:00:01` will always be in the past regardless of the timezone.

Comment (Erwane) [reply src/Http/Cookie/Cookie.php]: Not exactly. if "expire" timestamp in cookie is negative, the expires is not effective in browser.
I don't know why but i have made an example in the issue.

Comment (ADmad) [reply src/Http/Cookie/Cookie.php]: Ah, for time zones behind UTC using this datetime string can generate a negative timestamp. We can change it to `new DateTimeImmutable('@1')` instead of creating timezone instance.

Comment (Erwane) [reply src/Http/Cookie/Cookie.php]: (maybe php setcookie() function bug)

Comment (ADmad) [inline src/Http/Cookie/Cookie.php]:
```suggestion
        $new->expiresAt = new DateTimeImmutable('@1');
```

Comment (Erwane) [reply src/Http/Cookie/Cookie.php]: oops, sorry, i haven't saw your change :(
I've committed it.

Comment (ADmad) [reply src/Http/Cookie/Cookie.php]: no problem

File: tests/TestCase/Http/Cookie/CookieTest.php [hunk 2]
```diff
@@ -236,6 +236,21 @@ public function testWithExpired(): void
...
+     * Test the expired method
+     */
+    public function testWithExpiredNotUtc(): void
+    {
+        date_default_timezone_set('Europe/Paris');
+
+        $cookie = new Cookie('cakephp', 'cakephp-rocks');
+        $new = $cookie->withExpired();
+
+        $this->assertStringContainsString('01-Jan-1970 00:00:01 UTC', $new->toHeaderValue());
```
Comment (ADmad) [inline tests/TestCase/Http/Cookie/CookieTest.php]:
```suggestion
        $this->assertStringContainsString('01-Jan-1970 00:00:01 GMT+0000', $new->toHeaderValue());
```

File: tests/TestCase/Http/ResponseTest.php [hunk 3]
```diff
@@ -910,6 +910,19 @@ public function testWithExpiredCookieObject(): void
...
+    {
+        date_default_timezone_set('Europe/Paris');
+
+        $response = new Response();
+        $cookie = new Cookie('yay', 'a value');
+        $response = $response->withExpiredCookie($cookie);
+
+        $this->assertSame(1, $response->getCookie('yay')['expires']);
+
+        date_default_timezone_set('UTC');
```
Comment (markstory) [inline tests/TestCase/Http/ResponseTest.php]:
```suggestion
        date_default_timezone_set('UTC');
        
        $this->assertSame(1, $response->getCookie('yay')['expires']);
```

**Comment by markstory** [comment]
Thank you 🎉
