### PR TITLE
Bubble up exception if it is clearly to be not swallowed away.

### LINKED ISSUE #6422: 3.0: We need better IntegrationTestCase 5xx debugging
Currently, the result of an unexpected 5xx error would just show as 
```
1) App\Test\TestCase\Controller\AccountControllerTest::testEdit
Status code is not 200 but 500
Failed asserting that 500 is equal to 200 or is less than 200.
```

No logs entry, no additional data on what went wrong. Impossible to debug at that point.

One way would be `file_put_contents(TMP . 'x' . rand(1, 1000) . '.html', $this->_response->body());` from within `IntegrationTestCase ::_assertStatus()`
to actually find the error via generated body HTML content.

Turns out it was 
```
An Internal Error Has Occurred

Error: The "Passwordable" alias has already been loaded with the following config: array...
```

Any way to capture that in integration tests and let it bubble up somewhere?

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/6422

Before:

```
1) App\Test\TestCase\Controller\AccountControllerTest::testEdit
Status code is not 200 but 500
Failed asserting that 500 is equal to 200 or is less than 200.
```

:-1: 

Now it properly shows whats wrong:

```
1) App\Test\TestCase\Controller\AccountControllerTest::testEdit
RuntimeException: The "Passwordable" alias has already been loaded with the foll
owing config: array (
  'field' => 'password',
  'confirm' => true,
  'require' => true,
) which differs from array (
  'require' => false,
)

...\app\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php:138
...\app\vendor\cakephp\cakephp\src\Core\ObjectRegistry.php:74
...\app\vendor\cakephp\cakephp\src\ORM\Table.php:600
...\app\src\Controller\AccountController.php:181
...\app\vendor\cakephp\cakephp\src\Controller\Controller.php:41
0
...\app\vendor\cakephp\cakephp\src\Routing\Dispatcher.php:114
...\app\vendor\cakephp\cakephp\src\Routing\Dispatcher.php:87
...\app\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCas
e.php:285
...\app\vendor\cakephp\cakephp\src\TestSuite\IntegrationTestCas
e.php:197
...\app\tests\TestCase\Controller\AccountControllerTest.php:244
```

:+1:

### CODE REVIEW

File: src/TestSuite/IntegrationTestCase.php [hunk 1]
```diff
@@ -445,6 +454,11 @@ protected function _assertStatus($min, $max, $message)
             $this->fail('No response set, cannot assert status code.');
         }
         $status = $this->_response->statusCode();
+
+        if ($this->_exception && ($status < $min || $status > $max)) {
+            throw $this->_exception;
```
Comment (markstory) [inline src/TestSuite/IntegrationTestCase.php]: Shouldn't you fail() instead of throw? Throwing will make the test as an 'error' which is not what actually happened.

Comment (dereuromark) [inline src/TestSuite/IntegrationTestCase.php]: What should the fail() contain? The stracktrace seems useful to me as well.

Comment (dereuromark) [inline src/TestSuite/IntegrationTestCase.php]: You were right, and fail() can process the exception just fine, minor different output:
```
1) App\Test\TestCase\Controller\AccountControllerTest::testRegister
exception 'RuntimeException' with message 'The "Passwordable" alias has already ...
```

Perfect!

**Comment by lorenzo** [comment]
Good job @dereuromark !
