### PR TITLE
Fix problem with chained find() calls and overlapping argument names.

### LINKED ISSUE #18716: Chained calls to Table::find are not independent
### Description

I stumbled across a bug while using chained calls to different finders on a table.

The original bug is caused by this code snippet from my code:

```php
$affectedReservations = $this->Reservations
    ->find('reservationsForThing', [$entity->id])
    ->find('byTimespan', active: true, future: true);
```

This produced the error "Named parameter $active overwrites previous argument". After investigating, I located the responsible lines in the `Table::invokeFinder` function.

My finders are defined like this:

```php
public function findReservationsForDevices(
    SelectQuery $query,
    array $deviceIds,
): SelectQuery {...}

public function findByTimespan(
    SelectQuery $query,
    bool $active = false,
    bool $future = false,
    bool $past = false,
): SelectQuery {...}
```

What happens inside the `Table::invokeFinder` function is, that the arguments given to the finder are added to the `$query` instance via `$query->applyOptions($args)` in line 2705. This means, that the first call of `->find('reservationsForDevices', [$entity->id])` attaches the array containing the entity ID as a normal parameter into the `$args` array. The query arguments now look like this in case the entity ID is 2:

```php
$args = [
    0 => [2],
]
```

The next call to the find function happens with named arguments: `->find('byTimespan', active: true, future: true)`. After attaching the new named arguments to the query in line 2705 and loading all arguments from the query in line 2707, the `$args` array looks like this:

```php
$args = [
    0 => [2],
    'active' => true,
    'future' => true,
]
```

However, this becomes a problem when invoking the actual finder in line 2728, since all `$args` are unwrapped and applied:

```php
return $callable($query, ...$args);
```

As far as I understand, when trying to invoke my finder at the end of the `invokeFinder` method, the first argument, which is still coming from the first call to `findReservationsForDevices`, is written as the first argument of the `byTimespan` finder. Then, the `active` argument is written, which will now override the `$active` argument which was previously set by the positional argument. Therefore, the named parameter `active` would override the positional argument `$active = [2]`.

Workaround/Solution: When I use a named parameter for the first finder as well, everything works as expected.

## Conclusion
Chained calls to finder methods are not independent of each other. This is also reflected in a related bug described further down. However, when using the query builder syntax with chained finders, I never would have expected that the two calls to `find` would be related to each other in the end, and can affect each other like this. I think this is counter-intuitive.

## Another related problem
A related problem that arises from this behavior is, that we can't have multiple chained finders that use the same names for their parameters, in case we are not defining all parameters.

Suppose I have two finders like this:

```php
public function findA(SelectQuery $query, array $a): SelectQuery {...}

public function findAb(SelectQuery $query, bool $a = true, bool $b = false): SelectQuery {...}
```

If I call them like this, everything works:

```php
// This is okay
$table->find('a', a: [])->find('ab', a: true, b: false);
```

But if I don't define `a` in the second call, this results in an error, because `a` was already defined as an array in the first call, and persists inside the $query object. However, the second finder doesn't re-declare `a` again, which is why the persisted value is given to the second finder instead. This results in a Type error, because the array given to the second finder is not acceptable as a bool type:

```php
// Type error, because [] is used for bool $a in the second finder
$table->find('a', a: [])->find('ab', b: false);
```

Again, this is counter-intuitive. Especially, when a default value is defined for `$a` and `$b` in the `findAb` function, I would expect the default value to be used. But in the case that I don't specifically define all parameters for the second finder, the previously set values from finders before that bleed into the latter finder instead.

### CakePHP Version

5.1.6

### PHP Version

8.3

### PR DESCRIPTION
**Pull request by ADmad**
Closes #18716

### CODE REVIEW

**Comment by ADmad** [comment]
In the next minor/major release we should also avoid setting options with numeric keys to `SelectQuery::applyOptions()`.

I haven't done that currently as it would break this test

https://github.com/cakephp/cakephp/blob/40b87426df022b440c84b1b8555a27c66be972e4/tests/TestCase/ORM/AssociationTest.php#L483-L486

File: tests/TestCase/ORM/TableTest.php [hunk 1]
```diff
@@ -1314,6 +1314,30 @@ public function testFindTypedParameters(): void
...
+    /**
+     * https://github.com/cakephp/cakephp/issues/18716
+     */
+    public function testChangedFindWithOverlappingArgs(): void
+    {
+        $query = $this->getTableLocator()->get('Authors')
+            ->find('withIdArgument', 2)
+            ->find('custom', id: [1, 2], second: false);
+
+        $this->assertSame([2, 'id' => [1, 2], 'second' => false], $query->getOptions());
```
Comment (othercorey) [inline tests/TestCase/ORM/TableTest.php:1326]: The pain of query options returns.

Comment (markstory) [reply tests/TestCase/ORM/TableTest.php:1326]: Should we be planning a replacement for 6.0?

Comment (ADmad) [reply tests/TestCase/ORM/TableTest.php:1326]: Yes, we should consider it.
