### PR TITLE
Fix limitControl() to preserve passed params in form action

### LINKED ISSUE #19229: PaginatorHelper - allow specify form action
### Description

In PaginatorHelper, the limit control uses 'url' => [].
This makes impossible to use in cases when the url contains passed params like users/details/517?param1=test

Image

### CakePHP Version

_No response_

### PR DESCRIPTION
**Pull request by dereuromark**
## Summary

- Fix regression from 87b366cb71 where `limitControl()` used `'url' => []` for the form action, stripping passed parameters (e.g. `/users/details/517` became `/users/details`)
- Use the request URI path directly as form action to preserve the full URL path including passed params

Fixes #19229

### CODE REVIEW

File: src/View/Helper/PaginatorHelper.php [hunk 1]
```diff
@@ -1215,7 +1215,7 @@ public function limitControl(array $limits = [], ?int $default = null, array $op
             $scope .= '.';
         }
 
-        $out = $this->Form->create(null, ['type' => 'get', 'url' => []]);
+        $out = $this->Form->create(null, ['type' => 'get', 'url' => $this->_View->getRequest()->getUri()->getPath()]);
```
Comment (ADmad) [inline src/View/Helper/PaginatorHelper.php]:
```suggestion
        $out = $this->Form->create(null, ['type' => 'get', 'url' => $this->_View->getRequest()->getPath()]);
```

**Review by ADmad — APPROVED** [review]
