### PR TITLE
Fix regression in Router::reverse() handling pass data

### LINKED ISSUE #16148: Router issue after changes in #16119
### Description

After changes comming from #16119 routeReverse stop working for url '/authors/1/articles/1' (still works for /authors/1/articles/10) 

In this usecase author_id is same as passed id for article and it is deleted.

The reverse route receive
```
(
    [author_id] => 1
    [pass] => Array
        (
            [0] => 1
        )

    [controller] => Articles
    [action] => view
    [_method] => GET
    [map] => Array
        (
        )

    [plugin] => 
    [_matchedRoute] => /authors/{author_id}/articles/{id}
)
```
Reverting the reverseToArray changes fixes issue.

### CakePHP Version

4.3.2

### PHP Version

_No response_

### PR DESCRIPTION
**Pull request by markstory**
When two route parameters have the same value and one is defined as a passed parameter, the pass array had the too many values removed.

Fixes #16148

### CODE REVIEW

**Comment by othercorey** [comment]
@ADmad Think you're able to review this better than I am.

File: src/Routing/Router.php [hunk 1]
```diff
@@ -650,18 +650,29 @@ public static function reverseToArray($params): array
...
+            // so we can access the pass parameter configuration.
+            foreach (static::getRouteCollection()->routes() as $maybe) {
+                if ($maybe->template === $template) {
+                    $route = $maybe;
+                    break;
+                }
             }
         }
-        $params = array_merge($params, array_values($pass));
+        if ($route) {
```
Comment (ADmad) [inline src/Routing/Router.php:670]: Should there be an exception instead when no route matching the template is found? Trying to reverse an array which has a template which doesn't match any existing routes doesn't seem very useful.

Comment (markstory) [reply src/Routing/Router.php:670]: I was concerned about breaking an application that removed the `_matchingRoute` key. If the route truly doesn't match Router will raise an error when no URL could be generated for the parameters.

Comment (ADmad) [reply src/Routing/Router.php:670]: True, the returned array would be "unusable", so I guess this is fine.

File: src/Routing/Router.php [hunk 2]
```diff
@@ -650,18 +650,29 @@ public static function reverseToArray($params): array
...
+            // If we found a route, slice off the number of passed args.
+            $routePass = $route->options['pass'] ?? [];
+            $pass = array_slice($pass, count($routePass));
```
Comment (ADmad) [inline src/Routing/Router.php:673]: So essentially only the value matching `*` (or `**`) should remain in `$pass` isn't it?

File: src/Routing/Router.php [hunk 3]
```diff
@@ -650,18 +650,29 @@ public static function reverseToArray($params): array
         }
         $pass = $params['pass'] ?? [];
 
+        $template = $params['_matchedRoute'] ?? null;
```
Comment (ADmad) [inline src/Routing/Router.php:653]: In the past I have wondered if storing the full route instance instead of just the template would be useful. It would have been for this case :). Perhaps something to consider for 5.0.

File: src/Routing/Router.php (hunk 2 above)
Comment (markstory) [reply src/Routing/Router.php:673]: Yep! Or other route keys that weren't flagged as `pass`.

File: src/Routing/Router.php (hunk 3 above)
Comment (markstory) [reply src/Routing/Router.php:653]: Having the full route in the request (perhaps as an attribute) would be a nice improvement.
