### PR TITLE
don't update private variable unless repo exists.

### LINKED ISSUE #9008: ExistsIn validation is not atomic (with example code)
This is a (multiple allowed):
* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.2.10
* Platform and Target: Apache2, PHP7, Windows

### What you did

Created a table object that uses the `existsIn` rule validation.

```
    class Document extends Table {
       ///.....
       public function buildRules(RulesChecker $rules)
       {
           $rules->add($rules->existsIn(['foo_id'], 'Foo'));
         }
    }
```

In the above example, the table `Foo` does not exist.

### Expected Behavior

When trying to save a record the `ExistsIn` rule will throw the following error message.

```
ExistsIn rule for 'Document' is invalid. The 'Foo' association is not defined.
```

Here is my edge case where I attempt to save data using a `finally` to have the save always performed.

```
      $Document = TableRegistry::get('Document')
      $entity = $Document->get(0);
      try {
            // bla bla bla
           $Document->save($entity);
            // bla bla bla
      } finally {
           $Document->save($entity);
      }
```

Expected behavior would be that both save attempts throw the `RuntimeException` above, but this is not the case. The second time `$Document->save()` is called the `ExistsIn` will trigger a `null` reference error.

### Actual Behavior

When `__invoke` is called it attempts to lookup the repository, but only if it's a string.

```
    public function __invoke(EntityInterface $entity, array $options)
    {
        if (is_string($this->_repository)) {
            $alias = $this->_repository;
            $this->_repository = $options['repository']->association($alias);

            if (empty($this->_repository)) {
                throw new RuntimeException(sprintf(
                    "ExistsIn rule for '%s' is invalid. The '%s' association is not defined.",
                    implode(', ', $this->_fields),
                    $alias
                ));
            }
        }
```

If the repo is not found it throws an error, but the `$this->_repository` will no longer be a string value. Any future calls to `__invoke` have the class in an unexpected state.

I think the expected behavior would be  continued throwing of the same exception.

### PR DESCRIPTION
**Pull request by thinkingmedia**
closes #9008

### CODE REVIEW

File: src/ORM/Rule/ExistsIn.php [hunk 1]
```diff
@@ -64,16 +64,15 @@ public function __construct($fields, $repository)
     public function __invoke(EntityInterface $entity, array $options)
     {
         if (is_string($this->_repository)) {
-            $alias = $this->_repository;
-            $this->_repository = $options['repository']->association($alias);
-
-            if (empty($this->_repository)) {
+            $repository = $options['repository']->association($this->_repository);
+            if (empty($repository)) {
```
Comment (dereuromark) [inline src/ORM/Rule/ExistsIn.php]: if (!$...)
