### PR TITLE
Fix up data provider usage tests.

### LINKED ISSUE #18673: 5.x: `XmlView::_serialize()` and its test
### Description

Is this test correct?
https://github.com/cakephp/cakephp/blob/69cfd876242f8a0b33bf81fad1ed96d909f0dfe9/tests/TestCase/View/XmlViewTest.php#L294

It looks like the arguments are not actually passed.

And the test fails, because it seems to me that `XmlView::_serialize()` with `['']` produces a different result, while it fails with `[[]]`.

I don't want to be wrong and misunderstand the test code.

### CakePHP Version

5.2

### PHP Version

_No response_

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/18673 in a way that it actually tests the values.

The `[]` (empty array) case I dont know how to handle, it throws an actual error.
In the process I improved the exception message from

> Cake\Utility\Exception\XmlException: Invalid input.

to

> Cake\Utility\Exception\XmlException: Invalid input of type `array` (Count of 0).

### CODE REVIEW

File: tests/TestCase/View/XmlViewTest.php [hunk 1]
```diff
@@ -307,7 +306,8 @@ public function testRenderSerializeWithFalseyValue(): void
 
         $expected = Xml::build(['response' => $data])->asXML();
         $this->assertSame($expected, $result);
-        $this->assertStringContainsString('<testing>0</testing>', $result);
+        $expectedString = $expectedValue === null ? '<testing/>' : '<testing>' . $expectedValue . '</testing>';
```
Comment (mirko-pagliai) [inline tests/TestCase/View/XmlViewTest.php]: Why can't `$expectedValue` have the value of `$expectedString` directly?
The values ​​of the first 3 cases would be the same, but it would all become much more readable and without the need for additional steps.

Comment (mirko-pagliai) [reply tests/TestCase/View/XmlViewTest.php]:
```php
#[TestWith([0, '<testing>0</testing>'])]
#[TestWith(['0', '<testing>0</testing>'])]
#[TestWith([false, '<testing>0</testing>'])]
#[TestWith(['', '<testing/>'])]
```

**Comment by dereuromark** [comment]
@markstory 
What about your commit https://github.com/cakephp/cakephp/commit/354e6808826489ae362fdfce6a1ad3ab39b2cfb2 that now was removed again?
What should the empty array translate to in your opinion?
