### PR TITLE
Fix up URL comparison.

### LINKED ISSUE #684: AuthenticationService::getUnauthenticatedRedirectUrl() Returns Relative URLs Without Full Base
### Description

Why does `Authentication\AuthenticationService::getUnauthenticatedRedirectUrl()` returns URLs without full base?

https://github.com/cakephp/authentication/blob/6b6a2efb7f8b5f6e1c0d53f3fe79c690f29a0aa2/src/AuthenticationService.php#L398

Image

This makes asserting redirects because of unauthenticated access a PITA.

` $this->assertRedirect('/login?redirect=' . urlencode($redirect));`

Leads to the following test error because of this:

> Failed asserting that 'http://localhost/coupon-portal/login?redirect=%2Fcampaigns%2Fposition' equals content in header 'Location' (/coupon-portal/login?redirect=%2Fcampaigns%2Fposition).

Because `Cake\TestSuite\IntegrationTestTrait::assertRedirect()` always tests against full based URLs:

https://github.com/cakephp/cakephp/blame/33626a03197758f30a8ce8c2e0a75ed8ddbce40a/src/TestSuite/IntegrationTestTrait.php#L929

Wouldn't full based URL redirects be more sensible (& secure) to begin with?

### CakePHP Version

4.x & (probably) 5.x

### PHP Version

irrelevant

### PR DESCRIPTION
**Pull request by dereuromark**
Fixes https://github.com/cakephp/authentication/issues/684
This should be BC as it would convert if needed and now always compares absolute URLs.

### CODE REVIEW

**Comment by krugerman007** [comment]
Thanks @dereuromark! It works. We are waiting for the next release ;)

File: src/TestSuite/IntegrationTestTrait.php [hunk 1]
```diff
@@ -1506,6 +1526,24 @@ protected function extractExceptionMessage(Exception $exception): string
...
+     *
+     * If the URL is already absolute, it is returned as-is.
+     * If the URL is relative, it is converted to an absolute URL using Router::url().
+     *
+     * @param string $url The URL to normalize
+     * @return string The normalized absolute URL
+     */
+    protected function normalizeRedirectUrl(string $url): string
+    {
+        if (preg_match('#^https?://#', $url)) {
```
Comment (ADmad) [inline src/TestSuite/IntegrationTestTrait.php]: This isn't necessary, `Router::url()` already handles URLs with protocols.
