### PR TITLE
Fix routes check not handling invalid input

### LINKED ISSUE #14438: CakePHP 4.0.5 bin/cake routes check results in exception
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.5
* Platform and Target: Ubuntu 18 LTS

### What you did

Ran `bin/cake routes check`

### What happened

```
chris@chris-x1 /v/w/p/cake4_employees> bin/cake routes check
Exception: strlen() expects parameter 1 to be string, null given
In [/var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Http/ServerRequest.php, line 255]

2020-04-11 22:41:42 Error: [TypeError] strlen() expects parameter 1 to be string, null given in /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Http/ServerRequest.php on line 255
Stack Trace:
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Http/ServerRequest.php:255
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Http/ServerRequest.php:244
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Command/RoutesCheckCommand.php:50
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Console/BaseCommand.php:175
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Console/CommandRunner.php:336
- /var/www/personal/cake4_employees/vendor/cakephp/cakephp/src/Console/CommandRunner.php:171
- /var/www/personal/cake4_employees/bin/cake.php:12

```

### What you expected to happen

Not encounter an exception. I tested this in two separate cake 4 applications and both encountered this exception.

### PR DESCRIPTION
**Pull request by markstory**
Make the positional argument required so we don't get errors downstream.

Fixes #14438

### CODE REVIEW

**Comment by othercorey** [comment]
Should we back port to 3.x?

File: tests/TestCase/Command/RoutesCommandTest.php [hunk 1]
```diff
@@ -108,6 +108,19 @@ public function testCheckHelp()
         $this->assertErrorEmpty();
     }
 
+
```
Comment (ADmad) [inline tests/TestCase/Command/RoutesCommandTest.php:111]:
```suggestion
```

**Comment by ADmad** [comment]
> Should we back port to 3.x?

Same issue probably doesn't exist in `RoutesShell` (it doesn't have this command class).
