### PR TITLE
Fix #17604 problem formatting milliseconds using i18nFormat in 5.x

### LINKED ISSUE #17604: Problem formatting milliseconds using i18nFormat
### Description

I am facing similar problem to https://github.com/cakephp/cakephp/issues/10439 when formatting using the function `i18nFormat`

This line https://github.com/cakephp/cakephp/blob/1daf3c0854c139bac85d3535505cef6154f9d164/src/I18n/DateFormatTrait.php#L104 could be changed to `return (string)static::$formatters[$key]->format($date->format('U.u'));` to allow microseconds when formatting. This should not be a breaking change, since the date us already formatted again within the same line, but I am not sure if this could cause any new problem. 

This is a quick test:

```
$time = new FrozenTime('2014-07-06T13:09:01.523000+00:00');
$this->assertEquals('2014-07-06 13:09:01.523000', $time->format('Y-m-d H:i:s.u'));
$i18nFormat = $time->i18nFormat("yyyy-MM-dd'T'HH':'mm':'ss.SSSxxx", null, 'en-US');
$this->assertEquals('2014-07-06T13:09:01.523+00:00', $i18nFormat); // this will fail returning 2014-07-06T13:09:01.000+00:00
```

This is hapening in many different cakephp versions including 4.x and 5.x and it is independent from php version used

### CakePHP Version

4.4.0

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by freefri**
Fixes https://github.com/cakephp/cakephp/issues/17604 in branch 5.x relates to https://github.com/cakephp/cakephp/pull/17605

### CODE REVIEW

File: tests/TestCase/I18n/DateTimeTest.php [hunk 1]
```diff
@@ -412,6 +412,12 @@ public function testI18nFormat(): void
         $result = $time->i18nFormat(IntlDateFormatter::FULL, 'Asia/Tokyo', 'ja-JP@calendar=japanese');
         $expected = '平成22年1月14日木曜日 22時59分28秒 日本標準時';
         $this->assertTimeFormat($expected, $result);
+
+        // Test with milliseconds
+        $timeMillis = new FrozenTime('2014-07-06T13:09:01.523000+00:00');
```
Comment (ADmad) [inline tests/TestCase/I18n/DateTimeTest.php]:
```suggestion
        $timeMillis = new DateTime('2014-07-06T13:09:01.523000+00:00');
```

5.x doesn't have `FrozenTime`, `DateTime` is the immutable class.

File: src/I18n/DateFormatTrait.php [hunk 2]
```diff
@@ -101,7 +101,7 @@ protected function _formatObject(
             static::$formatters[$key] = $formatter;
         }
 
-        return (string)static::$formatters[$key]->format($date->format('U'));
+        return (string)static::$formatters[$key]->format($date->format('U.u'));
```
Comment (ADmad) [inline src/I18n/DateFormatTrait.php]: `IntlDateFormatter::format()` also accepts `DateTimeInterface` instances which `$date` already is. So I wonder why is it not directly used instead of converting to string.

Comment (ADmad) [inline src/I18n/DateFormatTrait.php]:
```suggestion
        return (string)static::$formatters[$key]->format($date);
```
I ran the tests locally and directly using the `$date` instance works fine.

Comment (freefri) [reply src/I18n/DateFormatTrait.php]: I did not think about it, but your solution is in my opinion better

Comment (othercorey) [reply src/I18n/DateFormatTrait.php]: I noticed this before as well. I must not have changed it after the Chronos 3 upgrade.

**Comment by dereuromark** [comment]
Looks like we should also address https://github.com/cakephp/cakephp/issues/17601 here
