### PR TITLE
2.7 session concurrency

### LINKED ISSUE #2808: DatabaseSession Integrity Constraint Violation
I am currently debugging a session issue where a PDOException is throw saying that there already exists a primary key with `<SESSION_ID>`. It appears to only happen during ajax requests.

Before `Model->save()`, `findById($sessionId)` returns false. After the exception is thrown, `findById(..)` returns true.

```
SQLSTATE[23000]: Integrity constraint violation: 1062 
Duplicate entry 'c760db8417dd5b9ec81d9dc3d99b743572c28a3c0d3ad2ed27b8b9ddc3e0531f' 
for key 'PRIMARY' in file
/var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php on line 458.

Stack trace:

#0 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(458): PDOStatement->execute(Array)
#1 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(424): DboSource->_execute('INSERT INTO `pe...', Array)
#2 /var/www/cakephp/repo/lib/Cake/Model/Datasource/DboSource.php(1004): DboSource->execute('INSERT INTO `pe...')
#3 /var/www/cakephp/repo/lib/Cake/Model/Model.php(1832): DboSource->create(Object(Session), Array, Array)
#4 /var/www/html/app/Model/Session.php(line: 23): Model->save(Array, true, Array)
#5 /var/www/cakephp/repo/lib/Cake/Model/Datasource/Session/DatabaseSession.php(117): Session->save(Array)
#6 [internal function]: DatabaseSession->write('c760db8417dd5b9...', '????Config??use...')
#7 [internal function]: session_write_close()
#8 {main}
```

Any suggestion to as why this is happening? Session locking? DB locking?

### PR DESCRIPTION
**Pull request by AD7six**
This starts with a failing test, fixes the test and then adjusts the options to reduce the code execution time.

We _could_ rework the write method to be of the form:

```
$db = x
$db->update($this->_model, ...) || $db->create($this->_model, ...)
```

But that's maybe not really necessary (or rather, not worth the maintenance of effectively re-implementing the model save method)

Fixes #2808

### CODE REVIEW

File: lib/Cake/Model/Datasource/Session/DatabaseSession.php [hunk 1]
```diff
@@ -114,7 +114,17 @@ public function write($id, $data) {
...
+
+		$options = array(
+			'validate' => false,
+			'callbacks' => false,
+			'counterCache' => false
+		);
+		try {
+			return $this->_model->save($record, $options);
+		} catch (Exception $e) {
+			return $this->_model->save($record, $options);
```
Comment (markstory) [inline lib/Cake/Model/Datasource/Session/DatabaseSession.php]: What happens if it fails again?

**Comment by markstory** [comment]
Other than my one question this looks like an improvement. Disabling code we don't need will help shorten the race window.

File: lib/Cake/Model/Datasource/Session/DatabaseSession.php (hunk 1 above)
Comment (AD7six) [inline lib/Cake/Model/Datasource/Session/DatabaseSession.php]: If it fails again, it's because of a none-transient problem and that'll bubble up (rightly so IMO).

I see I left it catching all exceptions, I'll update that to PDOException since that's the only scenario that this code is expecting to encounter.

**Comment by markstory** [comment]
Should this also be backported to master? It is probably also an issue in 2.6.x

**Comment by AD7six** [comment]
@markstory the problem certainly exists in master - does the different save calls have any BC concerns? If not, I'd say yes it should be.

**Comment by markstory** [comment]
I don't think the BC concern out weighs the issue around concurrency problems.
