### PR TITLE
Fix Model.afterSaveCommit triggering inconsistency.

### LINKED ISSUE #16499: Non-consistent afterSaveCommit dispatch in saveMany in Table.php
### Description

When executing a save on a table, Model.afterSaveCommit is dispatched if the transaction is committed. However, this method is also used for saveMany (and saveManyOrFail), so in a different context. Then, the save method does not dispatch Model.afterSaveCommit as the transaction is not yet committed. Now, the save method cleans the entity and sets new to false. After all calls to save from saveMany Model.afterSaveCommit is dispatched with cleaned entities, hence, the information for dirty fields and original values is lost and is not passed to Model.afterSaveCommit. 

In cakephp/src/ORM/Table.php
```php

protected function _saveMany(iterable $entities, $options = []): iterable
    {
        ...

        try {
            $this->getConnection()
                ->transactional(function () use ($entities, $options, &$isNew, &$failed) {
                    foreach ($entities as $key => $entity) {
                        $isNew[$key] = $entity->isNew();
                        // normal save called here, so each entity is cleaned here
                        if ($this->save($entity, $options) === false) {
                            $failed = $entity;

                            return false;
                        }
                    }
                });
        } catch (Exception $e) {
            $cleanup($entities);

            throw $e;
        }

       ...

        if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
            foreach ($entities as $entity) {
                // Cleaned entities are passed with the dispatch, missing dirty and original fields
                $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
            }
        }

        return $entities;
    }

public function save(EntityInterface $entity, $options = [])
    {
        ...

        if ($success) {
            // transaction is committed for single save, but not for saveMany operation
            if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
                $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
            }
            // For saveMany the entity is cleaned here, but the dispatch above was not executed.
            // Hence, all fields unset by clean are lost (dirty, original, etc.)
            if ($options['atomic'] || $options['_primary']) {
                $entity->clean();
                $entity->setNew(false);
                $entity->setSource($this->getRegistryAlias());
            }
        }

        return $success;
    }
```

What I expected is that a saveMany dispatches the model.afterSaveCommit with the dirty and original values. So, I propose to execute the clean operation for entities saved via saveMany only after the dispatchEvent in the _saveMany method. 

Let me know if you agree with my logic, then I will make an MR!

### CakePHP Version

4.3.9

### PHP Version

8.1.5

### PR DESCRIPTION
**Pull request by ADmad**
When using Table::saveMany() the entities are now cleaned up after
Model.afterSaveCommit event is dispatched, similar to what's done
when saving individual entities with Table::save().

Closes #16499

### CODE REVIEW

File: src/ORM/Table.php [hunk 1]
```diff
@@ -2249,20 +2253,34 @@ protected function _saveMany(iterable $entities, $options = []): iterable
...
         }
 
         if ($failed !== null) {
-            $cleanup($entities);
+            $cleanupOnFailure($entities);
 
             throw new PersistenceFailedException($failed, ['saveMany']);
         }
 
+        $cleanupOnSuccess = function (EntityInterface $entity) {
```
Comment (markstory) [inline src/ORM/Table.php]:
```suggestion
        $cleanupOnSuccess = function (EntityInterface $entity) use ($cleanupOnSuccess) {
```

Think you need this to fix the lint errors.

File: src/ORM/Table.php [hunk 2]
```diff
@@ -2249,20 +2253,34 @@ protected function _saveMany(iterable $entities, $options = []): iterable
...
+            $entity->clean();
+            $entity->setNew(false);
+
+            foreach ($entity->toArray() as $value) {
```
Comment (markstory) [inline src/ORM/Table.php]: Why do we need to iterate the properties of each entity?

File: src/ORM/Table.php (hunk 1 above)
Comment (ADmad) [reply src/ORM/Table.php]: Didn't help, I shut up the static analyzers instead.

File: src/ORM/Table.php (hunk 2 above)
Comment (ADmad) [reply src/ORM/Table.php]: Because any associated records also need to be cleaned up.

File: src/ORM/Table.php (hunk 1 above)
Comment (othercorey) [reply src/ORM/Table.php]: I do this with `use (&$cleanupOnSuccess)`

File: src/ORM/Table.php (hunk 2 above)
Comment (ADmad) [reply src/ORM/Table.php]: I have actually failed to take care of hasMany associated records, fixing it soon.

File: src/ORM/Table.php (hunk 1 above)
Comment (ADmad) [reply src/ORM/Table.php]: Yup, I was missing the `&`.

File: src/ORM/Table.php (hunk 2 above)
Comment (ADmad) [reply src/ORM/Table.php]: Done

File: src/ORM/Table.php [hunk 3]
```diff
@@ -2249,20 +2253,40 @@ protected function _saveMany(iterable $entities, $options = []): iterable
...
+                $value = $entity->get($field);
+
+                if ($value instanceof EntityInterface) {
+                    $cleanupOnSuccess($value);
+                } elseif (is_array($value) && current($value) instanceof EntityInterface) {
+                    foreach ($value as $associated) {
+                        $cleanupOnSuccess($associated);
+                    }
+                }
+            }
```
Comment (markstory) [inline src/ORM/Table.php:2281]: Were nested associations not being marked as clean before?

Comment (ADmad) [reply src/ORM/Table.php:2281]: They were but as per the issue users don't want the entities to be cleaned before the Model.afterSaveCommit is triggered. Hence I added a new option to prevent `save()` from doing so when called through `saveMany()`. So now after the event is fired we need to iterate though all the entities and clean them.

**Comment by othercorey** [comment]
Should we include a migration note?
