### PR TITLE
Add Connection::afterCommit() to fix suppressed afterSaveCommit/afterDeleteCommit in outer transactions

### LINKED ISSUE #19382: afterSaveCommit / afterDeleteCommit permanently suppressed inside Connection::transactional()
## Summary

When `Table::save()` or `Table::delete()` is called inside an application-level `Connection::transactional()` block, `afterSaveCommit` and `afterDeleteCommit` events are permanently suppressed. The events are correctly held during the transaction, but are never deferred and re-dispatched when the outermost transaction commits.

```php
$connection->transactional(function () {
    $this->OrdersTable->saveOrFail($order);          // afterSaveCommit suppressed
    $this->PaymentsTable->saveOrFail($payment);       // afterSaveCommit suppressed
});
// Transaction committed — but afterSaveCommit events are permanently lost
```

This pattern is common when multiple tables need to be saved atomically (cross-table transactions).

## Root Cause

The gate is `Table::_transactionCommitted()`:

```php
protected function _transactionCommitted(bool $atomic, bool $primary): bool
{
    return !$this->getConnection()->inTransaction() && ($atomic || $primary);
}
```

When an outer transaction is active, `inTransaction()` returns `true`, the method returns `false`, and `dispatchEvent()` is never called. There is no mechanism to defer the event for later dispatch.

CakePHP's own `saveManyOrFail()` solves this internally — `_saveMany()` collects entities and dispatches `afterSaveCommit` for each one after its transaction commits (Table.php lines 2392-2398). This proves the intent is for these events to fire after commit. The gap is that application-level `transactional()` blocks have no access to an equivalent mechanism.

## Failing Tests

Branch [`feature/connection-on-commit`](https://github.com/cakephp/cakephp/compare/5.x...feature/connection-on-commit) contains four tests demonstrating the issue:

| Test | Result | What it shows |
|------|--------|---------------|
| `testAfterSaveCommitFiringAfterOuterTransactionCommits` | **FAIL** | Single save inside `transactional()` — event lost after commit |
| `testAfterSaveCommitForCrossTableTransactional` | **FAIL** | Cross-table saves — both events lost |
| `testAfterDeleteCommitFiringAfterOuterTransactionCommits` | **FAIL** | Delete inside `transactional()` — event lost |
| `testAfterSaveCommitNotFiredOnRollback` | **PASS** | Control: events correctly discarded on rollback |

## Proposed Solution: `Connection::onCommit()` + deferred dispatch

A general-purpose post-commit callback mechanism on `Connection`, used by `Table` to defer suppressed events.

### Connection changes (~20 lines)

```php
protected array $afterCommitCallbacks = [];

public function onCommit(Closure $callback): void
{
    if (!$this->inTransaction()) {
        $callback();
        return;
    }
    $this->afterCommitCallbacks[] = $callback;
}
```

In `commit()`, after outermost commit succeeds, flush callbacks. In `rollback()`, discard them when outermost rolls back.

### Table changes (~10 lines)

At each dispatch point gated by `_transactionCommitted()`, add deferral:

```php
if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
    $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
} elseif ($this->getConnection()->inTransaction()) {
    $this->getConnection()->onCommit(
        fn() => $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'))
    );
}
```

Applies to 5 dispatch points: `save()`, `delete()`, `findOrCreate()`, `_saveMany()`, `deleteMany()`.

### Industry precedent

This is a well-established pattern:
- **Django**: [`transaction.on_commit()`](https://docs.djangoproject.com/en/5.0/topics/db/transactions/#django.db.transaction.on_commit)
- **Laravel**: [`DB::afterCommit()`](https://laravel.com/docs/11.x/database#database-transactions)
- **Doctrine**: Transaction lifecycle callbacks

## Design Decisions for Discussion

1. **Callback exceptions** — The transaction is already committed when callbacks flush. Should exceptions propagate? Should remaining callbacks still execute (collect-and-throw)?

2. **Savepoint rollback semantics** — When a nested savepoint rolls back, should callbacks registered after that savepoint be discarded? Django's `on_commit()` takes the simpler approach: callbacks always run after outermost commit regardless of intermediate savepoint rollbacks.

3. **Reentrancy** — What if a callback calls `transactional()` again? The flush loop should drain the queue safely even if new callbacks are added during flushing.

4. **`_saveMany()` / `deleteMany()` deferred loops** — These existing loops become redundant once individual `save()`/`delete()` handle deferral. They could be removed to avoid double dispatch, but this should be verified with targeted equivalence tests.

5. **`ConnectionInterface`** — Should `onCommit()` be added to the interface?

## CakePHP Version

5.x (tested against 5.3.1)

### PR DESCRIPTION
**Pull request by jamisonbryant**
## Summary

Adds `Connection::afterCommit()` for registering callbacks that execute after the outermost transaction commits. Uses this to fix suppressed `afterSaveCommit` and `afterDeleteCommit` events when `save()`/`delete()` is called inside an application-level `Connection::transactional()` block.

Fixes #19382.

## Major Changes

- **`Connection::afterCommit(Closure)`** -- new public method that queues a callback to run after the outermost transaction commits. If no transaction is active, the callback executes immediately. Callbacks are discarded on rollback.
- **`Connection::commit()`** -- after `commitTransaction()` succeeds, flushes all queued callbacks in registration order. All callbacks execute even if one throws; the first exception is re-thrown after.
- **`Connection::rollback()`** -- clears queued callbacks when rolling back to the beginning (outermost level or `$toBeginning = true`). Callbacks survive savepoint-only rollbacks.
- **`Table::save()`, `Table::delete()`, `Table::findOrCreate()`** -- when `_transactionCommitted()` returns false but the connection is still in a transaction, the commit event is deferred via `afterCommit()` instead of being silently dropped.
- **`Table::_saveMany()`** -- removed `afterSaveCommit` dispatch from the batch loop since individual `save()` calls now handle their own deferral, preventing double dispatch.
- **`Table::_deleteMany()`** -- retained the batch dispatch loop (since it calls `_processDelete()` directly, not the public `delete()`) but added `afterCommit()` deferral for the outer-transaction case.

## Minor Changes

- Fixed `\RuntimeException` FQN references in `TableTest` to use the existing `use` import
- Fixed CakePHP CS violations: `fn ()` to `fn()`, added trailing commas in multi-line calls
- Added PHPStan baseline ignore for `afterCommit()` in ORM split package (removable after next `cakephp/database` release)

## Work Remaining

- [x] Update Table docblock (line 130-131) to reflect new deferred behavior
- [ ] Consider adding `afterCommit()` to `ConnectionInterface` in a follow-up
- [x] Update Cake docs - see https://github.com/cakephp/docs/pull/8281

## Test Plan

- [x] `vendor/bin/phpunit tests/TestCase/Database/ConnectionTest.php` -- 63 tests pass (7 new), 1 skipped (savepoint test on drivers without support)
- [x] `vendor/bin/phpunit tests/TestCase/ORM/TableTest.php` -- 273 tests pass (8 new)
- [x] `vendor/bin/phpcs src/Database/Connection.php src/ORM/Table.php tests/TestCase/Database/ConnectionTest.php tests/TestCase/ORM/TableTest.php` -- no violations
- [x] New Connection tests cover: fire after commit, discard on rollback, immediate outside transaction, ordering, nested rollback to beginning, savepoint survival, exception safety
- [x] New Table tests cover: afterSaveCommit deferral in outer transaction, cross-table transactional, afterDeleteCommit deferral, rollback suppression, saveMany double-dispatch prevention (standalone + wrapped), deleteMany dispatch (standalone + wrapped)

### CODE REVIEW

**Comment by LordSimal** [comment]
I'd say lets add those changes from the connected issue and lets see what other tests may fail due to this change or not.

I can confirm, that these events are not dispatched when we are already inside a transaction. This also means, that its not "saved" somewhere else to re-dispatch them when the transaction is done (which the code in your issue adds)

**Comment by jamisonbryant** [comment]
> I'd say lets add those changes from the connected issue and lets see what other tests may fail due to this change or not.

Believe it or not, no existing tests needed to be modified to pass with the new code. Only new ones added.

File: src/ORM/Table.php [hunk 1]
```diff
@@ -1651,6 +1651,10 @@ public function findOrCreate(
 
         if ($entity && $this->_transactionCommitted($options['atomic'], true)) {
             $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
+        } elseif ($entity && $this->getConnection()->inTransaction()) {
+            $this->getConnection()->afterCommit(
+                fn() => $this->dispatchEvent('Model.afterSaveCommit', ['entity' => $entity, 'options' => $options]),
```
Comment (jamisonbryant) [inline src/ORM/Table.php]: didn't use `compact()` because it's in an arrow function and wouldn't work here. I can update the other spots to use explicit arrays instead of compact as well, if desired.

We do not allow its use at $MYJOB because it's "magic".

File: tests/TestCase/ORM/TableTest.php [hunk 2]
```diff
@@ -2478,6 +2478,216 @@ public function testAfterSaveCommitWithTransactionRunning(): void
...
+    /**
+     * Asserts afterSaveCommit is deferred and fires after the outer transaction commits.
+     *
+     * Currently, afterSaveCommit is permanently suppressed when save() is called inside
+     * Connection::transactional(). The event never fires — not during the save (correct,
+     * since the transaction is still open) and not after the outer commit (the bug).
+     *
+     * This test documents the expected behavior: the event should fire after commit.
+     */
+    public function testAfterSaveCommitFiringAfterOuterTransactionCommits(): void
```
Comment (jamisonbryant) [inline tests/TestCase/ORM/TableTest.php:2505]: Asserts `afterSaveCommit` is deferred and fires after the outer transaction commits. Previously, `afterSaveCommit` was permanently suppressed when `save()` was called inside `Connection::transactional()`. The event never fired -- not during the save (correct, since the transaction is still open) and not after the outer commit (the bug).

File: tests/TestCase/ORM/TableTest.php [hunk 3]
```diff
@@ -2478,6 +2478,216 @@ public function testAfterSaveCommitWithTransactionRunning(): void
...
+    }
+
+    /**
+     * Asserts afterSaveCommit fires for each table when multiple tables are saved
+     * inside a single Connection::transactional() block.
+     *
+     * This is the cross-table atomicity pattern: wrapping saves to multiple tables
+     * in one transaction. Currently, all afterSaveCommit events are permanently lost.
+     */
+    public function testAfterSaveCommitForCrossTableTransactional(): void
```
Comment (jamisonbryant) [inline tests/TestCase/ORM/TableTest.php:2537]: Asserts afterSaveCommit fires for each table when multiple tables are saved inside a single `Connection::transactional()` block.

This is the cross-table atomicity pattern: wrapping saves to multiple tables in one transaction. Currently, all afterSaveCommit events are permanently lost.

File: tests/TestCase/ORM/TableTest.php [hunk 4]
```diff
@@ -2478,6 +2478,216 @@ public function testAfterSaveCommitWithTransactionRunning(): void
...
+        $this->assertTrue($articleEventFired, 'afterSaveCommit should fire for articles table after outer commit');
+    }
+
+    /**
+     * Asserts afterDeleteCommit fires after an outer transaction commits.
+     *
+     * Same suppression problem as afterSaveCommit: when delete() is called inside
+     * Connection::transactional(), afterDeleteCommit is permanently lost.
+     */
+    public function testAfterDeleteCommitFiringAfterOuterTransactionCommits(): void
```
Comment (jamisonbryant) [inline tests/TestCase/ORM/TableTest.php:2572]: Asserts afterDeleteCommit fires after an outer transaction commits.

Same suppression problem as afterSaveCommit: when `delete()` is called inside `Connection::transactional()`, afterDeleteCommit is permanently lost.

File: tests/TestCase/ORM/TableTest.php [hunk 5]
```diff
@@ -2478,6 +2478,216 @@ public function testAfterSaveCommitWithTransactionRunning(): void
...
+            $table->deleteOrFail($user);
+        });
+
+        $this->assertTrue($called, 'afterDeleteCommit should fire after the outer transaction commits');
+    }
+
+    /**
+     * Asserts afterSaveCommit events are discarded when the outer transaction rolls back.
+     */
+    public function testAfterSaveCommitNotFiredOnRollback(): void
```
Comment (jamisonbryant) [inline tests/TestCase/ORM/TableTest.php:2591]: Asserts afterSaveCommit events are discarded when the outer transaction rolls back.

**Review by jamisonbryant — COMMENTED** [review]
I've now gone over all the AI-generated code and made it fix stuff to bring the overall branch more in-line with Cake standards and good coding practices.

File: src/Database/Connection.php [hunk 6]
```diff
@@ -494,7 +521,23 @@ public function commit(): bool
...
-            return $this->getWriteDriver()->commitTransaction();
+            $result = $this->getWriteDriver()->commitTransaction();
+
+            $callbacks = $this->afterCommitCallbacks;
+            $this->afterCommitCallbacks = [];
+            $firstException = null;
+            foreach ($callbacks as $cb) {
+                try {
+                    $cb();
+                } catch (Throwable $e) {
```
Comment (ADmad) [inline src/Database/Connection.php]: Should we be continuing to the next callback if there's an exception? Normally if you have multiple listeners for an event and if a handler generates and exception rest of the event handlers won't be executed.

File: src/Database/Connection.php [hunk 7]
```diff
@@ -494,7 +521,23 @@ public function commit(): bool
             $this->_transactionStarted = false;
             $this->nestedTransactionRollbackException = null;
 
-            return $this->getWriteDriver()->commitTransaction();
+            $result = $this->getWriteDriver()->commitTransaction();
+
+            $callbacks = $this->afterCommitCallbacks;
+            $this->afterCommitCallbacks = [];
+            $firstException = null;
+            foreach ($callbacks as $cb) {
```
Comment (ADmad) [inline src/Database/Connection.php:528]: Why not directly loop `$this->afterCommitCallbacks` and reset it afterwards?

File: src/ORM/phpstan.neon.dist [hunk 8]
```diff
@@ -21,3 +21,9 @@ parameters:
 			identifier: function.impossibleType
 			count: 1
 			path: EagerLoader.php
+
+		-
+			message: '#^Call to an undefined method Cake\\Database\\Connection::afterCommit\(\)\.$#'
```
Comment (ADmad) [inline src/ORM/phpstan.neon.dist:26]: This not required. The error for the split packages static analysis will go away after this is merged and the 5.next branch of split packages is updated.

File: src/ORM/Table.php [hunk 9]
```diff
@@ -2389,9 +2403,9 @@ protected function _saveMany(
             }
         };
 
+        // afterSaveCommit is dispatched by individual save() calls via afterCommit()
```
Comment (ADmad) [inline src/ORM/Table.php:2435]: But after this change the entity state will not be same. Currently the event is dispatched before the entities are set as clean. When `Model.afterCommit` is dispatched from the `Connection` class the entities will have been set as clean. So you'll won't be able to differentiate between an INSERT or UPDATE.

**Review by LordSimal — APPROVED** [review]
LGTM

It's only up for debate if this should go into the next patch release or next minor release.

I see it as a bugfix as this is the expected behavior which was never the case for this kind of scenario.

And the impact is minimal imho as this only affects users who manually start a transaction and manually do a save or delete operation inside that transaction.

**Review by ADmad — COMMENTED** [review]
This is a significant change in behavior and needs to target `5.next`.

One major point of concern is that when `Model.afterCommit` is triggered from the `Connection` class the entity state would have already been cleaned. So for e.g. differentiating between an INSERT or UPDATE won't be possible. Add a test which checks `$entity->isNew()` for a newly saved entity.

File: src/Database/Connection.php (hunk 7 above)
Comment (jamisonbryant) [reply src/Database/Connection.php:528]: This pattern guards against a callback itself calling `afterCommit()` which would execute immediately since we're outside a transaction at that point.

Laravel's `DatabaseTransactionsManager::commit()` uses a similar approach, splitting the committed transaction records out of the collection before iterating them.

That said, in hindsight the practical risk is low here because `afterCommit()` already short-circuits to immediate execution when no transaction is active.

In summary: this is probably an overly-protective footgun preventer. Want me to remove it?

File: src/ORM/Table.php (hunk 9 above)
Comment (jamisonbryant) [reply src/ORM/Table.php:2435]: OK, I'm going to try deferring `clean()` etc. into their own `afterCommit` callback. I wrote a (failing) test demonstrating the issue you pointed out, if it fixes it I will push both changes.

File: src/Database/Connection.php (hunk 6 above)
Comment (jamisonbryant) [reply src/Database/Connection.php]: Adjusted.

File: src/ORM/Table.php (hunk 9 above)
Comment (jamisonbryant) [reply src/ORM/Table.php:2435]: I was able to fix it but I'm quite un-confident in the code, and I even think it should maybe go in a separate PR. However, that would leave this one in a non-working state. Not sure if that's OK or not.

**Comment by jamisonbryant** [comment]
Gonna put this in 5.3.4 milestone for now, if we have to bump it out for stability/compatibility then that's fine but I was hoping for this to land sooner than later.

File: src/Database/Connection.php [hunk 10]
```diff
@@ -471,6 +478,26 @@ public function begin(): void
         }
     }
 
+    /**
+     * Register a callback to run after the outermost transaction commits.
+     *
+     * If no transaction is active, the callback executes immediately.
+     * Callbacks are discarded on rollback.
```
Comment (markstory) [inline src/Database/Connection.php:485]: Why is the callback executed right away? Couldn't that hide mistakes like calling `afterCommit()` outside of a transaction?

File: src/ORM/Table.php [hunk 11]
```diff
@@ -1966,15 +1973,35 @@ public function save(
...
         if ($success) {
+            $deferToCommit = $options['_primary']
+                && $this->getConnection()->inTransaction();
+
             if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
                 $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
+            } elseif ($deferToCommit) {
+                $this->getConnection()->afterCommit(
+                    fn() => $this->dispatchEvent('Model.afterSaveCommit', [
+                        'entity' => $entity,
```
Comment (markstory) [inline src/ORM/Table.php:2000]: With this being a deferred callback, do we need to snapshot the entity? Or will be returning the latest record be what is expected?

File: tests/TestCase/Database/ConnectionTest.php [hunk 12]
```diff
@@ -1286,4 +1287,121 @@ public function testRoleConfigInheritance(): void
...
+
+    public function testAfterCommitCallbackDiscardedOnRollback(): void
+    {
+        $fired = false;
+        $this->connection->begin();
+        $this->connection->afterCommit(function () use (&$fired): void {
+            $fired = true;
+        });
+        $this->connection->rollback();
+        $this->assertFalse($fired);
```
Comment (markstory) [inline tests/TestCase/Database/ConnectionTest.php:1311]: What if you call `commit()` after? It would be good to have a test ensuring that the callback doesn't fire next time.

File: src/Database/Connection.php (hunk 10 above)
Comment (jamisonbryant) [reply src/Database/Connection.php:485]: I tried to mirror how things work with e.g. `Table::afterSaveCommit`.

When save is called outside a transaction, `inTransaction()` is false, so `_transactionCommitted()` returns true, and the afterSaveCommit event fires immediately. That's the existing behavior in Table::save():

```
if ($this->_transactionCommitted($options['atomic'], $options['_primary'])) {
      $this->dispatchEvent('Model.afterSaveCommit', compact('entity', 'options'));
}
```

File: src/ORM/Table.php (hunk 11 above)
Comment (jamisonbryant) [reply src/ORM/Table.php:2000]: see `fe7b592` - entity cleanup is _also_ deferred to `afterCommit`. So the entity preserves its dirty flags and new-ness state until after the callback fires.

Latest state is intentional and correct, from what I can tell. Feedback welcome.

File: tests/TestCase/Database/ConnectionTest.php (hunk 12 above)
Comment (jamisonbryant) [reply tests/TestCase/Database/ConnectionTest.php:1311]: Great idea. Will update the existing test.

File: src/Database/Connection.php (hunk 10 above)
Comment (markstory) [reply src/Database/Connection.php:485]: > I tried to mirror how things work with e.g. Table::afterSaveCommit.

Ah darn, given that you're using the new system to run the old one, I see why the consistency is important now. :+1:

**Review by markstory — APPROVED** [review]
Nice work :clap:

**Comment by jamisonbryant** [comment]
Adding one more test to satisfy codecov and also put up a [docs PR](https://github.com/cakephp/docs/pull/8281).

**Comment by LordSimal** [comment]
This change causes problems with at least the `Cake\TestSuite\Fixture\TransactionStrategy` as it does not clean up entries properly anymore while doing the rollback after a test.

E.g. I have a very simple test like this:
```
$entry = SoftwareFactory::make()->withSoftwareKeys()->persist();
$this->Softwares->delete($entry);
$this->assertEmpty(SoftwareFactory::count());
```

Which does not work anymore as the entry is still present.

**Comment by dereuromark** [comment]
I fixed it for FixtureFactory using https://github.com/dereuromark/cakephp-fixture-factories/pull/32
