### PR TITLE
Remove incorrect argument type.

### LINKED ISSUE #15280: Cake\Validation\Validation::imageWidth() should expect an UploadedFile object instead of an array
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.1.7
* Platform and Target: OpenSuse 15.2, MySQL

### What you did
I tried to patch an entity with form data that contained an UploadedImage object.
I also have the following validation rule:

```php
$validator->add('image', 'largeurImageInvalide', [
    'rule' => ['imageWidth', '==', 640],
    'message' => __('The image width must be 640 pixels.'),
]);
```

### What happened
`'Argument 1 passed to Cake\Validation\Validation::imageWidth() must be of the type array, object given'.`

### What you expected to happen
Validation should not throw an error.

### PR DESCRIPTION
**Pull request by ADmad**
Closes #15280

### CODE REVIEW

File: src/Validation/Validation.php [hunk 1]
```diff
@@ -1463,12 +1463,12 @@ public static function imageSize($file, array $options): bool
     /**
      * Validates the image width.
      *
-     * @param array $file The uploaded file data from PHP.
```
Comment (dereuromark) [inline src/Validation/Validation.php:1466]: Could we just be concrete here with array|UploadedFile ?
That would help also understanding of IDE/PHPStan etc.

Comment (ADmad) [reply src/Validation/Validation.php:1466]: All other validation methods also have `mixed` since the argument comes from user input which can be of any type.

Comment (dereuromark) [reply src/Validation/Validation.php:1466]: But then you need to guard it with a type check and early return false
Otherwise, semantically, this can blow up from user land site as internal error without it supposed to happen.

Comment (ADmad) [reply src/Validation/Validation.php:1466]: > But then you need to guard it with a type check and early return false

Which is done by the `Valdiation::getFilename()` method which is called further down the call chain.
