### PR TITLE
Fix deleteMany stopping after the first failure

### LINKED ISSUE #16347: CacheEngine stops deleteMany after first non existent key
### Description

I have noticed that if you call a deleteMany on the CacheEngine class with keys that could return false due to not existing in the cache it will stop running deleteMany entirely, i.e.
````
[
    'key1',
    'key2',
]
````
Key1 does not exist but key2 does, but key2 will never be removed because key1 returns false from the function.

This also means this function has unpredictable behaviour depending on the order in which you place keys, so defo buggy.

### CakePHP Version

4.3

### PHP Version

7.1

### PR DESCRIPTION
**Pull request by markstory**
DeleteMany should be more of a best-effort vs stopping at the first missing key.

Fixes #16347

### CODE REVIEW

File: src/Cache/CacheEngine.php [hunk 1]
```diff
@@ -198,14 +198,14 @@ public function deleteMultiple($keys): bool
...
-            $result = $this->delete($key);
-            if ($result === false) {
-                return false;
+            if (!$this->delete($key)) {
+                $result = false;
             }
         }
 
-        return true;
+        return $result;
```
Comment (othercorey) [inline src/Cache/CacheEngine.php:212]: We should update the docblock to explain it attempts to delete all even if there was an error.
