### PR TITLE
Removes args from stack trace when args = false.

### LINKED ISSUE #16635: Debugger::formatTrace showing args when args is set to false
### Description

I have some code that adds stack traces and other information to the output of errors:

```php
        if (!Configure::read('debug')) {
            return $viewVars;
        }

        $trace = (array)Debugger::formatTrace(
            $exception->getTrace(),
            [
                'format' => 'array',
                'args' => false,
            ]
        );

        $origin = [
            'file' => $exception->getFile() ?: 'null',
            'line' => $exception->getLine() ?: 'null',
        ];

        // traces don't include the origin file/line.
        array_unshift($trace, $origin);
        $viewVars['trace'] = $trace;
        $viewVars += $origin;
```

The `formatTrace` method doesn't appear to be respecting args = false. Example trace item:

```json
        {
            "file": "\/srv\/app\/vendor\/cakephp\/cakephp\/src\/Controller\/ControllerFactory.php",
            "line": 139,
            "function": "invokeAction",
            "class": "Cake\\Controller\\Controller",
            "type": "-\u003E",
            "args": [
                {},
                [
                    {}
                ]
            ]
        },

```

Proposed change:

```php
            } elseif ($options['format'] === 'array') {
                if (!$options['args']) {
                    unset($trace['args']);
                }
                $back[] = $trace;
```

### CakePHP Version

4.4.2

### PHP Version

8.0

### PR DESCRIPTION
**Pull request by cnizzardini**
Removes args from stack trace when args = false.

Reference #16635

### CODE REVIEW

File: src/Error/Debugger.php [hunk 1]
```diff
@@ -442,6 +442,9 @@ public static function formatTrace($backtrace, array $options = [])
             if ($options['format'] === 'points' && $trace['file'] !== '[internal]') {
                 $back[] = ['file' => $trace['file'], 'line' => $trace['line']];
             } elseif ($options['format'] === 'array') {
+                if (!$options['args']) {
+                    unset($trace['args']);
```
Comment (othercorey) [inline src/Error/Debugger.php:446]: Should we fix wherever args is checked?

Comment (cnizzardini) [reply src/Error/Debugger.php:446]: We could move this up to around here: https://github.com/cakephp/cakephp/blob/15448de161da53f22ecab0409f2b4d3a7020d749/src/Error/Debugger.php#L419

As far as I could tell its only a problem when the format is array.

**Comment by markstory** [comment]
Thanks!
