### PR TITLE
Fix up eager loading.

### LINKED ISSUE #11395: Eager loaded Translations do not propagation limit & order into generated queries
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.4.10
* Platform and Target: Apache2, MySQL.

### What you did
I try to fetch a `Date` with associated `Event` (1<->n). The `Event` has translations. The `Event` has a Topic `MainTopic` (n<->1). The `MainTopic` has translations. I want to fetch a limited number of `Dates` with its associated `Events` and the associated data from these `Events` including the translations.
My query:
```
$this->Dates->find()
            ->select([
                $this->Dates->aliasField('date_start'),
                $this->Dates->aliasField('date_end'),
                $this->Dates->aliasField('time_start'),
                $this->Dates->aliasField('time_end'),
            ])->contain([
                'Events' => function (Query $query) {
                    return $query->find('translations', ['restrictToEnabled'=> false])
                        ->select([
                            'id',
                            'foreign_key',
                            'visited',
                            'approved',
                            'created',
                            'modified',
                            'speaker',
                            'affiliation_speaker',
                            'event',
                            'host',
                            'event_id',
                            'enabled',
                            'language'
                        ])->contain([
                            //gets limited but dont get sorted
                            'MainTopics' => function (Query $query) {
                                return $query->find('translations')
                                    ->select(['id', 'topic']);
                            }
                        ]);
                },
            ])->order('Events.id DESC')->limit(1);
```

### What happened
Resulting SQL:
```
SELECT 
  `Dates`.`date_start` AS `Dates__date_start`, 
  `Dates`.`date_end` AS `Dates__date_end`, 
  `Dates`.`time_start` AS `Dates__time_start`, 
  `Dates`.`time_end` AS `Dates__time_end`, 
  `Events`.`id` AS `Events__id`, 
  `Events`.`foreign_key` AS `Events__foreign_key`, 
  `Events`.`visited` AS `Events__visited`, 
  `Events`.`approved` AS `Events__approved`, 
  `Events`.`created` AS `Events__created`, 
  `Events`.`modified` AS `Events__modified`, 
  `Events`.`speaker` AS `Events__speaker`, 
  `Events`.`affiliation_speaker` AS `Events__affiliation_speaker`, 
  `Events`.`event` AS `Events__event`, 
  `Events`.`host` AS `Events__host`, 
  `Events`.`event_id` AS `Events__event_id`, 
  `Events`.`enabled` AS `Events__enabled`, 
  `Events`.`language` AS `Events__language`, 
  `MainTopics`.`id` AS `MainTopics__id`, 
  `MainTopics`.`topic` AS `MainTopics__topic`, 
  `Datasources`.`name` AS `Datasources__name`, 
  `Locations`.`location` AS `Locations__location`, 
  `Organizers`.`organizer` AS `Organizers__organizer`, 
  `Series`.`name` AS `Series__name` 
FROM 
  `dates` `Dates` 
  INNER JOIN `events` `Events` ON `Events`.`id` = (`Dates`.`event_id`) 
  INNER JOIN `topics` `MainTopics` ON `MainTopics`.`id` = (`Events`.`topic_id`) 
ORDER BY 
  Events.id DESC 
LIMIT 
  1
```
```
SELECT 
  `Eventsi18n`.`id` AS `Eventsi18n__id`, 
  `Eventsi18n`.`locale` AS `Eventsi18n__locale`, 
  `Eventsi18n`.`model` AS `Eventsi18n__model`, 
  `Eventsi18n`.`foreign_key` AS `Eventsi18n__foreign_key`, 
  `Eventsi18n`.`field` AS `Eventsi18n__field`, 
  `Eventsi18n`.`content` AS `Eventsi18n__content` 
FROM 
  `eventsi18n` `Eventsi18n` 
  INNER JOIN (
    SELECT 
      (`Events`.`id`) 
    FROM 
      `dates` `Dates` 
      INNER JOIN `events` `Events` ON `Events`.`id` = (`Dates`.`event_id`) 
      INNER JOIN `topics` `MainTopics` ON `MainTopics`.`id` = (`Events`.`topic_id`) 
    GROUP BY 
      `Events`.`id` 
    ORDER BY 
      Events.id DESC 
    LIMIT 
      1
  ) `Events` ON `Eventsi18n`.`foreign_key` = (`Events`.`id`) 
WHERE 
  `Eventsi18n`.`model` = 'Events'
```
```
SELECT 
  `Topicsi18n`.`id` AS `Topicsi18n__id`, 
  `Topicsi18n`.`locale` AS `Topicsi18n__locale`, 
  `Topicsi18n`.`model` AS `Topicsi18n__model`, 
  `Topicsi18n`.`foreign_key` AS `Topicsi18n__foreign_key`, 
  `Topicsi18n`.`field` AS `Topicsi18n__field`, 
  `Topicsi18n`.`content` AS `Topicsi18n__content` 
FROM 
  `topicsi18n` `Topicsi18n` 
  INNER JOIN (
    SELECT 
      (`MainTopics`.`id`) 
    FROM 
      `dates` `Dates` 
      INNER JOIN `events` `Events` ON `Events`.`id` = (`Dates`.`event_id`) 
      INNER JOIN `topics` `MainTopics` ON `MainTopics`.`id` = (`Events`.`topic_id`) 
    GROUP BY 
      `MainTopics`.`id` 
    LIMIT 
      1
  ) `MainTopics` ON `Topicsi18n`.`foreign_key` = (`MainTopics`.`id`) 
WHERE 
  `Topicsi18n`.`model` = 'Topics'
```
The second query includes the sorting and the limiting therefore it results in a correct join. But the third query just gets propagated the limit and not the sort anymore. It will use a `MainTopics`.`id` from another `Event` and will not join properly into the main query.

Example:
`Date` id = A, event_id = 1
`Event` id = 1, topic_id = 1
`Event` id = 2, topic_id = 2
`Eventi18n` foreign_key = 2
`MainTopic` id = 1
`MainTopic` id = 2
`Topici18n` foreign_key = 1
`Topici18n` foreign_key = 2

First query gets `Date` with associated `Event` id = 2, topic_id = 2. Second query gets translations because it fetches `Event` id = 2 in subquery (order by `Event`.`id` desc and limit 1). Third query fetches the wrong event `Event` id = 1 with topic_id = 1 (limit 1 no order). No translation will be joined to `MainTopic` id = 2 in main query.

### What you expected to happen
I think the limit should not get propagated into the contain models. If there wont be a limit in the subqueries all translations would get fetched correctly. Another possibility would be to properly propagate the `ORDER` clause into all queries.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/11395

### CODE REVIEW

File: tests/TestCase/ORM/Association/HasManyTest.php [hunk 1]
```diff
@@ -770,6 +770,47 @@ public function testSubqueryWithLimitAndOrder(): void
...
+
+        $result = $query->first();
+
+        // Verify that we got a result
+        $this->assertNotNull($result);
+
+        // If the author has articles, verify they are properly limited and ordered
+        if (!empty($result->articles)) {
+            // Check that we got at most 2 articles due to the limit
+            $this->assertLessThanOrEqual(2, count($result->articles));
```
Comment (markstory) [inline tests/TestCase/ORM/Association/HasManyTest.php]: Why would there be fewer? Couldn't this test silently fail by not running in the future if fixture rows were reduced?

Comment (dereuromark) [reply tests/TestCase/ORM/Association/HasManyTest.php]: More explicit test data now.
Feel free to adjust, though.

Is the approach valid in general?

File: tests/TestCase/ORM/Query/QueryRegressionTest.php [hunk 2]
```diff
@@ -1716,4 +1716,101 @@ public function testTranspiledFunctionExpressionWithCorrelatedSubquery(): void
...
+
+    /**
+     * Test that eager loading with subquery strategy properly preserves limit and order clauses.
+     * This is a regression test for issue #11395 where limit and order clauses were not
+     * properly propagated in eager loaded associations.
+     *
+     * @see https://github.com/cakephp/cakephp/issues/11395
+     * @return void
+     */
+    public function testEagerLoadingWithOrderAndLimitPreservation(): void
```
Comment (markstory) [inline tests/TestCase/ORM/Query/QueryRegressionTest.php:1728]: Do we need the same test twice?

**Comment by othercorey** [comment]
Nice work!
