### PR TITLE
2.7 fix PDO exception from Model::exists when useTable is false - #7229

### LINKED ISSUE #7229: Validate still query to database when there is field "id" in a model that doesn't have table `$useTable = false`
Model that doesn't have table to validate form register

```php
class Api extends Model {

	public $useTable = false;

	public function validateUserRegister() {
		$this->validate = array(
			'name' => array(
				'notBlank' => array(
					'rule' => array('notBlank'),
					'message' => 'Please enter name',
					'required' => true
				),
			),
			'email' => array(
				'notBlank' => array(
					'rule' => array('notBlank'),
					'message' => 'Please enter email',
					'required' => true
				),
			),
		);
		return $this->validates();
	}
}
```

Controller call the `validateUserRegister()` in model `Api`

```php
class V01Controller extends AppApiController {

	public $uses = array('Api.Api', 'User');

	public function register() {
		$this->Api->set($this->request->data);
		if ($this->Api->validateUserRegister()) {
			// todo
		}
	}
}
```

Browser request with below data is OK:

```json
{
    "name": "Toto",
    "email": "toto@gmail.com"
}
```

But when the request with this data, it shows an error :
```json
{
    "id": "10",
    "name": "Toto",
    "email": "toto@gmail.com"
}
```

```
Database Error

Error: SQLSTATE[42S02]: Base table or view not found: 1146 Table 'koicafe.koi_apis' doesn't exist

SQL Query: SELECT COUNT(*) AS `count` FROM `koicafe`.`koi_apis` AS `Api` WHERE `Api`.`id` = 10 
```
I think there is a bug on validation core of CakePHP when the table is not used, it still query to database on the table with the name of model.

### PR DESCRIPTION
**Pull request by tanuck**
This is trying to resolve #7229 - Model::exists() will now skip the find call when `$useTable = false`

### CODE REVIEW

File: lib/Cake/Model/Model.php [hunk 1]
```diff
@@ -2895,6 +2895,10 @@ public function exists($id = null) {
 			return false;
 		}
 
+		if ($this->useTable === false) {
+			return true;
```
Comment (dereuromark) [inline lib/Cake/Model/Model.php]: Shouldn't that return false then instead? Why returning true?

Comment (tanuck) [inline lib/Cake/Model/Model.php]: My thinking was, try to maintain the `'on' => 'create'` & `'on' => 'update'` in the validator. So if there is no id set then it returns false like usual. When the id is set, I was considering it a 'simulation' of an update call, therefore return true.

It's just suggestion, I can change it to return false if you think it's an over complication?

Comment (markstory) [inline lib/Cake/Model/Model.php]: I would think exists() should always return false, when useTable == false. We have no way of knowing whether or not the record exists, and often there is _no_ record so it can't exist.

Comment (tanuck) [inline lib/Cake/Model/Model.php]: Thats fair enough. Was just a suggestion, I'll revert it back to returning false :)

**Comment by ravage84** [comment]
How does this behave for models based on datasources that manually set the $records property, such as the ``ArraySource``?

**Comment by markstory** [comment]
@ravage84 Do those datasources also require the use of `useTable = false`?

**Comment by ravage84** [comment]
It seems it's not necessary officially, as you can see here:
https://github.com/cakephp/datasources/blob/master/Test/Case/Model/Datasource/ArraySourceTest.php#L29-L67

Documentation is scarce on this unfortunately...

But I just checked one of our code bases and for some reason we have set it to ``$useTable = false``...

How about we change the check to this?

```` php
if ($this->useTable === false && !empty($this->records)) {
````
Or something like that?
