### PR TITLE
Fix Query::bind() to make the count query

### LINKED ISSUE #15175: Query::bind() does not make the count query dirty although it should
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.12
* Platform and Target: Apache, MySQL

### What you did
In a table class:
```
        $Query = $this->find()
            ->where([
                'created BETWEEN :start AND :end',
            ])
            ->bind(':start', $today)
            ->bind(':end', $tomorrow);
        $dailyCount = $Query->count();
        ...
        $Query
            ->bind(':start', $monday)
            ->bind(':end', $sunday);
        $weeklyCount = $Query->count();
```

### What happened
This executed the query only one time when the first call to `->count()` was done.

### What you expected to happen
I would expect two statements to be executed.

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/15175

Given that this has been the case forever, this might be a bit more behavior changing to some existing apps.
Targeting ~~5.next~~ 5.x

### CODE REVIEW

File: tests/TestCase/ORM/Query/SelectQueryTest.php [hunk 1]
```diff
@@ -2397,6 +2417,32 @@ public function testCountCacheDirty(): void
         $this->assertSame(2, $thirdResult, 'The query has not been modified, the cached value is valid');
     }
 
+    /**
+     * Test that bind() marks the query as dirty and clears cached count
+     */
+    public function testCountCacheClearedOnBind(): void
+    {
+        $query = $this->getMockBuilder(Query::class)
```
Comment (ADmad) [inline tests/TestCase/ORM/Query/SelectQueryTest.php]:
```suggestion
        $query = $this->getMockBuilder(SelectQuery::class)
```

File: tests/TestCase/ORM/Query/SelectQueryTest.php [hunk 2]
```diff
@@ -1611,6 +1611,26 @@ public function testCount(): void
...
+    /**
+     * Test that rebinding parameters clears the count cache
+     */
+    public function testCountWithRebinding(): void
+    {
+        $table = $this->getTableLocator()->get('Articles');
+
+        $query = $table->find()
+            ->where('Articles.id >= :start')
+            ->bind(':start', 1, 'integer');
```
Comment (ADmad) [inline tests/TestCase/ORM/Query/SelectQueryTest.php]: > Worth mentioning that marking an already executed query dirty will reset all existing bindings, so if bind() would mark the query dirty, each bind() call would remove any previously set bindings, so that only the last bind() call would have any effect.

Considering the above comment by ndm2 on the related issue, the test should have at least 2 `bind()`.

Comment (dereuromark) [reply tests/TestCase/ORM/Query/SelectQueryTest.php]: Done

**Comment by dereuromark** [comment]
Seems actually pretty safe to even apply to 5.x, no?
Which also allows a possible backport to 4.x if someone wanted to do it.

**Comment by ADmad** [comment]
> Seems actually pretty safe to even apply to 5.x, no?

Yes, I think this can go in 5.x itself. I checked the code too and `_dirty()` resets the value binder only if the query has been already executed and statement instance generated. So having `bind()` call `_dirty()` should not cause any problems.

https://github.com/cakephp/cakephp/blob/48af2bbe61f2b6ffe39d4930e0b7ceb172c9bfb7/src/Database/Query.php#L1780-L1782

**Comment by othercorey** [comment]
I always thought this had side-effects. If this works, nice fix.

File: tests/TestCase/ORM/Query/SelectQueryTest.php [hunk 3]
```diff
@@ -2397,6 +2420,36 @@ public function testCountCacheDirty(): void
...
     }
 
+    /**
+     * Test that bind() marks the query as dirty and clears cached count
+     */
+    public function testCountCacheClearedOnBind(): void
+    {
+        $query = $this->getMockBuilder(SelectQuery::class)
+            ->disableOriginalConstructor()
+            ->onlyMethods(['_performCount'])
```
Comment (markstory) [inline tests/TestCase/ORM/Query/SelectQueryTest.php:2430]: Why do you use a mock here? Wouldn't executing the methods work just as well?

Comment (dereuromark) [reply tests/TestCase/ORM/Query/SelectQueryTest.php:2430]: The mock should be appropriate here because these tests are specifically verifying the caching behavior of the count() method, not the actual counting logic:

  1. testCountCache() - Verifies that calling count() multiple times only executes _performCount() once (the result is cached)
  2. testCountCacheDirty() - Verifies that when the query becomes dirty, _performCount() is called again
  3. testCountCacheClearedOnBind() - Verifies that bind() properly clears the count cache

  The mock allows the test to:
  - Precisely verify call counts - Using expects($this->once()) or expects($this->exactly(2)) to ensure the cache is working correctly
  - Isolate the behavior - Test only the caching logic without involving database connections or fixtures
  - Control the return value - Can return predictable values (1, 2) to verify cache behavior

  If you executed the actual methods instead, you wouldn't be able to verify that _performCount() was called exactly once or twice.

Comment (dereuromark) [reply tests/TestCase/ORM/Query/SelectQueryTest.php:2430]: If you dont think its needed, feel free to remove it.

**Comment by dereuromark** [comment]
@bancer you just got your backport.
