### PR TITLE
Fix poorly formatted multi-line errors

### LINKED ISSUE #14510: Use of <code> in dev_error header causes unreadable title
The `<code>` tags generated by `Debugger::formatHtmlMessage()` cause an unreadable dev_error header.

With code tags:
image

Without code tags:
image

### PR DESCRIPTION
**Pull request by markstory**
Add elements to fix flex layout and separate first line and subsequent lines so that we can have a more pleasing error layout.

Fixes #14510

### Multi-line
Screen Shot 2020-04-28 at 22 57 23

### Single line
Screen Shot 2020-04-28 at 22 57 55

### CODE REVIEW

File: templates/layout/dev_error.php [hunk 1]
```diff
@@ -249,10 +255,18 @@
 </head>
 <body>
     <header>
+        <?php
+        $title = explode("\n", $this->fetch('title'));
```
Comment (othercorey) [inline templates/layout/dev_error.php:259]:
```suggestion
        $title = explode("\n", trim($this->fetch('title')));
```

File: templates/layout/dev_error.php [hunk 2]
```diff
@@ -249,10 +255,18 @@
...
+        $title = explode("\n", trim($this->fetch('title')));
+        $errorTitle = array_shift($title);
+        $errorDescription = implode("\n", $title);
+        ?>
         <h1 class="header-title">
-            <?= Debugger::formatHtmlMessage($this->fetch('title')) ?>
+            <span><?= Debugger::formatHtmlMessage($errorTitle) ?></span>
             <a>&#128203</a>
         </h1>
+        <?php if (strlen($errorDescription)): ?>
```
Comment (ADmad) [inline templates/layout/dev_error.php:267]:
```suggestion
        <?php if (strlen($errorDescription)) : ?>
```
