### PR TITLE
Fix PaginatorHelper last & first with URL parameters

### LINKED ISSUE #14894: PaginatorHelper not merging URL parameters correctly
This is an apparent **bug** in CakePHP 3.8.12.

### What I did
I'm using the `PaginatorHelper` in CakePHP 3.8 and passing `'url' => ['?' => ['foo' => 'bar']]` into the options of its `first()`, `prev()`, `next()`, and `last()` buttons.

### What happened
`prev()` and `next()` are forming URLs as expected, but `first()` and `last()` are ignoring the query string parameter and not adding `'foo'` to the URL.

### PR DESCRIPTION
**Pull request by markstory**
Incorporate URL options when generating a single first/last link.

Fixes #14894

### CODE REVIEW

File: src/View/Helper/PaginatorHelper.php [hunk 1]
```diff
@@ -1075,8 +1075,9 @@ public function first($first = '<< first', array $options = [])
             }
         } elseif ($params['page'] > 1 && is_string($first)) {
             $first = $options['escape'] ? h($first) : $first;
+            $url = array_merge($options['url'], ['page' => 1]);
```
Comment (othercorey) [inline src/View/Helper/PaginatorHelper.php:1078]: Interestingly, this means you can control the page options, but I don't think that's going to cause any problems.

**Comment by dereuromark** [comment]
I wonder when we fixed 4.x and forgot to backport it.

**Comment by othercorey** [comment]
> I wonder when we fixed 4.x and forgot to backport it.

https://github.com/cakephp/cakephp/pull/14157

File: src/View/Helper/PaginatorHelper.php (hunk 1 above)
Comment (markstory) [reply src/View/Helper/PaginatorHelper.php:1078]: Wouldn't the merge overwrite anything in options[url]?

Comment (othercorey) [reply src/View/Helper/PaginatorHelper.php:1078]: It won't overwrite 'page' or 'pageCount'. Should we pass $options['url'] as the 3rd parameter to generateUrl() like your other PR?

Comment (markstory) [reply src/View/Helper/PaginatorHelper.php:1078]: The signature of generateUrl() is different in 3.x and 4.x. In 4.x there is an addtional url parameter that is being used in the PR you referenced. I can't make a similar change here as it would require changing the public interface.
