### PR TITLE
Fix ambiguous column in self-referential subquery eager loading

### LINKED ISSUE #19395: 5.next: `Column 'ChildMenuItems.id' in SELECT is ambiguous`
### Description

Just found another new bug/regression in current 5.next aka 5.4

```
Possibly related to `Cake\Database\Exception\QueryException`: "[test] SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'ChildMenuItems.id' in SELECT is ambiguous
Query: SELECT ChildMenuItems.id AS ChildMenuItems__id, ChildMenuItems.title AS ChildMenuItems__title, ChildMenuItems.url AS ChildMenuItems__url, ChildMenuItems.icon AS ChildMenuItems__icon, ChildMenuItems.is_divider AS ChildMenuItems__is_divider, ChildMenuItems.is_main_item AS ChildMenuItems__is_main_item, ChildMenuItems.staff_member_id AS ChildMenuItems__staff_member_id, ChildMenuItems.parent_id AS ChildMenuItems__parent_id, ChildMenuItems.lft AS ChildMenuItems__lft, ChildMenuItems.rght AS ChildMenuItems__rght, ChildMenuItems.created AS ChildMenuItems__created, ChildMenuItems.modified AS ChildMenuItems__modified FROM menu_items ChildMenuItems INNER JOIN (SELECT (ChildMenuItems.id) FROM menu_items ChildMenuItems INNER JOIN (SELECT (MenuItems.id) FROM menu_items MenuItems WHERE MenuItems.id = 2 GROUP BY MenuItems.id LIMIT 1) MenuItems ON ChildMenuItems.parent_id = MenuItems.id GROUP BY ChildMenuItems.id) ChildMenuItems ON ChildMenuItems.parent_id = ChildMenuItems.id"
#0 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Driver.php(337): Cake\Database\Driver->createQueryException(Object(PDOException), Object(Cake\Database\Statement\Statement), NULL)
#1 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Driver/Mysql.php(213): Cake\Database\Driver->executeStatement(Object(Cake\Database\Statement\Statement))
#2 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Connection.php(301): Cake\Database\Driver\Mysql->run(Object(Cake\ORM\Query\SelectQuery))
#3 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Core/Retry/CommandRetry.php(71): Cake\Database\Connection->{closure:Cake\Database\Connection::run():301}()
#4 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Connection.php(301): Cake\Core\Retry\CommandRetry->run(Object(Closure))
#5 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Query.php(239): Cake\Database\Connection->run(Object(Cake\ORM\Query\SelectQuery))
#6 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/Database/Query/SelectQuery.php(125): Cake\Database\Query->execute()
#7 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(1627): Cake\Database\Query\SelectQuery->all()
#8 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(389): Cake\ORM\Query\SelectQuery->_execute()
#9 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/Loader/SelectLoader.php(537): Cake\ORM\Query\SelectQuery->all()
#10 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/Loader/SelectLoader.php(130): Cake\ORM\Association\Loader\SelectLoader->_buildResultMap(Object(Cake\ORM\Query\SelectQuery), Array)
#11 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/HasMany.php(701): Cake\ORM\Association\Loader\SelectLoader->buildEagerLoader(Array)
#12 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/EagerLoader.php(691): Cake\ORM\Association\HasMany->eagerLoader(Array)
#13 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(1631): Cake\ORM\EagerLoader->loadExternal(Object(Cake\ORM\Query\SelectQuery), Array)
#14 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(389): Cake\ORM\Query\SelectQuery->_execute()
#15 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/Loader/SelectLoader.php(537): Cake\ORM\Query\SelectQuery->all()
#16 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/Loader/SelectLoader.php(130): Cake\ORM\Association\Loader\SelectLoader->_buildResultMap(Object(Cake\ORM\Query\SelectQuery), Array)
#17 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Association/HasMany.php(701): Cake\ORM\Association\Loader\SelectLoader->buildEagerLoader(Array)
#18 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/EagerLoader.php(691): Cake\ORM\Association\HasMany->eagerLoader(Array)
#19 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(1631): Cake\ORM\EagerLoader->loadExternal(Object(Cake\ORM\Query\SelectQuery), Array)
#20 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(389): Cake\ORM\Query\SelectQuery->_execute()
#21 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(593): Cake\ORM\Query\SelectQuery->all()
#22 /Users/kevin/Documents/sunlime/alfred/vendor/cakephp/cakephp/src/ORM/Query/SelectQuery.php(604): Cake\ORM\Query\SelectQuery->first()
#23 /Users/kevin/Documents/sunlime/alfred/vendor/riesenia/cakephp-duplicatable/src/Model/Behavior/DuplicatableBehavior.php(85): Cake\ORM\Query\SelectQuery->firstOrFail()
#24 /Users/kevin/Documents/sunlime/alfred/vendor/riesenia/cakephp-duplicatable/src/Model/Behavior/DuplicatableBehavior.php(55): Duplicatable\Model\Behavior\DuplicatableBehavior->duplicateEntity(2)
#25 /Users/kevin/Documents/sunlime/alfred/src/Controller/MenuItemsController.php(239): Duplicatable\Model\Behavior\DuplicatableBehavior->duplicate(2)
```

This is caused by calling 
```
$this->MenuItems->getBehavior('Duplicatable')->duplicate($sidebarMenuItem->id);
```

with the https://github.com/riesenia/cakephp-duplicatable plugin setup like this
```
$this->addBehavior('Duplicatable.Duplicatable', [
    'contain' => ['ChildMenuItems.ChildMenuItems'],
    'remove' => ['created'],
]);
```

This table has the `Tree` behavior attached as well to build the menu.

### CakePHP Version

5.next aka 5.4

### PHP Version

8.5

### PR DESCRIPTION
**Pull request by dereuromark**
## Summary

Fixes #19395.

Since #19345 changed the default eager loading strategy for HasMany/BelongsToMany to `subquery`, self-referential associations (e.g. a tree structure with `parent_id` pointing to the same table) fail with:

```
SQLSTATE[23000]: Integrity constraint violation: 1052 Column 'X.id' in SELECT is ambiguous
```

The `subquery` strategy in `SelectLoader::_addFilteringJoin()` joins the subquery using `$this->sourceAlias`. For self-referential associations, the source and target alias are identical, so the outer query's table and the joined subquery share the same alias — making all column references ambiguous.

## Fix

When `sourceAlias === targetAlias` (self-referential association), use a suffixed alias (`{sourceAlias}_subquery`) for the inner join and update the filter identifier expressions to reference the new alias.

A regression test using the `Categories` table (which has `parent_id`) is included.

### CODE REVIEW

**Comment by LordSimal** [comment]
Can confirm, that this fixes my issue.

**Comment by nicosp** [comment]
We have similar issues with subqueries and we also use a counter to also support multiple self-joins.

**Comment by dereuromark** [comment]
> We have similar issues with subqueries and we also use a counter to also support multiple self-joins.

So this here fixes it for you as well?

**Comment by nicosp** [comment]
@dereuromark Yes, it works because we use the counter for the table alias so this allows us to use subqueries in all cases.

Thanks!

File: src/ORM/Association/Loader/SelectLoader.php [hunk 1]
```diff
@@ -320,6 +332,34 @@ protected function _addFilteringJoin(SelectQuery $query, array|string $key, Sele
...
+     * while the outer join condition must reference the alias assigned to the
+     * derived table itself.
+     *
+     * @param mixed $field The original selected field.
+     * @param string $aliasedTable The alias assigned to the joined subquery.
+     * @return mixed
+     */
+    protected function _rewriteJoinIdentifier(mixed $field, string $aliasedTable): mixed
+    {
+        if (!is_string($field)) {
```
Comment (ADmad) [inline src/ORM/Association/Loader/SelectLoader.php:348]: This means if the join conditions are specified as an expression the rewrite will fail. But i guess such cases will be rare and there's nothing we can do about it.

Comment (dereuromark) [reply src/ORM/Association/Loader/SelectLoader.php:348]: If it ever becomes a real issue, the method could be extended to walk expression trees, but that's not worth the complexity now.

File: src/ORM/Association/Loader/SelectLoader.php [hunk 2]
```diff
@@ -296,22 +296,34 @@ protected function _assertFieldsPresent(SelectQuery $fetchQuery, array $key): vo
...
+        $joinFields = [];
         $aliasedTable = $this->sourceAlias;
+        $keyCount = count((array)$key);
+
+        // When source and target use the same alias (self-referential associations
+        // like a tree structure), the subquery join alias would collide with the
+        // outer query's table alias, causing ambiguous column references.
+        // Use a suffixed alias to avoid the collision.
+        if ($aliasedTable === $this->targetAlias) {
+            $aliasedTable = $this->sourceAlias . '_subquery';
```
Comment (markstory) [inline src/ORM/Association/Loader/SelectLoader.php:308]: We might have a similar problem if someone uses a doubly nested subquery. But we can always deal with that when it becomes a real problem. If it does, we may want to consider a query transform that generates unique aliases.

**Review by markstory — APPROVED** [review]
I don't know if the double nested join is worth fixing.
