### PR TITLE
Fix missing exception code in CLI

### LINKED ISSUE #16690: Command exit code 0 on Exception
## How to reproduce : 

With Cakephp 4.4 :

```php
<?php

namespace App\Command;

use Cake\Command\Command;
use Cake\Console\Arguments;
use Cake\Console\ConsoleIo;

class TestCommand extends Command
{
    public function execute(Arguments $args, ConsoleIo $io)
    {
        throw new \Exception;
    }
}
```

`bin/cake test ; echo $?`

The return code is __0__

With Cakephp 4.3, the return code is 1

the reason is that "ConsoleErrorHandler" was doing an "exit(1)" at the end of the "handleException" while the new "ExceptionTrap" does not

### CakePHP Version

4.4

### PHP Version

_No response_

### PR DESCRIPTION
**Pull request by markstory**
Fixes #16690

### CODE REVIEW

File: src/Error/ExceptionTrap.php [hunk 1]
```diff
@@ -241,6 +241,10 @@ public function handleException(Throwable $exception): void
         } catch (Throwable $exception) {
             $this->logInternalError($exception);
         }
+        // Use this constant as a proxy for cakephp tests.
+        if (PHP_SAPI == 'cli' && !env('FIXTURE_SCHEMA_METADATA')) {
```
Comment (othercorey) [inline src/Error/ExceptionTrap.php:245]: We should come up with some internal constant to replace this sometime.
