### PR TITLE
Reverse connection aliasing logic to restore previous behavior

### LINKED ISSUE #17619: Tests have wrong Connection aliases if testing with fixtures with different connection name
### Description

I'm upgrading my application from Cake4 to Cake5 and noticed, that my tests fail if fixtures with different connection names are loaded (e.g. from a plugin).
I tried to narrow down the problem and it seems, that the function `addTestAliases()` in file `src/TestSuite/ConnectionHelper.php` is causing the problem.

My Fixture class looks like this:
```
class InvoicesFixture extends TestFixture
{
    /**
     * Test connection
     *
     * @var string
     */
    public string $connection = 'test_myapp';

    public array $records = [

```

The aliases created by this function look like that:
```
[
  'debug_kit' => 'test_debug_kit',
  'default' => 'test',
  'test_myapp' => 'myapp', // this is wrong
  'myapp' => 'test_myapp',
  'test_debug_kit' => 'debug_kit'
]
```
The code in ConnectionHelper.php
```
public function addTestAliases(): void
{
[...]
else {
    $test = 'test_' . $connection;
    ConnectionManager::alias($connection, $test);
}
```
should be in my opinion
```
public function addTestAliases(): void
{
[...]
else {
    $test = 'test_' . $connection;
    ConnectionManager::alias($test, $connection);
}
```
Currently running the tests truncates my development tables 😕 and tests fail because the data is inserted into the wrong database.

### CakePHP Version

5.0.6

### PHP Version

8.2

### PR DESCRIPTION
**Pull request by markstory**
In #17261 we reversed the connection aliasing behavior so that if you had both a test and non test connection defined, and used the `test_` prefixed names in fixtures your local development database would be truncated.

The logic historically was that the framework would require you to define test_ prefixed connections and aliases would be made from live -> test so that accessing the live connection would retrieve the test connections. Having test prefixed connection names resolve to the real connection makes it hard to maintain a persistent development environment.

Fixes #17619

### CODE REVIEW

File: src/TestSuite/ConnectionHelper.php [hunk 1]
```diff
@@ -52,7 +52,7 @@ public function addTestAliases(): void
                 ConnectionManager::alias($connection, $original);
             } else {
                 $test = 'test_' . $connection;
-                ConnectionManager::alias($connection, $test);
+                ConnectionManager::alias($test, $connection);
```
Comment (othercorey) [inline src/TestSuite/ConnectionHelper.php:55]: So this is saying the `test_` connection must exist for the original connection to work, right?

Should we just skip the non test_ connections since the test_connection must be defined and therefore the alias will eventually be added in the above if condition?

Comment (markstory) [reply src/TestSuite/ConnectionHelper.php:55]: > So this is saying the test_ connection must exist for the original connection to work, right?

Yeah, we don't want tests to run in a non test-prefixed connection as that could delete data that is important to the developer. At least with a `test_xyz` connection they will have made an explicit choice on which database will be truncated.
