### PR TITLE
Throw DatabaseException when the join table key is missing

### LINKED ISSUE #16043: Undefined index: table in (...)/Database/QueryCompiler.php, line 272
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.2.8
* Platform and Target: Apache/2.4.48, PHP 7.4.21

### What you did
I created a query with a join like this:
```
$comments = $this->Comments->find('all', [
	'fields' => ['extras', 'username'=>'users.name', 'text'],
	'join' => [
		'users' => [
			'conditions' => 'users.record_num = comments.user_id'
		]
	],
	'conditions' => [
		'users.category_id' => 1,
	]
]);
```

### What happened
That works, but throws two notices in my _debug.log_ file:
* `Notice: Notice (8): Undefined index: table in [/var/www/html/vendor/cakephp/cakephp/src/Database/QueryCompiler.php, line 272`
* `Notice: Notice (8): Undefined index: table in [/var/www/html/vendor/cakephp/cakephp/src/Database/QueryCompiler.php, line 276`
The query only works because I used the exact table name as join alias.

### What you expected to happen
I figured out that I just need to add `'table' => 'users'` in the join=>users array to get rid of the two notices, I've already done that. I just thought it would be nice if the notices were a bit more descriptive (making it super clear that I forgot the 'table' property).

Peharps if the 'table' key is missing, just try and use the alias as table name, while throwing a warning (using Cake's  `triggerWarning`) like: "Missing table name in join {$joinAlias}. Specify a table name in ${$joinAlias}['table']."

I'd really like to contribute to the CakePHP project, would that be a good first issue for me to submit a PR?

Thanks!

### PR DESCRIPTION
**Pull request by rmard**
This fixes #16043 by throwing a DatabaseException (as @markstory suggested) when a table is missing from a join created through 
```
$items = $this->Table->find('all', [
	'join' => [
		'alias' => [
			// missing table should be here
			'conditions' => '...',
		]
	],
	...
]);
```

### CODE REVIEW

File: src/Database/QueryCompiler.php [hunk 1]
```diff
@@ -270,6 +270,13 @@ protected function _buildJoinPart(array $parts, Query $query, ValueBinder $binde
     {
         $joins = '';
         foreach ($parts as $join) {
+            if (!isset($join['table'])) {
+                throw new DatabaseException(sprintf(
+                    'Could not compile join clause for alias %s. No table was specified. ' .
```
Comment (dereuromark) [inline src/Database/QueryCompiler.php]:
```suggestion
                    'Could not compile join clause for alias `%s`. No table was specified. ' .
```

**Comment by markstory** [comment]
Thank you 👍
