### PR TITLE
Initialize ProgressHelper with defaults

### LINKED ISSUE #17195: 4.x: Division by zero in ProgressHelper
### Description

Bake a command via `bin/cake bake Test`

Just like the docs say in https://book.cakephp.org/4/en/console-commands/input-output.html#command-helpers add
```
$progress = $io->helper('Progress');
$progress->increment(10);
$progress->draw();
```

to the execute method and execute the command bin `bin/cake test`

This will result in the following error:
```
2023-07-27 09:51:38 error: [DivisionByZeroError] Division by zero in /myapp/vendor/cakephp/cakephp/src/Shell/Helper/ProgressHelper.php on line 134
Stack Trace:
- /myapp/src/Command/TestCommand.php:25
- /myapp/vendor/cakephp/cakephp/src/Console/BaseCommand.php:190
- /myapp/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /myapp/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /myapp/bin/cake.php:12
- [main]:

[DivisionByZeroError] Division by zero in /myapp/vendor/cakephp/cakephp/src/Shell/Helper/ProgressHelper.php on line 134
```

Should this be adjusted in the docs or is this actually a core issue?

### CakePHP Version

4.4.15

### PHP Version

8.2

### PR DESCRIPTION
**Pull request by markstory**
By setting the default values for width and total, we can make ProgressHelper easier to use. I thought this was a better solution over raising an error.

Fixes #17195

### CODE REVIEW

File: src/Shell/Helper/ProgressHelper.php [hunk 1]
```diff
@@ -35,6 +35,17 @@
  */
 class ProgressHelper extends Helper
 {
+    /**
+     * Default value for progress bar total value.
+     * Percent completion is derived from progress/total
+     */
+    private const DEFAULT_TOTAL = 100;
```
Comment (dereuromark) [inline src/Shell/Helper/ProgressHelper.php]: shouldnt those be protected to be consistent with the rest?

Comment (markstory) [reply src/Shell/Helper/ProgressHelper.php]: That's fair, I'll update the new constants.
