### PR TITLE
Fix up routing issue with null defaults.

### LINKED ISSUE #18860: Routing issue with nulled keys
### Description

I have an app here, where someone put nulled prefix in:

        $builder->connect('/login', ['controller' => 'Users', 'action' => 'login', 'prefix' => null]);
        $builder->connect('/logout', ['controller' => 'Users', 'action' => 'logout', 'prefix' => null]);

That broke silently

a) generates /users/login again instead of /login
b) /users/login => 404

I think thats a bug somewhere, as I would expect it to ignore the nulled key (prefix, plugin etc) or at least would render the fallback verbose URL then instead of 404
So the combination of both is bad.

### CakePHP Version

5.2

### PHP Version

8.4

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/18860

While the fix for static cases is easy, just to remove the nullish keys, this can be a bit more tricky for more dynamically created ones.
So I wonder if we could just remove nullish ones in the routing code?

This seems to fix it in a BC way.

### CODE REVIEW

File: src/Routing/Route/Route.php [hunk 1]
```diff
@@ -701,7 +701,10 @@ public function match(array $url, array $context = []): ?string
         unset($url['_method'], $url['[method]'], $defaults['_method']);
 
         // Defaults with different values are a fail.
-        if (array_intersect_key($url, $defaults) != $defaults) {
+        // Filter out null values from defaults for comparison as null values
+        // should be treated as "not set" for matching purposes
+        $filteredDefaults = array_filter($defaults, fn($v) => $v !== null);
```
Comment (markstory) [inline src/Routing/Route/Route.php]: Should we filter defaults when the route is constructed? Doing the filter here will be more expensive as this is the hot-path of route matching.

Comment (dereuromark) [reply src/Routing/Route/Route.php]: The updated change moves the null filtering logic for plugin and prefix keys from using array_filter() on every match() call to checking these specific keys inline during the
  matching loop. This addresses the performance concern raised by avoiding the overhead of creating a filtered array in the hot-path of route matching.
  
 Moving to construct doesnt seem possible, but correct me If I am wrong.

**Review by markstory — APPROVED** [review]
Pushed up a fix and additional test.
