### PR TITLE
4.4 Add prompting to input options

### LINKED ISSUE #15782: RFC - Add prompting for undefined command options
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [x] feature-discussion (RFC)

When building command line tools you can end up with a complex collection of options that are hard to remember and use. When a subset of those options are required getting all of them specified can be tedious for the operator as they try/fail/read help/try again until they get a working command.

An alternative solution to this would be to allow commands to 'prompt' the operator for values if the value is undefined. An example of how this could defined is:

```php
$optionParser->addOption('color', [
   'required' => true,
   'prompt' => 'What is your favourite color?',
   'options' => ['red', 'blue', 'green'],
])
```

By providing a `prompt` string the `ConsoleOptionParser` can request option values from the operator before marking the option set as 'invalid'.  If a response to an option does not fit within the listed options an error could be printed and the question can be retried.

### Similar features:

While I wasn't able to find a similar feature in Symfony or Laravel, there are examples of this behavior in python:

* [Click prompting](https://click.palletsprojects.com/en/8.0.x/options/#option-prompting)

### PR DESCRIPTION
**Pull request by markstory**
When an input option is has a prompt we can now prompt for the missing value. This works for both required and optional options. A prompt value will overwrite the default if no value was provided.

Closes #15782

### CODE REVIEW

**Comment by othercorey** [comment]
> This works for both required and optional options.

If a prompt is set, and a user must input a value, isn't that simply a required option? What's the distinction here?

**Comment by markstory** [comment]
> If a prompt is set, and a user must input a value, isn't that simply a required option? What's the distinction here?

I expressed what happens poorly, sorry about that. With both `prompt` and `required`, the user will be prompted for the required option when it is missing. With only `required` parsing will fail and an error will be raised.

**Comment by othercorey** [comment]
But if an optional has a prompt isnt that just required?

File: src/Console/ConsoleOptionParser.php [hunk 1]
```diff
@@ -677,18 +679,19 @@ public function subcommands()
      * to parse the $argv
      *
      * @param array $argv Array of args (argv) to parse.
+     * @param \Cake\Console\ConsoleIo|null $io A ConsoleIo instance or null. If null prompt options will error.
      * @return array [$params, $args]
      * @throws \Cake\Console\Exception\ConsoleException When an invalid parameter is encountered.
      */
-    public function parse(array $argv): array
+    public function parse(array $argv, ?ConsoleIo $io): array
```
Comment (saeideng) [inline src/Console/ConsoleOptionParser.php]: optional Argument is BC, but not passing it will cause the `prompt` to be ignored

**Comment by saeideng** [comment]
another way is handling `promp` on `BaseCommand::run()` 
instead of within parser

File: src/Console/ConsoleOptionParser.php (hunk 1 above)
Comment (markstory) [reply src/Console/ConsoleOptionParser.php]: Yes. We could raise an error if a prompt is used with no `ConsoleIo` so the failure isn't silent.

**Comment by markstory** [comment]
> another way is handling promp on BaseCommand::run() instead of within parser

How would that work with required options?

**Comment by markstory** [comment]
> But if an optional has a prompt isnt that just required

The end user could provide an empty string. We don't have validation on cli options outside of using `choices`.

File: src/Console/ConsoleOptionParser.php (hunk 1 above)
Comment (saeideng) [reply src/Console/ConsoleOptionParser.php]: could we have deprecation warning if user not pass it ?
and making required Argument in cake 5?

Comment (markstory) [reply src/Console/ConsoleOptionParser.php]: yes, I plan on making this parameter required in 5.x

File: src/Console/ConsoleInputOption.php [hunk 2]
```diff
@@ -266,6 +276,34 @@ public function validChoice($value): bool
...
+    /**
+     * Collect input from the user
+     *
+     * @param \Cake\Console\ConsoleIo $io A ConsoleIo used to ask questions.
+     * @return null|string
+     */
+    public function promptForInput(ConsoleIo $io): ?string
+    {
+        if (!$this->prompt) {
+            return null;
```
Comment (othercorey) [inline src/Console/ConsoleInputOption.php]: Shouldn't this be filtered out before calling? I'm not sure prompt should return null.

Comment (markstory) [reply src/Console/ConsoleInputOption.php]: If I don't have this return here, then there are type errors with `askChoice()` and `ask()`

Comment (othercorey) [reply src/Console/ConsoleInputOption.php:298]: I guess I'm suggesting that an invalid prompt shouldn't return null but should be a configuration error. Are we calling promptForInput() on all options regardless?

**Comment by saeideng** [comment]
> How would that work with required options?

it s better to handle all related `$io` process in `Command` or   `ConsoleOptionParser` classes 

after next your changes I think the `ConsoleOptionParser` is better place to do it

I thought about this
about passing `$io` to `ConsoleInputOption::promptForInput()` 
I think this could be change

when now we have `$io` in `ConsoleOptionParser` , it could be handle here

other suggestion could be :
1) renaming `promptForInput()` to `getPrompt()`/`prompt()` or something like this 

```php
public function prompt(): ?string
{
        if (!$this->prompt) {
            return null;
        }
        return $this->prompt;
}
```
2) add `choices()` to `ConsoleInputOption`
```php
    public function choices(): ?array // only `: array` ?
    {
        return $this->_choices
```

3) handle the `ask()` / `askChoice` in `ConsoleOptionParser`

4) no need to `hasPrompt()`

**Comment by markstory** [comment]
I can try moving all the input handling logic into `ConsoleOptionParser`

**Review by saeideng — COMMENTED** [review]
Your last changes about moving to  `ConsoleOptionParser` looks good to me

**Comment by saeideng** [comment]
> But if an optional has a prompt isnt that just required?

Implementing until now in this PR:
Looks : you can have `default` value , but `prompt` will ask you to set one
Am I right?

I'm not sure both these should be happen at same time

**Comment by markstory** [comment]
> you can have default value , but prompt will ask you to set one Am I right?

Good catch, I'll get that fixed.

**Comment by saeideng** [comment]
do we need throw `ConsoleException` in  `ConsoleInputOption`  ( within `__construct()` maybe)
when user set both `default` and `prompt` ?

File: tests/TestCase/Console/ConsoleOptionParserTest.php [hunk 3]
```diff
@@ -341,7 +355,119 @@ public function testAddOptionRequiredMissing(): void
...
+     * test adding an option and prompting with cli data
+     */
+    public function testAddOptionWithPromptAndProvidedValue(): void
+    {
+        $parser = new ConsoleOptionParser('test', false);
+        $parser->addOption('color', [
+            'prompt' => 'What is your favorite?',
+        ]);
+        $out = new ConsoleOutput();
+        $io = new ConsoleIo($out, new ConsoleOutput(), new ConsoleInput(['red']));
```
Comment (saeideng) [inline tests/TestCase/Console/ConsoleOptionParserTest.php]: looks the `'red'` is redundant IMO , since `['--color', 'blue']` provided, and `$this->assertCount(0, $out->messages());`

**Review by saeideng — APPROVED** [review]
Looks good to me
only `CI / Windows` has to pass
