### PR TITLE
Fix withStatus() overwriting content-type

### LINKED ISSUE #14211: Can't set Content-Type via Response::withHeader()
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.x

### What you did

```php
	    if ($controller->getRequest()->is('json')) {
	    	return (new Response())
				->withHeader('Content-Type', 'application/json')
				->withStatus(403)
				->withStringBody(json_encode([
					'redirectUrl' => '/',
				]));
	    }
```

Doing this fixed it.

```php
	    if ($controller->getRequest()->is('json')) {
	    	return (new Response())
				->withType('application/json') // <-- See this (added)
				->withStatus(403)
				->withStringBody(json_encode([
					'redirectUrl' => '/',
				]));
	    }
```

### What happened

Got a text/html response...

### What you expected to happen

Getting an application/json type response.

If the above is intended behavior then this sucks big time. If I'm forced to use withType() for that instead of being able to use withHeader() as well, then withHeader() should throw an exception telling me that I'm not allowed to do so instead of silently overriding my set value and causing me a nice debug orgy.

### PR DESCRIPTION
**Pull request by markstory**
The withStatus() method would use the `_contentType` property which can contain stale information if `withHeader()` is used to set the content-type. Instead of storing potentially divergent information we can make the content-type header authoritative and do type munging in getType().

While this could be a breaking change we make precious few promises around protected properties. This change should be backported to 3.x as well to resolve the same problem there.

Fixes #14211

### CODE REVIEW

File: src/Http/Response.php [hunk 1]
```diff
@@ -637,7 +631,10 @@ protected function _setStatus(int $code, string $reasonPhrase = ''): void
             $reasonPhrase = $this->_statusCodes[$code];
         }
         $this->_reasonPhrase = $reasonPhrase;
-        $this->_setContentType();
+
+        if (in_array($code, [304, 204], true)) {
```
Comment (othercorey) [inline src/Http/Response.php]: I think this one might deserve a comment.

File: src/Http/Response.php [hunk 2]
```diff
@@ -464,10 +456,11 @@ public function __construct(array $options = [])
             $options['charset'] = Configure::read('App.encoding');
         }
         $this->_charset = $options['charset'];
+        $type = 'text/html';
```
Comment (ADmad) [inline src/Http/Response.php]: I am wondering if this default type should be set by `View` instead of here. Might not be worth doing it right now and potentially break some app but worth considering in future.

Comment (markstory) [reply src/Http/Response.php]: Could be something we do in a future minor release. It shouldn't be a *breaking* change but it would be a small change in behavior.
