### PR TITLE
5.x: fix console subpackage

### LINKED ISSUE #18104: Problems when just requiring the subpackage `cakephp/console`
### Description

While creating the first upgrade rules for CakePHP 6.0 I ran into some problems which are caused by the fact, that the upgrade tool only requires `cakephp/console`

---

https://github.com/cakephp/cakephp/pull/17639/files#diff-35d4aaeff519e937f2c0abbd566b15c1bd21c8e26ba5eea56fe7fbfb0d68b15dR83 intorduced a requirement to the Routing class in the core ContainerStubTrait. The simplest solution (as mentioned by ADmad) is to wrap that in a `class_exists`

---

I get `Class "Cake\Command\Command" not found` when running the RectorCommandTest because we reference the code values via the command class (which is not present when just requiring `cakephp/console`)

### CakePHP Version

5.1

### PHP Version

8.3

### PR DESCRIPTION
**Pull request by LordSimal**
Closes https://github.com/cakephp/cakephp/issues/18104

### CODE REVIEW

**Review by dereuromark — APPROVED** [review]

File: src/Core/TestSuite/ContainerStubTrait.php [hunk 1]
```diff
@@ -81,7 +81,9 @@ public function configApplication(string $class, ?array $constructorArgs): void
      */
     protected function createApp(): HttpApplicationInterface|ConsoleApplicationInterface
     {
-        Router::resetRoutes();
+        if (class_exists('Cake\Routing\Router')) {
```
Comment (ADmad) [inline src/Core/TestSuite/ContainerStubTrait.php]:
```suggestion
        if (class_exists(Router::class)) {
```

The class-string expansion doesn't need the class to be present/loaded.
