### PR TITLE
Change how a single view var is inferred with `'_serialize' => true`

### LINKED ISSUE #7482: 3.1 - _serialize = true unexpected results
(From #6502)

Hey guys. With the way `_serialize=true` is working it doesn't seem possible to have it work when you have a single var.

```
$status = 1;
$this->set(compact('status') + ['_serialize' => true]);
```

If you do the above right now, you get this response, which isn't valid JSON:
```
1
```

However, if you have more than one var, it works as expected:
```
$status = 1;
$a = 'b';
$this->set(compact('status', 'a') + ['_serialize' => true]);
```

Returns:
```
{
    "status": 1,
    "a": "b"
}
```

The unexpectedness of that makes me think this is a bug, but it's possible that's as intended.

### PR DESCRIPTION
**Pull request by ADmad**
Now if a single view var is set it's inferred as `'_serialize' => ['var']`
instead of `'_serialize' => 'var'`.

Closes #7482

### CODE REVIEW

File: tests/TestCase/View/XmlViewTest.php [hunk 1]
```diff
@@ -253,13 +253,13 @@ public function testRenderWithSerializeTrue()
...
         $Controller = new Controller($Request, $Response);
-        $data = ['users' => ['user' => ['user1', 'user2']]];
+        $data = ['user' => ['user1', 'user2']];
         $Controller->set(['users' => $data, '_serialize' => true]);
         $Controller->viewClass = 'Xml';
         $View = $Controller->createView();
         $output = $View->render();
 
-        $this->assertSame(Xml::build($data)->asXML(), $output);
+        $this->assertSame(Xml::build(['response' => ['users' => $data]])->asXML(), $output);
```
Comment (markstory) [inline tests/TestCase/View/XmlViewTest.php]: Why does the output change? Was the old test wrong?

Comment (ADmad) [inline tests/TestCase/View/XmlViewTest.php]: Output has changed because behavior has changed. Earlier if only single view var was set using `'_serialize' => true` was treated as `'_serialize' => 'var'` whereas now it's treated as `'_serialize' => ['var']` which yields different result.

Please check the discussion on #7482.

Comment (markstory) [inline tests/TestCase/View/XmlViewTest.php]: Ah OK. for JSON the change makes sense. However, XML serialization was fine previously (as long as your one var was not a scalar).

Comment (ADmad) [inline tests/TestCase/View/XmlViewTest.php]: Okay, so I should revert back changes to XmlView?

**Comment by ravage84** [comment]
Not sure if we actually should change this.
What if the the single variable in ``_serialize`` is an array?
You would get a valid JSON, right?

File: tests/TestCase/View/XmlViewTest.php (hunk 1 above)
Comment (ravage84) [inline tests/TestCase/View/XmlViewTest.php]: Keeping the (breaking) change - if at all -  to JsonView only, is a good idea.

**Comment by patrickconroy** [comment]
@ravage84 Yeah you'd get valid JSON that way. It's just that it's very unexpected that if I want a single item in JSON I'd have to first convert it to an array or add a second item, whereas if I have two things they can be any type.

**Comment by patrickconroy** [comment]
Also consider the difference with this:
```
$data = [
    'status' => $status
];
$this->set(compact('data'));
```
Returns
```
{
    "status": 1
}
```

vs
```
$data = [
    'status' => $status
];
$foo = 'dfg';
$this->set(compact('data', 'foo'));
```

Returns
```
{
    "data": {
        "status": 1
    },
    "foo": "dfg"
}
```

So if you add view vars to an existing single view var `JsonView` you'd have to either set `$status` explicitly anyway, or update your JS (or whatever) logic to handle the response differently.

File: tests/TestCase/View/XmlViewTest.php (hunk 1 above)
Comment (markstory) [inline tests/TestCase/View/XmlViewTest.php]: I think keeping the change confined to the JsonView is a safer plan.

**Comment by ADmad** [comment]
I have reverted changes to XmlView.
