### PR TITLE
Fix BufferedIterator not yielding full results

### LINKED ISSUE #15341: BufferedIterator::firstMatch not able to find elements
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.x/4.x (dcbf2095a61b87270b6a5baa11aef26a39f2bba2)
* Platform and Target: LAMP

### What you did
```
    public function testBufferedIterator() {
        $data = [['myField' => '1'], ['myField' => '2'], ['myField' => '3']];
        $buffered = (new \Cake\Collection\Collection($data))->buffered();
        // $buffered->count();
        debug($buffered->firstMatch(['myField' => '1']));
        debug($buffered->firstMatch(['myField' => '2']));
        debug($buffered->firstMatch(['myField' => '3']));
    }
```

### What happened
```
BufferedIteratorTest.php (line 42)
########## DEBUG ##########
[
  'myField' => '1'
]
###########################
BufferedIteratorTest.php (line 43)
########## DEBUG ##########
[
  'myField' => '2'
]
###########################
BufferedIteratorTest.php (line 44)
########## DEBUG ##########
null
###########################
```

### What you expected to happen
Third item should be found.

After adding a `$buffered->count()` the issue goes away, so something is likely off with the index.

### PR DESCRIPTION
**Pull request by markstory**
When a Collection\BufferedIterator is partially iterated, rewound and then iterated again it would not yield complete data as the inner iterator would be advanced while buffered data was being yielded.

Fixes #15341

### CODE REVIEW

File: src/Collection/Iterator/BufferedIterator.php [hunk 1]
```diff
@@ -117,6 +117,9 @@ public function rewind(): void
         }
 
         $this->_index = 0;
+        // Reset the wrapped iterator so if it was partially
+        // iterated before it can be resumed.
+        // parent::rewind();
```
Comment (othercorey) [inline src/Collection/Iterator/BufferedIterator.php:122]: Is this supposed to be here?

Comment (markstory) [reply src/Collection/Iterator/BufferedIterator.php:122]: Nope, I'll clean that up.
