### PR TITLE
Fix Validation::inList() warning on non-scalar input.

### LINKED ISSUE #14418: Warning in validation if value is array
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 4.0.4
* Platform and Target: Nginx, PHP 7.3, SQL Server

### What you did
In table default validation
```
$validator->inList('fieldname', [1, 2, 3, 4]);
```
Patch below post data to entity
```
fieldname[]=1&fieldname[]=2
```

### What happened
Below warning
```
In [.../src/vendor/cakephp/cakephp/src/Validation/Validation.php, line 1117]
```

### What you expected to happen
Validation error without warning.

### PR DESCRIPTION
**Pull request by markstory**
Fixes #14418

### CODE REVIEW

File: src/Validation/Validation.php [hunk 1]
```diff
@@ -1107,6 +1107,9 @@ public static function url($check, bool $strict = false): bool
      */
     public static function inList($check, array $list, bool $caseInsensitive = false): bool
     {
+        if (!is_scalar($check)) {
+            return false;
+        }
         if ($caseInsensitive) {
             $list = array_map('mb_strtolower', $list);
             $check = mb_strtolower($check);
```
Comment (dereuromark) [inline src/Validation/Validation.php:1115]: This might already need the string cast here.
