### PR TITLE
Fix silent association failures

### LINKED ISSUE #13467: belongsTo association with strategy=select
This is a (multiple allowed):

* [ ] bug
* [x] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.8.

### What you did
In table: defined belongsTo association with strategy=select
In controller: feetched results without assoc foreign key in select expression:
`$this->Table->find()->select(['id', 'name'])->contain(['Assoc'])->first();`

### What happened
I got results from primary table, but property with assoc entity is null.

### What you expected to happen
`RuntimeException` is thrown with message `'Could not find primary key value for source entity'`.

It works only when I specify assoc foreign key in select expression or skip select:
`$this->Table->find()->select(['id', 'name', 'assoc_id'])->contain(['Assoc'])->first();`
`$this->Table->find()->contain(['Assoc'])->first();`

### PR DESCRIPTION
**Pull request by markstory**
When selecting specific fields if foreign key columns are omitted, associations would silently fail to load. When we know that the source query returned results but that no foreign keys could be collected the ORM raises an error. This should help prevent missing associations. We do not raise an error for nested association loads as the nested association could be dependent on an optional association.

I can backport this fix to 3.x if folks are happy with it.

Fixes #13467

### CODE REVIEW

File: src/ORM/EagerLoader.php [hunk 1]
```diff
@@ -644,8 +649,23 @@ public function loadExternal(Query $query, StatementInterface $statement): State
             $path = $meta->aliasPath();
 
             $requiresKeys = $instance->requiresKeys($config);
-            if ($requiresKeys && empty($collected[$path][$alias])) {
-                continue;
+            if ($requiresKeys) {
+                // If the path or alias has no key the required assoication load will fail.
```
Comment (othercorey) [inline src/ORM/EagerLoader.php]:
```suggestion
                // If the path or alias has no key the required association load will fail.
```

File: src/ORM/EagerLoader.php [hunk 2]
```diff
@@ -644,8 +649,23 @@ public function loadExternal(Query $query, StatementInterface $statement): State
...
+                // Nested paths are not subject to this condition because they could
+                // be attached to joined associations.
+                if (
+                    strpos($path, '.') === false &&
+                    (!array_key_exists($path, $collected) || !array_key_exists($alias, $collected[$path]))
+                ) {
+                    $message = "Unable to load `{$path}` association. Ensure foreign key on `{$alias}` is selected.";
```
Comment (othercorey) [inline src/ORM/EagerLoader.php]:
```suggestion
                    $message = "Unable to load `{$path}` association. Ensure foreign key in `{$alias}` is selected.";
```

File: tests/TestCase/ORM/Association/BelongsToTest.php [hunk 3]
```diff
@@ -427,4 +428,32 @@ public function testAttachToNoFieldsSelected()
...
+        $this->assertNotEmpty($result->author);
+        $this->assertSame(1, $result->author->id);
+
+        $query = $articles->find()
+            ->select(['Articles.title'])
+            ->where(['Articles.id' => 1])
+            ->contain('Authors');
+
+        $this->expectException(InvalidArgumentException::class);
+        $this->expectExceptionMessage('Unable to load `Authors` association. Ensure foreign key on `Articles`');
```
Comment (othercorey) [inline tests/TestCase/ORM/Association/BelongsToTest.php]:
```suggestion
        $this->expectExceptionMessage('Unable to load `Authors` association. Ensure foreign key in `Articles`');
```

File: tests/TestCase/ORM/Association/HasManyTest.php [hunk 4]
```diff
@@ -452,6 +454,25 @@ public function testEagerLoaderMultipleKeys()
...
+     *
+     * @return void
+     */
+    public function testEagerloaderNoForeignKeys()
+    {
+        $authors = $this->getTableLocator()->get('Authors');
+        $authors->hasMany('Articles');
+
+        $this->expectException(InvalidArgumentException::class);
+        $this->expectExceptionMessage('Unable to load `Articles` association. Ensure foreign key on `Authors`');
```
Comment (othercorey) [inline tests/TestCase/ORM/Association/HasManyTest.php]:
```suggestion
        $this->expectExceptionMessage('Unable to load `Articles` association. Ensure foreign key in `Authors`');
```

**Comment by othercorey** [comment]
This looks good to me!  I think it covers a significant percentage of use cases.
