### PR TITLE
Fix belongsToMany with finder & contain

### LINKED ISSUE #16252: belongsToMany through table with finder that contains table fails
### Description

If you have the following relation setup in `ProductsTable.php`

```
$this->belongsToMany('VariantOptions', [
	'through'          => 'ProductVariantOptions',
	'targetForeignKey' => 'variant_option_id',
	'finder'           => 'forDomain',
]);
```

and the forDomain finder is located in `VariantOptionsTable.php` which looks like: 

```
public function findForDomain(Query $query, array $options)
{
	return $query->contain([
		'VariantOptionLocales' 
	]);
}
```

And then you try to save 

```
$product = $this->Products->newEntity([
	'variant_options'=>[
		[
			'description'=>1,
		]
	]
]);
$this->Products->save($product);
```

It then falls with the following error message: `The VariantOptionLocales association is not defined on ProductVariantOptions`.

This happens because in the `findForDomain` method, the `$query` objects `repository` property is an instance of the through table `ProductVariantOptions` which does not have a relation to `VariantOptionLocales`. 

The `repository` property should be an instance of the `VariantOptions` table instead. Thats how it worked in CakePHP 3.4 atleast

### CakePHP Version

4.3.0

### PHP Version

8.1

### PR DESCRIPTION
**Pull request by markstory**
When a belongsToMany association uses a finder, and that finder applies a contain() the query will fail as the query is rooted in the junction table and not the association target table. This was caused by the
changes done in #15977 to fix the wrong entity type being passed to delete callbacks.

Restoring the old query fixes this issue, but would break entity delete callbacks. To solve that I've selected all the fields on the junction table and then created the correct entity. This is a bit gross, but trying to use `contain()` on the junction association doesn't work as the table has already been `innerJoinWith()` onto the query. I also attempted to use subqueries and `where exists` but abandoned that as it caused other problems in type mapping parameters.

Fixes #16252

### CODE REVIEW

File: src/ORM/Association/BelongsToMany.php [hunk 1]
```diff
@@ -1183,27 +1184,31 @@ function () use ($sourceEntity, $targetEntities, $primaryValue, $options) {
...
-                $existing = $junction->find()
-                    ->innerJoinWith($target->getAlias())
-                    ->where($this->targetConditions())
-                    ->where($this->junctionConditions())
-                    ->where(array_combine($prefixedForeignKey, $primaryValue));
-                [$finder, $finderOptions] = $this->_extractFinder($this->getFinder());
-                if ($finder) {
-                    $existing = $target->callFinder($finder, $existing, $finderOptions);
-                }
+                $existing = $this->_appendJunctionJoin($this->find())
```
Comment (othercorey) [inline src/ORM/Association/BelongsToMany.php:1196]: It's too bad we can't cleanly build queries from finders that exclude non-essential parts like contain.

**Comment by othercorey** [comment]
Looks ok to me.

File: src/ORM/Association/BelongsToMany.php (hunk 1 above)
Comment (markstory) [reply src/ORM/Association/BelongsToMany.php:1196]: Yeah... I also wanted to try and use a `JOIN` with a subquery, but the ORM can't do that. I'm wondering if it is worth expanding the capabilities around subquery joins and making references to the outer queries easier.
