### PR TITLE
Fix plugin fixtures not finding their table

### LINKED ISSUE #19304: Plugin fixtures not finding their table
### Description

Previously my `Application::bootstrap()` looked like this:
```php
if (PHP_SAPI === 'cli') {
   $this->bootstrapCli();
} else {
   FactoryLocator::add('Table', new TableLocator()->allowFallbackClass(false));
}
```
Now I wanted to [sync it with the app](https://github.com/cakephp/app/blob/8464e0f35e93051e76605f76ec7d36256fb2bd4f/src/Application.php#L48), so only:
```php
FactoryLocator::add('Table', new TableLocator()->allowFallbackClass(false));
```

This automatically means that fallback tables will no longer be used in cli... which I didn't know I was using, though (ok, that's good to know).

Now what happens is that if I run tests, I get errors about tests in the main app using plugin fixtures in the `plugins/` directory:

```
There was 1 error:

1) App\Test\TestCase\Controller\CalendarsControllerTest::testCalendar
Cake\Core\Exception\CakeException: Cannot describe schema for table `` for fixture `Drugs\Test\Fixture\DrugsFixture`. The table does not exist.

/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:193
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:141
/home/mirko/PhpstormProjects/climat/plugins/Drugs/tests/Fixture/DrugsFixture.php:105
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:107
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:93
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TruncateStrategy.php:51
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:294
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:244
/home/mirko/PhpstormProjects/climat/tests/TestCase/Controller/CalendarsControllerTest.php:73

Caused by
Cake\ORM\Exception\MissingTableClassException: Table class for alias `Drugs` could not be found.

/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:242
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/Datasource/Locator/AbstractLocator.php:71
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/ORM/Locator/TableLocator.php:204
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/ORM/Locator/LocatorAwareTrait.php:99
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:172
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:141
/home/mirko/PhpstormProjects/climat/plugins/Drugs/tests/Fixture/DrugsFixture.php:105
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TestFixture.php:107
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/FixtureHelper.php:93
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/Fixture/TruncateStrategy.php:51
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:294
/home/mirko/PhpstormProjects/climat/vendor/cakephp/cakephp/src/TestSuite/TestCase.php:244
/home/mirko/PhpstormProjects/climat/tests/TestCase/Controller/CalendarsControllerTest.php:73
```

In fact, `App\Test\TestCase\Controller\CalendarsControllerTest` uses `Drugs\Test\Fixture\DrugsFixture` by FQCN (I also tried the `plugin.Drugs.Drugs` notation, but it's the same).

Obviously, the `Drugs\Model\Table\DrugsTable` table exists correctly, and I'm not seeing any problems.

In fact:
1) if I run the tests only for the plugins, everything is fine;
2) if I run the test directly for just that class, i.e., `vendor/bin/phpunit tests/TestCase/Controller/CalendarsControllerTest.php`, everything is fine (hmm... this makes me think some previous test is messing something up...).

But I noticed that if I add in `DrugsFixture`:
```php
public string $tableAlias = 'Drugs.Drugs';
```
Everything works fine. So, it's as if the plugin's fixture fails to auto-resolve its own table.

So I noticed that `TestFixture::init()` sets the `$this->tableAlias` property as `Drugs` (rather than `Drugs.Drugs`).

In the end, it seems to me that the problem could be here:
https://github.com/cakephp/cakephp/blob/5c7abec3348523d6d1ef693e448eba50d9bc7eae/src/TestSuite/Fixture/TestFixture.php#L152
because this does not consider that the class may be in a plugin.

Is this intentional? Or could it be my fault?
I saw that the `$tableAlias` property was added in CakePHP 5.3.0. Perhaps it's intended to be required for these cases?

Thanks.

### CakePHP Version

5.3

### PHP Version

8.5

### PR DESCRIPTION
**Pull request by dereuromark**
## Summary

- Plugin fixtures in namespaces like `MyPlugin\Test\Fixture\ArticlesFixture` now automatically get the plugin prefix in their table alias (e.g., `MyPlugin.Articles`)
- This allows them to properly resolve their Table class when `allowFallbackClass(false)` is enabled
- The fix detects the `{Plugin}\Test\Fixture\` namespace pattern and uses `Plugin::isLoaded()` to verify the namespace corresponds to an actual loaded plugin

Fixes #19304

### CODE REVIEW

File: src/TestSuite/Fixture/TestFixture.php [hunk 1]
```diff
@@ -155,7 +160,18 @@ protected function _aliasFromClass(): string
         preg_match('/^(.*)Fixture$/', $class, $matches);
         $name = $matches[1] ?? $class;
 
-        return Inflector::camelize(Inflector::tableize($name));
+        $alias = Inflector::camelize(Inflector::tableize($name));
+
+        // Detect plugin namespace pattern: {Plugin}\Test\Fixture\...
+        // and prepend plugin name to alias for proper table resolution
+        if (preg_match('/^([^\\\\]+)\\\\Test\\\\Fixture\\\\/', static::class, $nsMatches)) {
```
Comment (LordSimal) [inline src/TestSuite/Fixture/TestFixture.php]: I feel like this regex can be replaced with str_contains call combined with a explode in the next line to get the plugin name.

This would make this easier to reaad.

Comment (josbeir) [reply src/TestSuite/Fixture/TestFixture.php]: or
```$plugin = strstr(static::class, '\\Test\\Fixture\\', before_needle: true) ?: null;```

Comment (markstory) [reply src/TestSuite/Fixture/TestFixture.php]: Agreed, this could be simpler.

**Comment by josbeir** [comment]
I still think this onliner is more elegant and most certainly faster:

```php
$plugin = strstr(static::class, '\\Test\\Fixture\\', before_needle: true) ?: null;
```

**Review by josbeir — APPROVED** [review]
