### PR TITLE
Fix cookie parsing when value is undefined

### LINKED ISSUE #17296: Cookie::createFromHeaderString can cause a warning on empty value string
### Description

When the response header from a Http/Client::get request is eventually parsed by Http/Cookie/Cookie::createFromHeaderString, the method can cause a warning saying "undefined array key 1" in some situations . This happens for example when the response header contains Set-Cookie with an empty value string.

Code snippet to reproduce this:
```php
// NOTE: The url used is just an example url that contains to a src example, 
// the actual url contained privacy sensitive data and has been replaced
// by an example src that leads to the same results as the real world data.

$url = 'https://view.officeapps.live.com/op/view.aspx?src=https://www.google.com';
$fakeUseragent = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/98.0.4758.102 Safari/537.36';
$client = new \Cake\Http\Client([
    'ssl_verify_peer' => false,
    'ssl_verify_peer_name' => false,
    'ssl_verify_host' => false,
    'redirect' => 10,
]);
$response = $client->get(
    $url,
    [],
    ['headers' => ['User-Agent' => $fakeUseragent]]
);
```
It can be prevented in this particular case by adding an additional check to the CookieCollection::createFromHeader method, that will skip any empty values. I am however unsure if this would solve the issue permanently since the problem actually exists in the Cookie::createFromHeaderString method.

### CakePHP Version

4.4.17

### PHP Version

8.2

### PR DESCRIPTION
**Pull request by markstory**
Some server send malformed cookie name/value pairs that lack both the value and are missing an `=`.

Fixes #17296

### CODE REVIEW

File: tests/TestCase/Http/Cookie/CookieTest.php [hunk 1]
```diff
@@ -475,6 +475,14 @@ public function testCreateFromHeaderString(): void
         $this->assertNull($result->getSameSite());
     }
 
+    public function testCreateFromHeaderStringEmptyValue(): void
+    {
+        $header = 'cakephp; expires=Wed, 01-Dec-2027 12:00:00 GMT; path=/; domain=cakephp.org;';
+        $result = Cookie::createFromHeaderString($header);
+
+        $this->assertSame('', $result->getValue());
+    }
```
Comment (othercorey) [inline tests/TestCase/Http/Cookie/CookieTest.php:485]: Can we label this as malformed so future devs know it wasn't some misinterpretation of the standard and remove the support?

Comment (markstory) [reply tests/TestCase/Http/Cookie/CookieTest.php:485]: I don't know if we'll be able to remove support as there will always be bad servers out in the wild.
