### PR TITLE
Fix loading of old interface.

### LINKED ISSUE #16867: Paginator changes in 4.4 seem to have BC issues
### Description

Changes done in https://github.com/cakephp/cakephp/pull/16433 affect plugins and project code it seems that is using the old interface as types.

https://github.com/burzum/cakephp-service-layer/actions/runs/3487896715/jobs/5836059551

It shows green for older versions, but with latest it seems to cause problems, visible in tests and phpstan.
Any idea how we can resolve this in a BC way?

These seem to be the changes required for the plugin itself if no further action would be taken:
https://github.com/burzum/cakephp-service-layer/pull/34/files

### CakePHP Version

4.4.x

### PHP Version

8.1

### PR DESCRIPTION
**Pull request by ADmad**
Closes #16867

### CODE REVIEW

File: src/Datasource/Paging/PaginatorInterface.php [hunk 1]
```diff
@@ -41,3 +41,8 @@ public function paginate(object $object, array $params = [], array $settings = [
      */
     public function getPagingParams(): array;
 }
+
+// phpcs:disable
+// The old interface Cake\Datasource\PaginatorInterface will not load during instanceof / type checks so ensure it's loaded here
+class_alias('Cake\Datasource\Paging\PaginatorInterface', 'Cake\Datasource\PaginatorInterface');
```
Comment (othercorey) [inline src/Datasource/Paging/PaginatorInterface.php]: This looks good. We should change PagintorInterface to call class_exists() since the aliasing will fail if both files are loaded. This is how we solve this in other places.
