### PR TITLE
Fix falsey value handling in XmlView

### LINKED ISSUE #18129: XML response with a variable that has a value of 0 or empty throws "Array callback must have exactly two elements"
### Description

Hello, I found this bug on cakephp4, and checked out if this happens of cakephp5, and it does.

This is how the code looks like in cakephp5:
Image

This is the response that I have got:
Image

Expected response:
`
<response><testing>0</testing></response>
`

I think here the bug is happening:
Image

### CakePHP Version

5

### PHP Version

8.3.6

### PR DESCRIPTION
**Pull request by markstory**
Fixes #18129

### CODE REVIEW

File: src/View/XmlView.php [hunk 1]
```diff
@@ -133,10 +133,10 @@ protected function _serialize(array|string $serialize): string
                 }
             }
         } else {
-            /** @var array<mixed>|string $data */
+            /** @var array<mixed>|string|int|bool|null $data */
             $data = $this->viewVars[$serialize] ?? [];
             if (
-                $data &&
+                $data !== null &&
```
Comment (ADmad) [inline src/View/XmlView.php:139]: Do we have a test where `$data` ends up being `[]`, as the semantics have changed here a bit?

Comment (markstory) [reply src/View/XmlView.php:139]: We don't, I can add a scenario for that.

Comment (markstory) [reply src/View/XmlView.php:139]: Added a test for `[]` as well. Prior to this change, `[]` would also error.
