### PR TITLE
#17951 restore functionality to disable query logging in runtime

### LINKED ISSUE #17951: $connection->disableQueryLogging() not available anymore
### Description

I'd like to disable query logging in runtime.
This code doesn't work anymore in CakePHP5:
```
$connection = $query->getConnection();
$connection->disableQueryLogging()
```
Was deprecated in 4.5: https://github.com/cakephp/cakephp/blob/4.x/src/Database/Connection.php#L1076

This suggestion was made in Slack:
```
$connection = ConnectionManager::get('default');
/** @var \Cake\Database\Driver $driver */
$driver = $connection->getDriver();
$driver->logger = null;
```
However, there is no ```$connection->setDriver($driver)``` possibility.

### CakePHP Version

5.1

### PHP Version

8.1

### PR DESCRIPTION
**Pull request by LordSimal**
Fixes #17951

### CODE REVIEW

File: src/Database/Driver.php [hunk 1]
```diff
@@ -994,6 +1002,26 @@ public function getRole(): string
         return $this->_config['_role'] ?? Connection::ROLE_WRITE;
     }
 
+    /**
+     * Enable query logging.
+     *
+     * @return void
+     */
+    public function enableQueryLogging(): void
```
Comment (ADmad) [inline src/Database/Driver.php]: `enableAutoQuoting()/disableAutoQuoting()` return `$this`, so it would be better to do the same for these 2 methods for API consistency.

File: src/TestSuite/ConnectionHelper.php [hunk 2]
```diff
@@ -74,6 +74,7 @@ public static function enableQueryLogging(?array $connections = null): void
                 $connection->getDriver()->log($message) === false
             ) {
                 $connection->getDriver()->setLogger(new QueryLogger());
+                $connection->getDriver()->enableQueryLogging();
```
Comment (markstory) [inline src/TestSuite/ConnectionHelper.php]: Won't this change/break logging configurations that are currently working? We could have `setLogger()` also set `logQueries` to true.

Comment (LordSimal) [reply src/TestSuite/ConnectionHelper.php]: seems reasonable to always enable query logging when a logger instance is set
