### PR TITLE
Fix Router::reverse() not being compatible with setPass()

### LINKED ISSUE #16119: Router::reverse() fails for routes with ->setPass()
### Description

In my routes.php I have a route like this one:

```
$builder->connect('/articles/{slug}', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
```

Because of the `->setPass(['slug'])` the slug is listed twice in `$this->getRequest()->getAttribute('params');` which is the desired behaviour, i guess:

```
[slug] => testslug
[pass] => Array
(
    [0] => testslug
)
```

However, this causes problems when using `Router::reverse($this->getRequest()->getAttribute('params'))`, because the router class says that no route is matching. When i change my aforementioned route to ...

```
$builder->connect('/articles/{slug}/*', ['controller' => 'Articles', 'action' => 'view'])->setPass(['slug']);
```

... it creates the route `/articles/testslug/testslug`. So i think `Router::reverse()` or actually the underlying `Router::reverseToArray()` needs to handle things a little differently when using `->setPass()` when defining a route.

Same behaviour in CakePHP 3 and 4.

### CakePHP Version

3.9.6 AND 4.3.1

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by markstory**
Fixes #16119

### CODE REVIEW

File: src/Routing/Router.php [hunk 1]
```diff
@@ -655,7 +655,13 @@ public static function reverseToArray($params): array
             $params['_matchedRoute'],
             $params['_name']
         );
-        $params = array_merge($params, $pass);
+        foreach ($pass as $i => $passedValue) {
+            // Remove passed values that are also route keys
+            if (in_array($passedValue, $params)) {
```
Comment (dereuromark) [inline src/Routing/Router.php]: Do we need
```suggestion
            if (in_array($passedValue, $params, true)) {
```
here to avoid side effects of matching with numeric values and strings or alike?
