### PR TITLE
Auto coerce ints to strings when creating Options

### LINKED ISSUE #18397: Silently coerce integer defaults to strings when defining Options
### Description

A very innocuous (but wrong) way to set up Options in a Cake Command is as follows:

```
->addOption('psm', [
    'help' => 'Page segmentation mode (0-13)',
    'default' => 1,    // oh no! an integer!
])
->addOption('oem', [
    'help' => 'OCR engine mode (0-3)',
    'default' => 3,    // egads! another one!
])
```

This results in this kind of error, assuming you have strict typing enabled:

> [TypeError] Cake\Console\ConsoleInputOption::__construct(): Argument #5 ($default) must be of type string|bool|null, int given, called in /Users/asdf/Code/www/foo/webapp/vendor/cakephp/cakephp/src/Console/ConsoleOptionParser.php on line 382 in /Users/asdf/Code/www/foo/webapp/vendor/cakephp/cakephp/src/Console/ConsoleInputOption.php on line 107

It would be awesome if the Command class could silently convert these invalid options to strings under-the-hood so the user doesn't get bothered by this message and the command crashes.

### CakePHP Version

5.1.6

### PR DESCRIPTION
**Pull request by jamisonbryant**
Resolves [#18397 ](https://github.com/cakephp/cakephp/issues/18397)

### CODE REVIEW

File: src/Console/ConsoleOptionParser.php [hunk 1]
```diff
@@ -387,7 +387,14 @@ public function addOption(ConsoleInputOption|string $name, array $options = [])
                 'required' => false,
                 'prompt' => null,
             ];
+
             $options += $defaults;
+
+            // If a default value is provided and it is not a string, do a cast
+            if ($options['default'] && !is_string($options['default'])) {
+                $options['default'] = (string)$options['default'];
```
Comment (dereuromark) [inline src/Console/ConsoleOptionParser.php:394]: With `string|bool|null` as valid options, doesnt this also kill bool values? what about 1/0 in the bool context?

File: src/Console/ConsoleOptionParser.php [hunk 2]
```diff
@@ -387,7 +387,14 @@ public function addOption(ConsoleInputOption|string $name, array $options = [])
                 'required' => false,
                 'prompt' => null,
             ];
+
             $options += $defaults;
+
+            // If a default value is provided and it is not a string, do a cast
+            if ($options['default'] && !is_string($options['default'])) {
```
Comment (dereuromark) [inline src/Console/ConsoleOptionParser.php]:
```suggestion
            if ($options['default'] && is_int($options['default'])) {
```
sounds safer to me.
No other types should be cast IMO.

Comment (markstory) [reply src/Console/ConsoleOptionParser.php]: What about floats? They could be cast to string as well.

File: tests/TestCase/Console/ConsoleOptionParserTest.php [hunk 3]
```diff
@@ -185,6 +185,60 @@ public function testAddOptionDefault(): void
...
+
+     /**
+     * test adding an option with a non-string default.
+     */
+    public function testAddOptionBooleanDefault(): void
+    {
+        $parser = new ConsoleOptionParser('test', false);
+        $parser
+            ->addOption('test', [
+                'default' => true,
```
Comment (markstory) [inline tests/TestCase/Console/ConsoleOptionParserTest.php]: This would be a breaking change for many applications, as you would have been able to get booleans from `--enabled` style options. I don't think we should be casting bools to strings.

File: src/Console/ConsoleOptionParser.php (hunk 2 above)
Comment (dereuromark) [reply src/Console/ConsoleOptionParser.php]: Aren't floats are usually already displayed/expected within cake as strings, at least given the DB type etc?
Or was that just decimal types?

I think too much magic here isnt needed. The only common one people might trip over is int IMO.
