### PR TITLE
fix subjectless events throw before deprecation message is being display

### LINKED ISSUE #18692: Dispatching an Event without Subject throws an Error
## Long Description

#18353 introduces a deprecation message when a listener return value is used to set the result of an Event.
This Deprecation message calls `getSubject` on the Event.
The constructor of Event allows `$subject` to be `?object` and defaults it to `null`.
However, `getSubject` checks if `subject` is `null` and throws a `CakeException` in that case.

So a Event without a subject and with a deprecated listener-return will not yield a deprecation warning but throw `CakeException` which stops further execution.

## What I expected to happen
Event gets fired correctly, result is available, deprecation warning is emitted.

## What did happen
`CakeException` thrown when firing Event caused by missing `subject` which is not required in the class constructor.

## Possible solutions
- Catch Error when fetching subject for deprecation warning
- Note edge-case in Migration-Docs in case someone else has this problem
- Require `subject` in Event-Constructor (probably breaking change?)

## Reproduction
A simple repo with a reproduction is available here:
https://github.com/xyng/cakephp-repro

Use branch `master` for cake 5.1, use branch `cake/5.2` for cake 5.2 (only composer changes).

The Reproduction consists of a command (`TestCommand`) that invokes another class with a static function (which is a simplified version of what is done in my real app).

### CakePHP Version

5.2.4

### PHP Version

8.4

### PR DESCRIPTION
**Pull request by LordSimal**
Fixes https://github.com/cakephp/cakephp/issues/18692

### CODE REVIEW

File: src/Event/EventManager.php [hunk 1]
```diff
@@ -330,7 +330,11 @@ protected function _callListener(callable $listener, EventInterface $event): voi
         $result = $listener($event, ...array_values($event->getData()));
 
         if ($result !== null) {
-            $class = get_class($event->getSubject());
+            try {
```
Comment (ADmad) [inline src/Event/EventManager.php:333]: Instead of using a try catch skip the `get_class()` call if `$event->getSubject()` returns null.

Comment (LordSimal) [reply src/Event/EventManager.php:333]: its not about the `get_class` throwing, its about `getSubject()` throwing because no subject is present.
See https://github.com/cakephp/cakephp/blob/5.x/src/Event/Event.php#L113

Comment (LordSimal) [reply src/Event/EventManager.php:333]: and there is no other way to see if a subject is present on an EventInterface object or not

Comment (ADmad) [reply src/Event/EventManager.php:333]: Oh, it's a bit strange that the method throws an exception instead of returning null when the subject is optional. Perhaps something to change in 6.0

**Review by ADmad — APPROVED** [review]

File: src/Event/EventManager.php (hunk 1 above)
Comment (LordSimal) [reply src/Event/EventManager.php:333]: I'd also be in favor of just returning null.
It seems, that this change was done this way due to static analyzer problems in the past.
https://github.com/cakephp/cakephp/pull/13568

**Comment by othercorey** [comment]
The changes look good for a patch. The deprecation message could use a re-wording so it's clearer.
