### PR TITLE
Fix RouteBuilder::plugin() not forwarding namePrefix option

### LINKED ISSUE #15394: _namePrefix not working in \Cake\Routing\RouteBuilder::plugin
This is a (multiple allowed):
* [x] bug

* CakePHP Version: 4.2.4.
* Platform and Target: Ubuntu Linux 18.04, PHP 7.2.

### What you did
I've set up a plugin with a namePrefix for its routes.

```php
// my Plugin class
class Plugin extends BasePlugin
{
    public function routes(RouteBuilder $routes): void
    {
        $config = [
            'path' => '/sadmin',
            '_namePrefix' => 'sadmin.',
        ];

        $routes->plugin('SuperAdmin', $config, function (RouteBuilder $builder) {
            $builder->connect('/', 'Clientes::index', ['_name' => 'home']);
            $builder->fallbacks();
        });

        parent::routes($routes);
    }
}
```

### What happened
The route is registered with the _name "home" without the prefix.

### What you expected to happen
The route should be named as "sadmin.home"

I've been looking into the code and I think the issue is on the `\Cake\Routing\RouteBuilder::plugin()` method, as it's ignoring any options key other than `"path"`:

```php
// \Cake\Routing\RouteBuilder class
    public function plugin(string $name, $options = [], $callback = null)
    {
        if (!is_array($options)) {
            $callback = $options;
            $options = [];
        }

        $params = ['plugin' => $name] + $this->_params;
        $path = $options['path'] ?? '/' . Inflector::dasherize($name);
        $this->scope($path, $params, $callback);

        return $this;
    }
```
As you can see, `$options` is not passed nor merged into `scope()` method, instead only the `"path"` key is taken.
I found this bug some time ago, in cakephp 3.x, I was almost sure I'd reported it then, but it turns out that I didn't, I'd just used the scope method directly, avoiding the use of `plugin()`.

### PR DESCRIPTION
**Pull request by markstory**
I also improved the API docs for plugin() and scope() to be clearer on the supported options.

Fixes #15394

### CODE REVIEW

**Comment by othercorey** [comment]
Looks good. Do we need to backport to 3.x?

File: src/Routing/RouteBuilder.php [hunk 1]
```diff
@@ -881,8 +887,9 @@ public function plugin(string $name, $options = [], $callback = null)
             $options = [];
         }
 
-        $params = ['plugin' => $name] + $this->_params;
         $path = $options['path'] ?? '/' . Inflector::dasherize($name);
+        unset($options['path']);
+        $params = ['plugin' => $name] + $options + $this->_params;
```
Comment (ADmad) [inline src/Routing/RouteBuilder.php:892]: This mixing of options and params is confusing and doesn't make for very readable code. The constructor has two separate arguments for params and options while for thos method now both seem to be clubbed together.

We should better document which keys options and params can contain and if possible avoid such clubbing. 

Also there's inconsistent in key naming. For e.g. for the constructor's options `namePrefix` doesn't have a underscore prefix while at other places it does.

Comment (markstory) [reply src/Routing/RouteBuilder.php:892]: > We should better document which keys options and params can contain and if possible avoid such clubbing.

I considered copying over only the relevant keys but I got lazy. I can get unlazy if being explicit is important here.

> Also there's inconsistent in key naming. For e.g. for the constructor's options namePrefix doesn't have a underscore prefix while at other places it does.

`RouteBuilder::scope()` also uses `_namePrefix`. I'm pretty sure that option has an `_` because it was added in a minor release and we didn't want to shadow userland route keys.

Comment (ADmad) [reply src/Routing/RouteBuilder.php]: I pushed a commit to remove unneeded additional local var and array merging :slightly_smiling_face:.

Regarding the `$options` vs `$params` inconsistency/confusion; `plugin()`, `prefix()` are quite similar convenience wrappers for `scope()` which just preset certain values. Yet for `plugin()` the 2nd arg is called `$options` while for `prefix()` it's `$params` (which matches `scope()` when both args can have pretty much the same keys.

**Review by ADmad — APPROVED** [review]

File: src/Routing/RouteBuilder.php (hunk 1 above)
Comment (ADmad) [reply src/Routing/RouteBuilder.php]: That said I guess we can live we the current argument names.
