### PR TITLE
Fix PaginatorComponent ignoring default config

### LINKED ISSUE #16056: PaginatorComponent ignores $_defaultConfig
### Description

I just found out that the PaginatorComponent in `src\Controller\Component\PaginatorComponent.php` ignores the $_defaultConfig because it overwrites the `setConfig`-Method which itself calls `$this->_paginator->setConfig()` without the defaults:
https://github.com/cakephp/cakephp/blob/6ccf771238720ec4815a1bca68e379263afc67c7/src/Controller/Component/PaginatorComponent.php#L289

This is not a problem until you extend PaginatorComponent and try to change the default settings because it uses the $_defaultConfig in `\src\Datasource\Paginator.php` instead.

### CakePHP Version

4.2.10

### PHP Version

8.0

### PR DESCRIPTION
**Pull request by othercorey**
Fixes https://github.com/cakephp/cakephp/issues/16056

The component should not have $_defaultConfig set as it's impossible to use those values without overwriting the defaults in Paginator itself.

### CODE REVIEW

File: src/Controller/Component/PaginatorComponent.php [hunk 1]
```diff
@@ -81,6 +81,8 @@ public function __construct(ComponentRegistry $registry, array $config = [])
             $this->_paginator = new Paginator();
         }
 
+        // Call parent setConfig() to merge with defaults before proxy call to Paginator
+        parent::setConfig($config);
```
Comment (othercorey) [inline src/Controller/Component/PaginatorComponent.php]: This isn't enough. The merged config isn't passed to PaginatorComponent::setConfig() in the constructor, the original config is.
