### PR TITLE
Fix for HTML attributes being ignored for individual datetime selects.

### LINKED ISSUE #5829: 3.0 - Add $attr option for datetime parts select lists.
The following functions don't support adding HTML attributes:

``` php
$this->Form->year()
$this->Form->month()
$this->Form->day()
$this->Form->hour()
$this->Form->minute()
$this->Form->second()
$this->Form->meridian()
```

I will try do this one myself if its a good idea? :smile:

### PR DESCRIPTION
**Pull request by ADmad**
Closes #5829

### CODE REVIEW

**Comment by markstory** [comment]
Tests are failing.

**Comment by ADmad** [comment]
@markstory Fixed code to ensure all tests pass but I am not satisfied with the change. 

While this fixes problem for methods generating individual time selects you still can pass attributes when using time() or datetime(). For that I think the attributes extraction I added to `_singleDatetime()` should be moved to `_datetimeOptions()` instead and also change should be done in `DateTimeWidget`.

Currently any extra attributes passed to `$data` of `DateTimeWidget::render()` are used as attributes for `dateWidget` template, which doesn't do much good since the default [dateWidget](https://github.com/cakephp/cakephp/blob/3.0/src/View/Helper/FormHelper.php#L85) does not have any `{{attrs}}` placeholder. So instead the attributes should be passed to calls done to `SelectBoxWidget::render()` calls for generating select tags for each datetime part.

**Comment by markstory** [comment]
Is there much utility in having the same attrs applied to each select in a time/datetime compound input?

File: src/View/Helper/FormHelper.php [hunk 1]
```diff
@@ -65,6 +65,16 @@ class FormHelper extends Helper
     protected $_datetimeParts = ['year', 'month', 'day', 'hour', 'minute', 'second', 'meridian'];
 
     /**
+     * Special options used for datetime inputs.
+     *
+     * @var array
+     */
+    protected $_datetimeOptions = [
+        'interval', 'round', 'monthNames', 'minYear', 'maxYear',
```
Comment (markstory) [inline src/View/Helper/FormHelper.php]: What if each public method passed the list of exclusions to _singleDatetime()?

**Comment by ADmad** [comment]
> Is there much utility in having the same attrs applied to each select in a time/datetime compound input?

Hmm someone might want same class applied to each select but apart from that can't think of any other.

File: src/View/Helper/FormHelper.php (hunk 1 above)
Comment (ADmad) [inline src/View/Helper/FormHelper.php]: That's what I had started doing earlier but then switched to using a common list at it was more convenient to maintain.

**Comment by markstory** [comment]
One could always use a class on the wrapping div/container in that case.

**Comment by ADmad** [comment]
> One could always use a class on the wrapping div/container in that case.

Yes and one could add the wrapping div with class to the template so using the html attributes passed to datetime() as attributes for `dateWidget` template isn't very useful. 

Instead not being able to specifically set class to select elements can be restrictive as some css framework might dictate that.
