### PR TITLE
fix TableLocator::get() with options throw exception if model mocked.

### LINKED ISSUE #16603: getMockForModel not compatible with TableLocator::get() className option
### Description

**Resume:**
When mocking model, if the `fetchTable()` or `getTableLocator()->get()` is invoked with `className` option, this will throw `RunTimeException`.

**Details:**
In tests: `$table = $this->getMockForModel('Users', ['methodToMock']);`
In controller : `$this->fetchTable('Users', ['className' => UsersTable::class]);`
`Cake\Datasource\Locator\AbstractLocator::get()`: has `$this->instances[$alias]` set (by mock), a non-empty `$storeOptions` (by fetchTable) but `$this->options[$alias]` don't exists.

### CakePHP Version

4.4.1

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by Erwane**
fix #16603

### CODE REVIEW

File: tests/TestCase/ORM/Locator/TableLocatorTest.php [hunk 1]
```diff
@@ -661,4 +661,18 @@ public function testSetFallbackClassName(): void
         $table = $this->_locator->get('FooBar');
         $this->assertInstanceOf(ArticlesTable::class, $table);
     }
+
+    /**
+     * testInstanceSetButNotOptions
+     *
+     * Tests that mock model will not thrown an exception if model fetched with options.
```
Comment (dereuromark) [inline tests/TestCase/ORM/Locator/TableLocatorTest.php]:
```suggestion
     * Tests that mock model will not throw an exception if model fetched with options.
```
