### PR TITLE
Fixing json view selection via ACCEPT header.

### LINKED ISSUE #7360: 3.0 - Debug mode influences json behaviour
I have a page using jQuery (`$.getJSON()`) to repeatedly poll a JSON page to get a simple json response. I tried both the template method (`Template/Jobs/json/poll.ctp`) as the `_serialize` method. I have the RequestHandler component loaded.

In debug mode: `'debug' => true` (in `app.php`), both methods work just fine.

In production mode though (`'debug' => false`), neither of the methods work. Both yield a 500 response, because Cake is looking for a template file `Template/Jobs/poll.ctp` and cannot find it. It seems to ignore the `Accept: application/json` request header.

Workaround: enable Routing File Extensions in `routes.php`:
```
Router::extensions(['json']);
```

This seems like a bug in two ways:
 - As I don't use the `.json` extension, the routing file extensions should not be involved.
 - It is clearly not right when debug mode influences json responses.

### PR DESCRIPTION
**Pull request by lorenzo**
In the past we were relying on Router::extensions() to set the whitelist
for content types, but this should have been use only for accepting
the URL extension.

Fixes #7360

### CODE REVIEW

File: src/Routing/Router.php [hunk 1]
```diff
@@ -452,6 +452,7 @@ public static function reload()
             }
         }
         static::$_collection = new RouteCollection();
+        static::$_defaultExtensions = [];
```
Comment (markstory) [inline src/Routing/Router.php]: Shouldn't this be reset with the rest of the initialState?

**Comment by lorenzo** [comment]
@markstory Removed that extra line
