### PR TITLE
Fix XML to not break with enums.

### LINKED ISSUE #18016: Enum to string conversion in XML utility
### Description

I’m getting the following error when parsing an enum to xml document:

“App\Model\Enum\MyEnum could not be converted to string”

It occures in this line (CakePHP 5.1.1):
CORE/src/Utility/Xml.php at line 344

`$child->appendChild(new DOMText((string)$value));`

Here is the example enum:

```
enum MyEnum: int
{
    case OFF = 0;
    case ON = 1;
    case ON_WITH_EXTENSION = 2;
}
```

When you try to add __toString() method to the enum, you get a fatal error:

“Fatal error: Enum App\Model\Enum\AutoAppointmentBooking cannot include magic method __toString”

### CakePHP Version

5.1.1

### PHP Version

8.3

### PR DESCRIPTION
**Pull request by dereuromark**
Resolves https://github.com/cakephp/cakephp/issues/18016

The reporter is right that it is not consistent that serialization and handling in general of enum is now supported throughout the framework, but the XML would blow up here.
There is an easy fix and it shouldnt make it too much slower.

With this instead of the exception it now renders out
```php
$user = $this->Users->get($id); // containing backed enum Status
$xmlResponse = Xml::fromArray(['user' => $user]);
```
just fine:

xml

### CODE REVIEW

File: src/Utility/Xml.php [hunk 1]
```diff
@@ -341,7 +343,14 @@ protected static function _fromArray(
                             // https://www.w3.org/TR/REC-xml/#syntax
                             // https://bugs.php.net/bug.php?id=36795
                             $child = $dom->createElement($key, '');
-                            $child->appendChild(new DOMText((string)$value));
+                            if ($value instanceof BackedEnum) {
+                                $value = (string)$value->value;
+                            } elseif ($value instanceof UnitEnum) {
```
Comment (ADmad) [inline src/Utility/Xml.php:348]: Handling `BackedEnum` is fine but I don't think we should be dealing with `UnitEnum` as they have no associated value. For reference you can `json_encode()` `BackedEnum` but not `UnitEnum`.

https://3v4l.org/6h7cm#v8.3.13

Comment (dereuromark) [reply src/Utility/Xml.php:348]: Interesting.
I thought it doesn't hurt to add (as did we in other places), as the data can also come from any custom array that might include them.
So I don't see the harm of this check here for consistency - and to avoid it blowing up because of this. Hard to document that this is not supported for XML, but e.g. for Collection.
Also JSON doesn't throw exception, just internally converts it wrongly. So here it is mainly done to avoid the hard fail.

For FormHelper and Validator I understand the limitation and is documented as such afaik.

Comment (markstory) [reply src/Utility/Xml.php:348]: I think including the name is a reasonable solution. If devs want to control the output more, they can use a `BackedEnum`.
