### PR TITLE
Handle host & scheme in array URLs

### LINKED ISSUE #13204: Router seems to break when host is specified in integration test
This is a **bug**

* CakePHP Version: 3.7.7

### What you did
In an integration test,
```
$this->get([
    'prefix' => 'v1',
    'controller' => 'Events',
    'action' => 'future',
    '?' => ['apikey' => $this->getApiKey()],
    '_host' => 'api.app.localhost',
    '_ssl' => true
]);
```
[The docs](https://book.cakephp.org/3.0/en/development/routing.html#matching-specific-hostnames) suggest that using `_host` this way should work for URL generation, and I'm not aware of a reason why specifying `_host` for integration tests shouldn't work.

### Why
I'm working to combine a website and its API into one codebase. It's currently set up to reject any requests for pages under the `v1` prefix if the `api.` subdomain is missing, so I'm updating the requests in API integration tests to have `api.` in their host names.

### What happened
A 404 response with this error message:
> A route matching "/https://api.app.localhost/v1/events/future" could not be found.

(Note the leading slash in the URL)

### What you expected to happen
I expected the provided URL to be routed correctly and return a successful response. The array correctly resolves to `https://api.app.localhost/v1/events/future` when put through `Router::url()` and returns a normal, non-error response when loaded in a browser.

### Notes
The `MissingRouteException` exception is getting thrown in `RouteCollection::parseRequest()`, where `$request->url` is `https://api.app.localhost...`, but `$request->here` is `/https://api.app.localhost...` with a leading slash.

`$request = new ServerRequest(['url' => $url]);` in `IntegrationTestTrait::_url($url)` is taking the correct URL and returning a `$request` with the incorrect `here` property.

This code in `ServerRequest::_setConfig()`
```
if (strlen($config['url'])) {
    $uri = $uri->withPath('/' . $config['url']);
}
...
$this->here = $this->base . '/' . $this->url;
```
causes `$request->uri->path` and `$request->here` to be set with a leading slash.

Then in the `foreach` loop in `RouteCollection::parseRequest`, each possible matching path (e.g. `"/v1/events/future"` is compared against the entire URL that's pulled from `$request->uri->path`, (e.g. `"/https://api.app.localhost/v1/events/future"`) and rejected if the request's path doesn't _begin_ with the candidate path, which `$request->uri->path` never will if a protocol and host are included.

So it's looking like the router can correctly translate the provided URL array into a string (actually, the same `MissingRouteException` is encountered if a URL string is provided), but can't then get the correct route back out of that string as long as the host name is manually specified.  **Is this a bug, or am I going about this wrong?**

### Conclusion
I'm not sure what specifically to suggest for fixing it if it were a bug, but comparing `$paths` in `RouteCollection::parseRequest` to a normalized version of the current path, with `$uri->scheme . '://' . $uri->host` removed, instead of to (potentially) the full URL, might be a good direction to take.

### PR DESCRIPTION
**Pull request by markstory**
When handling array URLs or absolute URLs IntegrationTestCase should forward https and host data to the right place. I was able to replace our URL parsing logic with the Uri implementation from diactoros letting us save a few cycles in each test method.

Fixes #13204

### CODE REVIEW

File: tests/test_app/TestApp/Controller/PostsController.php [hunk 1]
```diff
@@ -116,6 +116,18 @@ public function header()
...
     }
 
+    public function hostData()
+    {
+        $data = [
+            'host' => $this->request->host(),
+            'isSsl' => $this->request->is('ssl'),
+        ];
+
+        debug($data);
```
Comment (ADmad) [inline tests/test_app/TestApp/Controller/PostsController.php]: Leftover `debug()`.
