### PR TITLE
Fix fixture table name derivation to respect custom Inflector rules

### LINKED ISSUE #19124: Inflector rule no longer picked up by PHPUnit in 5.3.0rc2
### Description

Upgraded CakePHP from 5.2.10 to 5.3.0rc2.

Having set

```php
Inflector::rules('uninflected', ['invoice_tax_information']);
```

in bootstrap.php I'm getting this error in PHPUnit Test Runs now:

Cannot describe schema for table `invoice_tax_informations` for fixture `App\Test\Fixture\InvoiceTaxInformationFixture`. The table does not exist.

### CakePHP Version

5.3.0rc2

### PHP Version

8.5

### PR DESCRIPTION
**Pull request by dereuromark**
## Summary
- Fixes #19124 - Custom Inflector rules (like uninflected) are not respected when fixtures derive their table names

The change in #18959 and follow-up #18972 changed fixture table name derivation from using `tableize()` (underscore then pluralize) to pluralizing the CamelCase class name directly. This broke custom Inflector uninflected rules since those rules match against underscored strings.

**Example:** With `Inflector::rules('uninflected', ['invoice_tax_information'])`, the fixture `InvoiceTaxInformationFixture` would incorrectly use `invoice_tax_informations` instead of `invoice_tax_information`.

**Old behavior (5.2.x):**
- `InvoiceTaxInformation` → `underscore()` → `invoice_tax_information` → `pluralize()` → `invoice_tax_information` (uninflected rule matches!)

**Broken behavior (5.3.0rc2):**
- `InvoiceTaxInformation` → `pluralize()` → `InvoiceTaxInformations` → `underscore()` → `invoice_tax_informations`

**Fix:**
Changes `_aliasFromClass()` to use `tableize()` then `camelize()`, which respects custom Inflector rules by doing underscore-then-pluralize (matching how uninflected rules are defined).

### CODE REVIEW

File: tests/TestCase/TestSuite/TestFixtureTest.php [hunk 1]
```diff
@@ -98,6 +100,33 @@ public function testAliasPlural(): void
...
+        Inflector::rules('uninflected', ['invoice_tax_information']);
+        $this->assertSame('invoice_tax_information', Inflector::pluralize('invoice_tax_information'));
+        $this->assertSame('invoice_tax_information', Inflector::tableize('InvoiceTaxInformation'));
+
+        // The alias should be derived using tableize + camelize to respect uninflected rules
+        $this->assertSame(
+            'InvoiceTaxInformation',
+            Inflector::camelize(Inflector::tableize('InvoiceTaxInformation')),
+        );
+    }
```
Comment (markstory) [inline tests/TestCase/TestSuite/TestFixtureTest.php:122]: This doesn't test anything with fixtures. Could we use anonymous classes to better simulate the regression?
