### PR TITLE
Fix MySQL schema reflection when columns have expressions

### LINKED ISSUE #16727: Error in MysqlSchemaDialect, when database scheme contains expression in constraint
### Description

I have migration error, when database scheme contains expression in constraint.

Error dump
```
[Cake\Database\Exception\DatabaseException] Columns used in constraints must be added to the Table schema first. The column "" was not found in table "fin_analytics_update_queue". in /var/www/vendor/cakephp/cakephp/src/Database/Schema/TableSchema.php on line 583
Stack Trace:
- /var/www/vendor/cakephp/cakephp/src/Database/Schema/MysqlSchemaDialect.php:279
- /var/www/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:164
- /var/www/vendor/cakephp/cakephp/src/Database/Schema/Collection.php:123
- /var/www/vendor/cakephp/migrations/src/Command/Phinx/Dump.php:102
- /var/www/vendor/symfony/console/Command/Command.php:291
- /var/www/vendor/symfony/console/Application.php:989
- /var/www/vendor/symfony/console/Application.php:299
- /var/www/vendor/symfony/console/Application.php:171
- /var/www/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:126
- /var/www/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /var/www/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:198
- /var/www/vendor/cakephp/cakephp/src/Console/BaseCommand.php:271
- /var/www/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:152
- /var/www/vendor/cakephp/cakephp/src/Console/BaseCommand.php:179
- /var/www/vendor/cakephp/migrations/src/Command/MigrationsCommand.php:198
- /var/www/vendor/cakephp/cakephp/src/Console/CommandRunner.php:334
- /var/www/vendor/cakephp/cakephp/src/Console/CommandRunner.php:172
- /var/www/bin/cake.php:12
```

MySQL scheme example 
```
create table fin_analytics_update_queue
(
 id int auto_increment primary key,
 config_id int unsigned not null,
 status enum ('new', 'processing', 'completed', 'failed') default 'new' not null,
 created timestamp default CURRENT_TIMESTAMP not null,
 constraint unique_index
 unique (config_id, ((case when ((`status` = _utf8mb4'new') or (`status` = _utf8mb4'processing')) then `status` end)))
);
```

### CakePHP Version

4.3.3

### PHP Version

7.4

### PR DESCRIPTION
**Pull request by markstory**
Skip over empty columns when reflecting schema. Currently schema reflection doesn't support expressions for indexes. This isn't ideal but we are also missing schema generation and migration support for index expressions.

Fixes #16727

### CODE REVIEW

File: src/Database/Schema/MysqlSchemaDialect.php [hunk 1]
```diff
@@ -238,7 +238,9 @@ public function convertIndexDescription(TableSchema $schema, array $row): void
             $name = $type = TableSchema::CONSTRAINT_PRIMARY;
         }
 
-        $columns[] = $row['Column_name'];
+        if (strlen($row['Column_name'] ?? '')) {
```
Comment (othercorey) [inline src/Database/Schema/MysqlSchemaDialect.php]:
```suggestion
        if (!empty($row['Column_name'])) {
```

Comment (markstory) [reply src/Database/Schema/MysqlSchemaDialect.php]: I was concerned with `0` being used as a field name by userland code. Perhaps I'm being overly cautious though.
