### PR TITLE
2.6 jsonView should throw exception if json_encode fails

### LINKED ISSUE #3141: 2.5 - jsonView should throw exception if json_encode fails.
JsonView will produce an empty HTTP response if json_encode fails. This can create a lot of confusion for a developer trying to understand why the controller's action is executing correctly, but the response from the server is empty.

When json_encode fails the return value is just false.

The `_serialize` method could be changed to something like this.

```
		$json = version_compare(PHP_VERSION, '5.4.0', '>=') && Configure::read('debug')
			? json_encode($data, JSON_PRETTY_PRINT)
			: json_encode($data);
		if(json_last_error() !== JSON_ERROR_NONE)
		{
			throw new CakeException(json_last_error_msg());
		}
		return $json;
```

json_encode will fail if `$data` contains any non-UTF-8 character encoded strings.

### PR DESCRIPTION
**Pull request by robmcvey**
Closes https://github.com/cakephp/cakephp/issues/3141

Seems this issue lay dormant, but solution given by @dereuromark in https://github.com/dereuromark/cakephp/commit/7b6238613de79bb0135d557a182c663ad3e9f8a1 seems a good fix.

I've added extra catch for if `json_last_error()` nor `json_last_error_msg()` are present.

### CODE REVIEW

File: lib/Cake/View/JsonView.php [hunk 1]
```diff
@@ -145,10 +149,22 @@ protected function _serialize($serialize) {
...
 
-		return json_encode($data);
+		if (function_exists('json_last_error') && json_last_error() !== JSON_ERROR_NONE) {
+			if (function_exists('json_last_error_msg')) {
+				$error = json_last_error_msg();
+			} else {
+				$error = __('JSON encoding failed: Error code %s', json_last_error());
+			}
+			throw new CakeException($error);
+		} else if ($json === false) {
```
Comment (dereuromark) [inline lib/Cake/View/JsonView.php]: should be elseif

**Comment by dereuromark** [comment]
I don't think we should translate those internal server errors. What do others think?

**Comment by markstory** [comment]
There are still a [few PHPCS errors](https://travis-ci.org/cakephp/cakephp/jobs/54272911).

@dereuromark Agreed, those error messages do not need to be translated.

File: lib/Cake/View/JsonView.php [hunk 2]
```diff
@@ -145,10 +149,22 @@ protected function _serialize($serialize) {
...
 
 		if (version_compare(PHP_VERSION, '5.4.0', '>=') && Configure::read('debug')) {
-			return json_encode($data, JSON_PRETTY_PRINT);
+			$json = @json_encode($data, JSON_PRETTY_PRINT);
+		} else {
+			$json = @json_encode($data);
 		}
 
-		return json_encode($data);
+		if (function_exists('json_last_error') && json_last_error() !== JSON_ERROR_NONE) {
```
Comment (ADmad) [inline lib/Cake/View/JsonView.php]: You can backport the [json_last_error()](https://github.com/cakephp/cakephp/blob/3.0/src/basics.php#L132) added to basics.php in 3.0.

**Comment by robmcvey** [comment]
Suppressing the json_encode warnings with `@` fails code sniffer, but without PHPUnit throws `PHPUnit_Framework_Error_Warning` before we can catch anything in the test case.

What would be the best approach to get around this? set_error_handler() ?

**Comment by lorenzo** [comment]
Use `set_error_handler` in the test

File: lib/Cake/Test/Case/View/JsonViewTest.php [hunk 3]
```diff
@@ -28,12 +28,27 @@
...
 	}
 
 /**
+ * tearDown method
+ *
+ * @return void
+ **/
+	public function tearDown() {
+		parent::tearDown();
+		restore_error_handler();
```
Comment (markstory) [inline lib/Cake/Test/Case/View/JsonViewTest.php]: You should only restore the error handler when you change it. Otherwise you can end up popping off phpunits error handler.

**Comment by robmcvey** [comment]
Ah OK thanks, would this be the preferred way?

```php
try {
	$View->render();
	$this->fail('Failed asserting that exception of type "CakeException" is thrown.');
} catch (CakeException $e) {
	restore_error_handler();
	return;
}

**Comment by markstory** [comment]
@robmcvey That looks good to me. I would normally do some assertions in the catch block too.

**Comment by lorenzo** [comment]
Good job @robmcvey :)
