### PR TITLE
Fix empty string hiddenField values

### LINKED ISSUE #16254: Allow empty string as value for FormHelper::checkbox()'s hiddenField
### Description

I was wondering if there's a reason that in `FormHelper::checkbox()` and `FormHelper::radio()` (and also `select()` and `multiCheckbox()`) the check for `hiddenField` looks like ...

```
if ($options['hiddenField']) {
```

... and not like ...

```
if ($options['hiddenField'] !== false) {
```

The odd thing about this is that the default value for radios is an empty string, however, it's not possible to have checkboxes with the same value (default value is `0`) as the `if`-check in the helper methods obviously isn't fulfilled by `''`. Hence when setting it to an empty string for `FormHelper::checkbox()`, no hidden field is rendered at all which feels like a somewhat unexpected behaviour to me.

### CakePHP Version

4.3

### PHP Version

_No response_

### PR DESCRIPTION
**Pull request by markstory**
While hiddenField is documented it can also be a string. We've had this behavior (with tests) since 2.1 so we might as well keep it. Expand this behavior to with ''.

Align both checkbox() and radio() to handle `hiddenField = ''` consistently as them being different is clunky.

Fixes #16254

### CODE REVIEW

File: src/View/Helper/FormHelper.php [hunk 1]
```diff
@@ -1503,7 +1503,7 @@ public function checkbox(string $fieldName, array $options = [])
         $options['value'] = $value;
 
         $output = '';
-        if ($options['hiddenField']) {
+        if ($options['hiddenField'] !== false && is_scalar($options['hiddenField'])) {
```
Comment (othercorey) [inline src/View/Helper/FormHelper.php:1506]: Should this be cast to string when assigned to `value`?
