### PR TITLE
Fixed nested contains

### LINKED ISSUE #7591: [3.1] Strange (maybe faulty?) behaviour with contain().
Hi there :)
 I am having a strange issue with contain() and not sure about the cause.

The DB: http://pastebin.com/HCxUVtS9
The AssessmentsTable: http://pastebin.com/CYfFnd2e
The CustomersTable: http://pastebin.com/Hvk5fRQm

In summary, I have Assessments belongsTo Customers belongstTo Companies belongsTo Groups.

In CustomersTable::getBaseQuery() everything works fine, but in Assessments::getBaseQuery() I get an erorr that reads: "Assessments is not associated with Companies".

I am not aware that I am trying to join Companies to Assessments anywhere???

PHP 5.4.25
Apache: 2.2.22
MySQL: 5.5.24

Any assistance would be great.

### PR DESCRIPTION
**Pull request by lorenzo**
Closes #7591

### CODE REVIEW

File: src/ORM/EagerLoader.php [hunk 1]
```diff
@@ -334,14 +334,22 @@ public function attachAssociations(Query $query, Table $repository, $includeFiel
...
+                    'propertyPath' => $loadable->propertyPath(),
+                    'includeFields' => $includeFields,
+                ];
+                $loadable->instance()->attachTo($query, $config);
+                $processed[$alias] = true;
+            }
+
+            $newAttachable = $this->attachableAssociations($repository);
+            $attachable = array_diff_key($newAttachable, $processed);
+        } while ($attachable);
```
Comment (markstory) [inline src/ORM/EagerLoader.php]: Should this be `while (!empty($attachable)`? Seems like the kind of thing scrutinizer whines about.

Comment (lorenzo) [inline src/ORM/EagerLoader.php]: Good idea

**Comment by lorenzo** [comment]
@markstory done
