### PR TITLE
Add fix and tests for #6402

### LINKED ISSUE #6402: Time "00:00:00"
If in my database table I have field type TIME and I put value like "00:00:00" or "00:15:00" in, I have a trouble to get it by model. Cake\I18n\Time Object isn't created.

### PR DESCRIPTION
**Pull request by dereuromark**
Should fix https://github.com/cakephp/cakephp/issues/6402

The null change should only be made of date(time) that contain a date, not pure time values.

### CODE REVIEW

File: src/Database/Type/DateTimeType.php [hunk 1]
```diff
@@ -103,7 +103,7 @@ public function toDatabase($value, Driver $driver)
      */
     public function toPHP($value, Driver $driver)
     {
-        if ($value === null || (int)$value === 0) {
+        if ($value === null || strpos($value, '-') !== false && (int)$value === 0) {
```
Comment (lorenzo) [inline src/Database/Type/DateTimeType.php]: new idea, that will save one function call: `strpos($value, '0000-00-00') === 0`
