### PR TITLE
Throwing exceptions in Type::toDatabase()

### LINKED ISSUE #7494: Database type classes should throw exception for objects
When providing an object  or array to any of the database Type classes, and the class does not know how to convert this object to the right representation, we should throw an exception.

I have run into a few problems where we were too friendly by converting anything to a string, for example an array.

It is not immediately obvious that the developer passed a wrong data type as often there is no SQL error.

### PR DESCRIPTION
**Pull request by lorenzo**
Fixes #7494

### CODE REVIEW

File: src/Database/Type/StringType.php [hunk 1]
```diff
@@ -0,0 +1,97 @@
...
+     * @param Driver $driver The driver instance to convert with.
+     * @return string|null
+     */
+    public function toDatabase($value, Driver $driver)
+    {
+        if ($value === null || is_string($value)) {
+            return $value;
+        }
+
+        if (is_object($value) && method_exists($value, '__toString')) {
```
Comment (ADmad) [inline src/Database/Type/StringType.php]: Nice!

File: src/Database/Type.php [hunk 2]
```diff
@@ -49,6 +52,7 @@ class Type
      * for doing conversion on these
      *
      * @var array
+     * @deprecated 3.1 All types will now use a specific class
      */
```
Comment (markstory) [inline src/Database/Type.php]: Seems like a good idea to require classes.

File: src/Database/Type/StringType.php [hunk 3]
```diff
@@ -0,0 +1,97 @@
...
+     * @param Driver $driver The driver.
+     * @return int
+     */
+    public function toStatement($value, Driver $driver)
+    {
+        return PDO::PARAM_STR;
+    }
+
+    /**
+     * Marshalls request data into PHP floats.
```
Comment (markstory) [inline src/Database/Type/StringType.php]: Docs are wrong.
