### PR TITLE
#9848 PaginatorComponent.php ignores maxLimit

### LINKED ISSUE #9848: maxLimit is ignored in PaginatorComponent.php
This is a (multiple allowed):

* [x] bug
* [ ] enhancement
* [ ] feature-discussion (RFC)

* CakePHP Version: 3.3.9
* Platform and Target: This phenomenon seems not depend on platform.

### What you did

One of the options `maxLimit` was ignored in my application, and I checked the codes.
Finally, I found a suspicious code in `cakephp/src/Controller/Component/PaginatorComponent.php`.
I wrote some test codes, and the error occured.

The test codes I added is shown below.

```php
/**
 * test getDefaults with limit > maxLimit in code.
 *
 * @return void
 */
public function testGetDefaultMaxLimit()
{
    $settings = [
        'page' => 1,
        'limit' => 2,
        'maxLimit' => 10,
        'order' => [
            'Users.username' => 'asc'
        ],
    ];
    $result = $this->Paginator->mergeOptions('Post', $settings);
    $expected = [
        'page' => 1,
        'limit' => 2,
        'maxLimit' => 10,
        'order' => [
            'Users.username' => 'asc'
        ],
        'whitelist' => ['limit', 'sort', 'page', 'direction']
    ];
    $this->assertEquals($expected, $result);

    $settings = [
        'page' => 1,
        'limit' => 100,
        'maxLimit' => 10,
        'order' => [
            'Users.username' => 'asc'
        ],
    ];
    $result = $this->Paginator->mergeOptions('Post', $settings);
    $expected = [
        'page' => 1,
        'limit' => 10,
        'maxLimit' => 10,
        'order' => [
            'Users.username' => 'asc'
        ],
        'whitelist' => ['limit', 'sort', 'page', 'direction']
    ];
    $this->assertEquals($expected, $result);
}
```

### What happened
The error shown below occured in the test.

```php

gorogoroyasu$ vendor/bin/phpunit tests/TestCase/Controller/Component/PaginatorComponentTest.php
PHPUnit 5.7.2 by Sebastian Bergmann and contributors.

.............F.............................                       43 / 43 (100%)

Time: 302 ms, Memory: 14.25MB

There was 1 failure:

1) Cake\Test\TestCase\Controller\Component\PaginatorComponentTest::testGetDefaultMaxLimit
Failed asserting that two arrays are equal.
--- Expected
+++ Actual
@@ @@
 Array (
     'page' => 1
-    'limit' => 10
-    'maxLimit' => 10
+    'limit' => 100
+    'maxLimit' => 100
     'order' => Array (...)
     'whitelist' => Array (...)
 )

/Users/gorogoroyasu/cakephp3-core/cakephp/tests/TestCase/Controller/Component/PaginatorComponentTest.php:550

FAILURES!
Tests: 43, Assertions: 94, Failures: 1.
```

### What you expected to happen
If `maxLimit` is given in array `$settings`, the `limit` value in array `$result` should be equal to `maxLimit`, though it wasn't.
In conclusion, I regard this phenomenon as bug.

I showed an example to fix this bug in #9849 ,
please review it, and I expect for some comments.
If my PullRequest is not worth to merge, don't hesitate to close it.

Thanks for your attention.

### PR DESCRIPTION
**Pull request by gorogoroyasu**
Fixes #9848

### CODE REVIEW

**Comment by chinpei215** [comment]
@gorogoroyasu Sorry, but I changed the description, as it was a message template.

File: src/Controller/Component/PaginatorComponent.php [hunk 1]
```diff
@@ -299,13 +299,23 @@ public function getDefaults($alias, $defaults)
...
+        if (empty($defaults['limit'])) {
+            $defaults['maxLimit'] = $maxLimit;
+            $defaults['limit'] = $limit;
+        }
+
+        $defaults['maxLimit'] = $maxLimit;
+        $defaults['limit'] = $limit;
 
-        return $defaults + $this->config();
+        return $defaults + $config;
```
Comment (dereuromark) [inline src/Controller/Component/PaginatorComponent.php]: The code should **never** have something like `$defaults + $config`.
As $config by definition should be higher than $defaults in priority of merging. And is exactly the opposite here.
I think that may play into it here. Either way we need to fix the variables here to avoid future confusion and issues.

**Review by dereuromark — CHANGES_REQUESTED** [review]

**Review by dereuromark — APPROVED** [review]

File: src/Controller/Component/PaginatorComponent.php [hunk 2]
```diff
@@ -287,35 +287,35 @@ public function mergeOptions($alias, $settings)
...
+            $settings['limit'] = $limit;
         }
 
-        $defaults['maxLimit'] = $maxLimit;
-        $defaults['limit'] = $limit;
+        $settings['maxLimit'] = $maxLimit;
+        $settings['limit'] = $limit;
 
-        return $defaults + $config;
+        return array_merge($default, $settings);
```
Comment (gorogoroyasu) [inline src/Controller/Component/PaginatorComponent.php]: Thanks for your comments.
I fixed the variable names(from $default to $defaults) , and removed the function `array_merge`.

Additionally, I have an proposal.
This method seems not to be called from any other classes, so I think it should be private function. How do you think?

Comment (dereuromark) [inline src/Controller/Component/PaginatorComponent.php]: If it is now public API, you cannot do that until the next major one.

File: src/Controller/Component/PaginatorComponent.php [hunk 3]
```diff
@@ -287,25 +287,35 @@ public function mergeOptions($alias, $settings)
...
+        $maxLimit = isset($settings['maxLimit']) ? $settings['maxLimit'] : $defaults['maxLimit'];
+        $limit = isset($settings['limit']) ? $settings['limit'] : $defaults['limit'];
+
+        if ($limit > $maxLimit) {
+            $limit = $maxLimit;
         }
+        if (empty($settings['limit'])) {
+            $settings['maxLimit'] = $maxLimit;
+            $settings['limit'] = $limit;
+        }
```
Comment (chinpei215) [inline src/Controller/Component/PaginatorComponent.php]: This `if` block seems redundant to me.

File: src/Controller/Component/PaginatorComponent.php (hunk 2 above)
Comment (gorogoroyasu) [inline src/Controller/Component/PaginatorComponent.php]: Ok, I got it.
I expect this API will be private one in the next major version.

File: src/Controller/Component/PaginatorComponent.php (hunk 3 above)
Comment (gorogoroyasu) [inline src/Controller/Component/PaginatorComponent.php]: That's true. I removed these four lines.
Thanks.
