### PR TITLE
fixes #9064 - added new locale for Icelandic language

### LINKED ISSUE #9064: Inconsistent `locale` ?
L10n::_l10nCatalog contains an array of languages. The value of 'locale' key seems to be inconsistent. Sometimes it is 3 letters code, in other cases it is 4 letters. 

Currently I'm using 4 letters locale and `'is' => array('language' => 'Icelandic', 'locale' => 'is_is', 'localeFallback' => 'isl', 'charset' => 'utf-8', 'direction' => 'ltr'),` doesn't apply to all cases. Fx that does not work with is_IS locale.
Is there a good reason why, for example it is 'locale' => 'dan', 'localeFallback' => 'dan' for example but not 'locale' => 'da_dk', 'localeFallback' => 'dan'?

can I make a PR to add is-is to the list ?

### PR DESCRIPTION
**Pull request by alex2690**

### CODE REVIEW

File: lib/Cake/I18n/L10n.php [hunk 1]
```diff
@@ -272,6 +272,7 @@ class L10n {
 		'hy' => array('language' => 'Armenian - Armenia', 'locale' => 'hye', 'localeFallback' => 'hye', 'charset' => 'utf-8', 'direction' => 'ltr'),
 		'id' => array('language' => 'Indonesian', 'locale' => 'ind', 'localeFallback' => 'ind', 'charset' => 'utf-8', 'direction' => 'ltr'),
 		'is' => array('language' => 'Icelandic', 'locale' => 'isl', 'localeFallback' => 'isl', 'charset' => 'utf-8', 'direction' => 'ltr'),
+		'is-is' => array('language' => 'Icelandic', 'locale' => 'is_is', 'localeFallback' => 'isl', 'charset' => 'utf-8', 'direction' => 'ltr'),
```
Comment (bancer) [inline lib/Cake/I18n/L10n.php]: Perhaps it should be `'language' => 'Icelandic (Iceland)'` like in other places?

**Comment by lorenzo** [comment]
Thanks!
