### PR TITLE
4.4 -  Start Error Renderer changes

### LINKED ISSUE #16228: 4.4 - Error and Exception Handling Improvements
### Description

Having error handling and exception rendering responsibilities are distributed awkwardly. An example of this is that `ErrorHandler::register()` also binds a default exception handler. Part of this is because of how fatal errors are handled and treated as exceptions. I now believe that converting fatal errors into exceptions should be consolidated with the default exception handler abstraction. I propose we introduce a new error handler system that treats non-fatal errors separately from fatal ones as they generally require different actions to be taken. Introducing a new subsystem does create an upgrade challenge for applications but is much lower-risk for us and developers. We have used the parallel sub-system upgrade path a few times and has worked well most of the time.

## Handling Non-Fatal Errors

Non-fatal errors can have a variety of actions taken for them. One or many of the following may be the desired action:

* Ignored
* Logged
* Output to STDERR console environments or as HTML in web contexts.

The output implementation is currently implemented as subclasses, which complicates error monitoring integrations as developers need to extend multiple classes in order to handle all environments. An example of this comes up when trying to integrate Sentry for one of my applications. While the `ErrorLoggerInterface` is a good solution for monitoring services we could build more powerful developer tools if we could reliably replace the output. Plugins like DebugKit could provider richer help/context without additional user configuration. 

I believe a better solution for the future is to have non-fatal error rendering have the output handled separately from exception handling. I also think we should have simpler callback interface for error notifications that doesn't require implementing the `ErrorLoggerInterface`. Additionally rendering should be implemented via adapters and not sub-classes. CakePHP can intelligently choose a default based on the SAPI.

A prototype of a possible interface and class names for the above is:

```php
// in bootstrap.php

// Good names like ErrorHandler are already in use. Would really appreciate feedback/suggestions here.
use Cake\Error\ErrorTrap;

// Create an error trap.
$errortrap = new ErrorTrap(Configure::read('Error'));

// Desired bootstrap addition
(new ErrorTrap(Configure::read('Error')))->register();

// Imperitive API
$errorTrap = new ErrorTrap();

// Add closures that are called on each non-fatal error.
// This covers logging and error-monitoring relatively easy and allows
// plugins to provide common saas or self-hosted solutions.
// Signature for callbacks would be `function (\Cake\Error\PhpError $error): void`
$errorTrap->addCallback(Closure::fromCallable([DebugKitErrorTrap::class, 'recordDeprecation']));

// Register the trap.
$errorTrap->register();

// Force a renderer  (not implemented)
$errorTrap->setRenderer(new CustomErrorRenderer());

// Set error trap level. Doing after register will replace the existing error handler.
// Or raise an exception. I'm not sure which is better.  (not implemented)
$errorTrap->setLevel(E_ALL);

// Classname or instance. Reuse the existing ErrorLoggerInterface as it fits the requirements
// and helps reduce upgrade pain.  (not implemented)
$trap->setLogger(CustomErrorLogger::class);

// Turn logging on with additional configuration.  (not implemented)
$errorTrap->enableLogging(['trace' => true]);
```

Configuration data under the `Error` key:

- `errorLevel` Same as today.
- `ignoredDeprecationPaths` Same as today.
- `log` Set to true to enable logging. Same as today.
- `logger` The name of the logger class or a `Cake\Error\ErrorLoggerInterface` instance. If a classname is used, the current configuration of `ErrorTrap` will be provided as a constructor argument.
- `errorRenderer` The classname or instance of the error renderer to use
- `extraFatalErrorMemory` Same as today.
- `trace` Same as today.

### Error Objects

Callbacks and internal methods would receive `Cake\Error\PhpError` objects. This object would encapsulate the various parameters to the error handler callback and include the stack trace as well.

### Error Renderers

Error Renderers are responsible for coverting `ErrorObject` instances into SAPI appropriate or application appropriate output. Several named output formats and formatting functionality lives in `Debugger` currently. The addition of `ErrorRenderer` objects would allow us to extract logic from a complex and re-use it. This approach will also unblock DebugKit from replacing error output with one that leverages Toolbar Panels better.

```php
namespace Cake\Error;

interface ErrorRenderer
{
    public function render(ErrorObject $error): string;
}
```

Is the most minimal interface that covers all of the existing scenarios that Debugger has. 

## Handling Exceptions and Fatal Errors

Exception Rendering is mostly good. What isn't good is that the `ErrorHandler` has a method to get an exception renderer. Per the above proposal these concerns should be separated. In the new system an `ExceptionTrap` class would be added. A prototype of this class is:

```php
// Trying to keep name aligned with the ErrorTrap from above.
use Cake\Error\ExceptionTrap;

// Use config to create an instance.
$trap = new ExceptionTrap(Configure::read('Error'));

// Register this trap as the default exception and fatal-error handler.
// Also set it as the singleton value.
$trap->register();

// Get the singleton. Useful in the Middleware.
$trap = ExceptionTrap::instance();

// Desired bootstrap addition
(new ExceptionTrap(Configure::read('Error')))->register();
```

If we are going to make users update their applications we can at least remove some noise from their `Application::middleware()`. By having the exception trap as a singleton we can easily get a reference to the object used in bootstrapping. And the default exception handler is already effectively a singleton as there can be only one active at a time.

Imperitive configuration and manipulation methods:

```php
// Register a default exception and fatal error handler. Should this be registerHandler()?
$trap->register();

// Add a callback for exceptions trapped by $trap.
// Signature for callbacks would be `function (Throwable $error): void`
$trap->addCallback(Closure::fromCallable([DebugKitErrorTrap::class, 'recordDeprecation']));

// Define the controller used to render error pages if you can't use App\Controller\ErrorController
$trap->setController(CustomErrorController::class);

// Enable logging (not implemented)
$trap->enableLogging();

// Classname or instance  (not implemented)
$trap->setLogger(CustomErrorLogger::class);

// Classname or instance. Reuse existing ExceptionRendering as I think it generally works well.  (not implemented)
$trap->setRenderer(CustomExceptionRenderer::class);
```

Configuration data under the `Error` key:

- `exceptionRenderer` Class name, Closure or instance. Currently instances are not supported but I think they should be to improve compatibility with the DI container.
- `logger` The name of the logger class or a `Cake\Error\ErrorLoggerInterface` instance. If a classname is used, the current configuration of `ErrorTrap` will be provided as a constructor argument.
- `log` Set to true to enable logging. Same as today.
- `trace` Same as today.

### Events as an alternative

The `addCallback()` methods could be skipped and we could leverage events instead. This would allow application developers to bind events to the global EventManager and be notified of errors and exceptions that way.

## ErrorHandlerMiddleware Changes

The ErrorHandlerMiddleware will need changes to its constructor. I'm proposing we accept either the old or use the global instance to  encapsulate switching between them within the middleware to improve backwards compatibility the new and existing paths should be separate functions. The duplicate code while annoying in the short term makes future clean-up easier and safer.

### Open Questions

- [x] Are the method names and class names clear enough ?
- [x] Are the changes to separate fatal and non-fatal error handling worth the effort and application code churn?
- [x] Should we use events or the `addCallback` method instead?

### CakePHP Version

4.4.0

### Changes

- Removed the imperative interfaces for both `ErrorTrap` and `ExceptionTrap`. Because the primary usage scenario for these objects is to consume a configuration array during application bootstrap the imperative methods will not be frequently used, and we shouldn't expose more public API than we need.

### PR DESCRIPTION
**Pull request by markstory**
Start building out the new Error rendering sub-system. These changes include the object wrapper for PHP Errors and simple renderer to act as a proof of concept on how the new system can deprecate the existing formatting mess in Debugger.

We won't be able to remove any templates or formating logic as userland code could have custom formats, or extend/reference the existing template strings. :cry:

### CODE REVIEW

File: src/Error/Debugger.php [hunk 1]
```diff
@@ -110,6 +111,19 @@ class Debugger
...
+     * Mapping for error renderers.
+     *
+     * Error renderers are replacing output formatting with
+     * an object based system. Having Debugger handle and render errors
+     * will be deprecated and the new ErrorTrap system should be used instead.
+     *
+     * @array <string, class-string>
+     */
+    protected $renderers = [
+        'txt' => TextRenderer::class,
```
Comment (othercorey) [inline src/Error/Debugger.php:127]: `txt` is a little ambiguous. Is this a console output or does the text renderer get used for other things?

File: src/Error/PhpError.php [hunk 2]
```diff
@@ -0,0 +1,191 @@
...
+
+/**
+ * Object wrapper around PHP errors that are emitted by `trigger_error()`
+ */
+class PhpError
+{
+    /**
+     * @var int
+     */
+    private $code;
```
Comment (othercorey) [inline src/Error/PhpError.php:27]: Is this class meant to be final?

We could type the properties now that 4.4 is php 7.4+.

File: src/Error/PhpError.php [hunk 3]
```diff
@@ -0,0 +1,191 @@
...
+        $this->line = $line;
+        $this->trace = $trace;
+    }
+
+    /**
+     * Get the PHP error constant.
+     *
+     * @return string
+     */
+    public function getCode(): int
```
Comment (othercorey) [inline src/Error/PhpError.php:110]: Should this be `code()` instead of `getCode()`?

File: src/Error/Debugger.php (hunk 1 above)
Comment (markstory) [reply src/Error/Debugger.php:127]: It is one of the existing output formats that `Debugger` has. This starts the replacement of our default built-in output formats with the new system.

Comment (othercorey) [reply src/Error/Debugger.php:127]: Ah, ok. So it will probably be console output, but it's not tied to an IO stream of any kind.

Can we just name it 'text' then?

File: src/Error/PhpError.php (hunk 2 above)
Comment (markstory) [reply src/Error/PhpError.php:27]: > Is this class meant to be final?

No I just don't see a use case for allowing subclasses to read/write these properties directly when we have read accessor methods. I see PhpError objects as immutable. There are no useful scenarios I can see right now where we would ever need to mutate an instance.

File: src/Error/PhpError.php (hunk 3 above)
Comment (markstory) [reply src/Error/PhpError.php:110]: It could be. I was thinking it could be more ergonomic to emulate the existing methods of `Exception` so that users have to remember fewer methods names if they ever need to interact with error and exception handlers.

Comment (othercorey) [reply src/Error/PhpError.php:110]: I assumed you were following Exception. I'd like to start promoting more of these style guides in Cake in the future although modifying anything existing would be really annoying.

Arbitrary using get or or not starts to get messy. Something to discuss.

Comment (markstory) [reply src/Error/PhpError.php:110]: That's fair I can put together an update to the internal development docs on method naming conventions and when to diverge from them.

File: src/Error/Debugger.php (hunk 1 above)
Comment (markstory) [reply src/Error/Debugger.php:127]: We could. The existing format uses `txt`. We could add `text` as well though.

Comment (othercorey) [reply src/Error/Debugger.php:127]: Ok, up to you, if you're trying to support something existing.

**Comment by markstory** [comment]
Added the HTML/JS renderer as well.

File: src/Error/Renderer/HtmlRenderer.php [hunk 4]
```diff
@@ -0,0 +1,94 @@
...
+     * @param string $id The error id scope.
+     * @param string $suffix The element selector.
+     * @return string
+     */
+    private function renderToggle(string $text, string $id, string $suffix): string
+    {
+        $selector = $id . '-' . $suffix;
+
+        // phpcs:disable
+        return <<<HTML
```
Comment (othercorey) [inline src/Error/Renderer/HtmlRenderer.php:85]: Now that cakephp 4.4 uses PHP 7.4, we can indent the Heredoc and Nowdoc lines:

https://www.php.net/manual/en/migration73.new-features.php#migration73.new-features.core.heredoc

File: src/Error/Debugger.php [hunk 5]
```diff
@@ -110,6 +113,23 @@ class Debugger
...
+     * will be deprecated and the new ErrorTrap system should be used instead.
+     *
+     * @var array<string, class-string>
+     */
+    protected $renderers = [
+        // Backwards compatible alias for text that will be deprecated.
+        'txt' => TextRenderer::class,
+        'text' => TextRenderer::class,
+        // The html alias currently uses no JS and will be deprecated.
+        'js' => HtmlRenderer::class,
```
Comment (othercorey) [inline src/Error/Debugger.php:130]: Do we need a `json` renderer?

File: src/Error/Debugger.php [hunk 6]
```diff
@@ -922,6 +942,16 @@ public function outputError(array $data): void
         ];
         $data += $defaults;
 
+        $outputFormat = $this->_outputFormat;
+        if (isset($this->renderers[$outputFormat])) {
+            $trace = static::trace(['start' => $data['start'], 'format' => 'points']);
+            $error = new PhpError($data['code'], $data['description'], $data['file'], $data['line'], $trace);
+            $renderer = new $this->renderers[$outputFormat]();
+            echo $renderer->render($error);
```
Comment (othercorey) [inline src/Error/Debugger.php:950]: Should this be clearing output first?

File: src/Error/Debugger.php (hunk 5 above)
Comment (markstory) [reply src/Error/Debugger.php:130]: Debugger doesn't currently have a JSON output format.

File: src/Error/Debugger.php (hunk 6 above)
Comment (markstory) [reply src/Error/Debugger.php:950]: I don't think so, PHP errors can happen many times in a request and clearing the output buffer could drop user output. I'm also trying to preserve behavior with existing functionality.

**Comment by othercorey** [comment]
Looks ok to me. I haven't really had time to evaluate the design in-depth, but seems simple enough.
